table Query1


    column 'CHARGED_DATE'
        dataType: string
        summarizeBy: none
        sourceColumn: CHARGED_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TRANSACTION_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: TRANSACTION_TYPE

        

        annotation SummarizationSetBy = Automatic

        



    partition 'Query1' = m
        mode: import
        source = 
            	let
					Source = Excel.Workbook(File.Contents("C:\\Users\\PowerBIUser\\Documents\\sample_data.xlsx"), null, true),
					Sheet1_Sheet = Source{{[Item = "Sheet1",Kind = "Sheet"]}}[Data],
					#"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars = true]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(#"Promoted Headers"),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"CHARGED_DATE", type text}, {"TRANSACTION_TYPE", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table