table Sheet1

	measure 'Units Measure' = SUM(Sheet1[Units])

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order ID'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = User

	column 'Order Date'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = User

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		summarizeBy: none
		sourceColumn: Product Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Quantity

		annotation SummarizationSetBy = User

	column Discount
		dataType: double
		summarizeBy: none
		sourceColumn: Discount

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Region Sales' = Sheet1[Region] & " Sales"
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Region Split' = ```
			
			    SWITCH(
			        TRUE(),
			        Sheet1[Region Sales] = "North Sales", "North East",
			        Sheet1[Region Sales] = "East Sales", "North East",
			        Sheet1[Region Sales] = "South Sales", "South West",
			        Sheet1[Region Sales] = "West Sales", "South West"
			    )
			```
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Units = Sheet1[Sales]/Sheet1[Quantity]
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Sheet1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\CodehiveBIVM\Desktop\Datasets\sample_sales_data.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order ID", Int64.Type}, {"Order Date", Int64.Type}, {"Region", type text}, {"Product Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

