table 'Orders'


    column '_row_id'
        dataType: int64
        summarizeBy: none
        sourceColumn: _row_id

        annotation SummarizationSetBy = Automatic

        
    column 'Row_ID'
        dataType: int64
        summarizeBy: none
        sourceColumn: Row_ID

        annotation SummarizationSetBy = Automatic

        
    column 'Order_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: Order_ID

        annotation SummarizationSetBy = Automatic

        
    column 'Order_Date'
        dataType: datetime
        summarizeBy: none
        sourceColumn: Order_Date

        annotation SummarizationSetBy = Automatic

        
    column 'Ship_Date'
        dataType: datetime
        summarizeBy: none
        sourceColumn: Ship_Date

        annotation SummarizationSetBy = Automatic

        
    column 'Ship_Mode'
        dataType: string
        summarizeBy: none
        sourceColumn: Ship_Mode

        annotation SummarizationSetBy = Automatic

        
    column 'Customer_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: Customer_ID

        annotation SummarizationSetBy = Automatic

        
    column 'Customer_Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Customer_Name

        annotation SummarizationSetBy = Automatic

        
    column 'Segment'
        dataType: string
        summarizeBy: none
        sourceColumn: Segment

        annotation SummarizationSetBy = Automatic

        
    column 'Country_Region'
        dataType: string
        summarizeBy: none
        sourceColumn: Country_Region

        annotation SummarizationSetBy = Automatic

        
    column 'City'
        dataType: string
        summarizeBy: none
        sourceColumn: City

        annotation SummarizationSetBy = Automatic

        
    column 'State_Province'
        dataType: string
        summarizeBy: none
        sourceColumn: State_Province

        annotation SummarizationSetBy = Automatic

        
    column 'Postal_Code'
        dataType: string
        summarizeBy: none
        sourceColumn: Postal_Code

        annotation SummarizationSetBy = Automatic

        
    column 'Region'
        dataType: string
        summarizeBy: none
        sourceColumn: Region

        annotation SummarizationSetBy = Automatic

        
    column 'Product_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: Product_ID

        annotation SummarizationSetBy = Automatic

        
    column 'Category'
        dataType: string
        summarizeBy: none
        sourceColumn: Category

        annotation SummarizationSetBy = Automatic

        
    column 'Sub_Category'
        dataType: string
        summarizeBy: none
        sourceColumn: Sub_Category

        annotation SummarizationSetBy = Automatic

        
    column 'Product_Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Product_Name

        annotation SummarizationSetBy = Automatic

        
    column 'Sales'
        dataType: double
        summarizeBy: none
        sourceColumn: Sales

        annotation SummarizationSetBy = Automatic

        
    column 'Quantity'
        dataType: int64
        summarizeBy: none
        sourceColumn: Quantity

        annotation SummarizationSetBy = Automatic

        
    column 'Discount'
        dataType: double
        summarizeBy: none
        sourceColumn: Discount

        annotation SummarizationSetBy = Automatic

        
    column 'Profit'
        dataType: double
        summarizeBy: none
        sourceColumn: Profit

        annotation SummarizationSetBy = Automatic

        



    partition 'Orders' = m
        mode: import
        source = 
            let
				Source = / * Connect to data source based on context * /,
				#"Renamed Columns" = Table.RenameColumns(Source,
				{{"_row_id",
				"_row_id"},
				{"Row_ID",
				"Row_ID"},
				{"Order_ID",
				"Order_ID"},
				{"Order_Date",
				"Order_Date"},
				{"Ship_Date",
				"Ship_Date"},
				{"Ship_Mode",
				"Ship_Mode"},
				{"Customer_ID",
				"Customer_ID"},
				{"Customer_Name",
				"Customer_Name"},
				{"Segment",
				"Segment"},
				{"Country_Region",
				"Country_Region"},
				{"City",
				"City"},
				{"State_Prov
			in
				ce", "State_Prov
        



    annotation PBI_ResultType = Table