table 'People'


    column '_row_id'
        dataType: int64
        summarizeBy: none
        sourceColumn: _row_id

        annotation SummarizationSetBy = Automatic

        
    column 'Regional_Manager'
        dataType: string
        summarizeBy: none
        sourceColumn: Regional_Manager

        annotation SummarizationSetBy = Automatic

        
    column 'Region'
        dataType: string
        summarizeBy: none
        sourceColumn: Region

        annotation SummarizationSetBy = Automatic

        
    column 'Area'
        dataType: string
        summarizeBy: none
        sourceColumn: Area

        annotation SummarizationSetBy = Automatic

        
    column 'Country'
        dataType: string
        summarizeBy: none
        sourceColumn: Country

        annotation SummarizationSetBy = Automatic

        



    partition 'People' = m
        mode: import
        source = 
            let
				Source = / * Connect to data source based on context * /,
				#"Renamed Columns" = Table.RenameColumns(Source,
				{{"OldRowId",
				"_row_id"},
				{"OldRegionalManager",
				"Regional_Manager"},
				{"OldRegion",
				"Region"},
				{"OldArea",
				"Area"},
				{"OldCountry",
				"Country"}}),
				#"Changed Types" = Table.TransformColumnTypes(#"Renamed Columns",
				{{"_row_id",
				Int64.Type},
				{"Regional_Manager",
				type text},
				{"Region",
				type text},
				{"Area",
				type text},
				{"Country",
				type text}})
			in
				#"Changed Types"
        



    annotation PBI_ResultType = Table