table 'People'


    column '_row_id'
        dataType: int64
        summarizeBy: none
        sourceColumn: _row_id

        annotation SummarizationSetBy = Automatic

        
    column 'Regional_Manager'
        dataType: string
        summarizeBy: none
        sourceColumn: Regional_Manager

        annotation SummarizationSetBy = Automatic

        
    column 'Region'
        dataType: string
        summarizeBy: none
        sourceColumn: Region

        annotation SummarizationSetBy = Automatic

        
    column 'Area'
        dataType: string
        summarizeBy: none
        sourceColumn: Area

        annotation SummarizationSetBy = Automatic

        
    column 'Country'
        dataType: string
        summarizeBy: none
        sourceColumn: Country

        annotation SummarizationSetBy = Automatic

        



    partition 'People' = m
        mode: import
        source = 
            let
				Source = / * Connect to data source based on context * /,
				#"Renamed Columns" = Table.RenameColumns(Source,
				{{"Orig
			in
				alRowID", "_row_id"}, {"Orig
        



    annotation PBI_ResultType = Table