table 'Returns'


    column 'Row Id'
        dataType: int64
        summarizeBy: none
        sourceColumn: Row Id

        annotation SummarizationSetBy = Automatic

        
    column 'Returned'
        dataType: string
        summarizeBy: none
        sourceColumn: Returned

        annotation SummarizationSetBy = Automatic

        
    column 'Order ID'
        dataType: string
        summarizeBy: none
        sourceColumn: Order ID

        annotation SummarizationSetBy = Automatic

        



    partition 'Returns' = m
        mode: import
        source = 
            let
				Source = / * Connect to data source based on context * /,
				#"Renamed Columns" = Table.RenameColumns(Source,
				{{"OldRowId",
				"Row Id"},
				{"OldReturned",
				"Returned"},
				{"OldOrderID",
				"Order ID"}}),
				#"Changed Types" = Table.TransformColumnTypes(#"Renamed Columns",
				{{"Row Id",
				Int64.Type},
				{"Returned",
				type text},
				{"Order ID",
				type text}})
			in
				#"Changed Types"
        



    annotation PBI_ResultType = Table