table Report_with_Calculations


    column 'ID'
        dataType: int64
        summarizeBy: none
        sourceColumn: ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Name

        

        annotation SummarizationSetBy = Automatic

        
    column 'Value'
        dataType: int64
        summarizeBy: none
        sourceColumn: Value

        

        annotation SummarizationSetBy = Automatic

        



    partition 'Report_with_Calculations' = m
        mode: import
        source = 
            	let
					Source = Excel.Workbook(File.Contents("C:\\Users\\PowerBIUser\\Documents\\sample_data.xlsx"), null, true),
					Sheet1_Sheet = Source{{[Item = "Sheet1",Kind = "Sheet"]}}[Data],
					#"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars = true]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(#"Promoted Headers"),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"ID", Int64.Type}, {"Name", type text}, {"Value", Int64.Type}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table