table ITEM_SITE_EXTRACT


    column 'SITE_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: DESCRIPTION

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_MEASURE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: UNIT_OF_MEASURE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_CREATED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_CREATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'TAX_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: TAX_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TYPE_CODE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: TYPE_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'FUNCTIONAL_GROUP'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: FUNCTIONAL_GROUP

        

        annotation SummarizationSetBy = Automatic

        
    column 'MATERIAL_CLASS'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: MATERIAL_CLASS

        

        annotation SummarizationSetBy = Automatic

        
    column 'STATUS'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_RANK'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SITE_RANK

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_INVENTORIED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_LAST_INVENTORIED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ON_ORDER'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_ON_ORDER

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ON_HAND'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_ON_HAND

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_AVAILABLE'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_AVAILABLE

        

        annotation SummarizationSetBy = Automatic

        
    column 'MINIMUM'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: MINIMUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'MAXIMUM'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: MAXIMUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'EOQ_QTY'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: EOQ_QTY

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CODE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: QA_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_LEVEL'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: QA_LEVEL

        

        annotation SummarizationSetBy = Automatic

        
    column 'CYCLE_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: CYCLE_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'SHELF_LIFE_DATE'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: SHELF_LIFE_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_RECEIVED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_LAST_RECEIVED

        

        annotation SummarizationSetBy = Automatic

        
    column 'FERC_CODE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: FERC_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PRIMARY_LOC'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PRIMARY_LOC

        

        annotation SummarizationSetBy = Automatic

        
    column 'SECONDARY_LOC'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SECONDARY_LOC

        

        annotation SummarizationSetBy = Automatic

        
    column 'EXTRA_LOCS'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: EXTRA_LOCS

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_APPROVED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_LAST_APPROVED

        

        annotation SummarizationSetBy = Automatic

        
    column 'APPROVER_ID'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: APPROVER_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'APPROVER_BADGE_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: APPROVER_BADGE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'APPROVAL_SWITCH'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: APPROVAL_SWITCH

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT1'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: QA_CERT1

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT2'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: QA_CERT2

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT3'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: QA_CERT3

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT4'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: QA_CERT4

        

        annotation SummarizationSetBy = Automatic

        
    column 'VALUE_ON_HAND'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: VALUE_ON_HAND

        

        annotation SummarizationSetBy = Automatic

        
    column 'PREVIOUS_ITEM_ID'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PREVIOUS_ITEM_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ALLOCATED'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_ALLOCATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'CONSUMABLE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: CONSUMABLE

        

        annotation SummarizationSetBy = Automatic

        
    column 'SHELF_LIFE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SHELF_LIFE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PREVENT_MAINTENANCE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PREVENT_MAINTENANCE

        

        annotation SummarizationSetBy = Automatic

        
    column 'CORPORATE_SWITCH'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: CORPORATE_SWITCH

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_OWNER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ITEM_OWNER

        

        annotation SummarizationSetBy = Automatic

        
    column 'SAFETY_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SAFETY_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'UTC_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: UTC_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_DEPT'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ITEM_DEPT

        

        annotation SummarizationSetBy = Automatic

        
    column 'IN_PROCESS_HOLD'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: IN_PROCESS_HOLD

        

        annotation SummarizationSetBy = Automatic

        
    column 'PIT'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PIT

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_EXCESS'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_EXCESS

        

        annotation SummarizationSetBy = Automatic

        
    column 'NEW_RANK'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: NEW_RANK

        

        annotation SummarizationSetBy = Automatic

        
    column 'SUB_STATUS'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SUB_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'STRATIFIED_TRANS_COUNT'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: STRATIFIED_TRANS_COUNT

        

        annotation SummarizationSetBy = Automatic

        
    column 'STRATIFIED_DATE'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: STRATIFIED_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TOLERANCE_AMOUNT'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: TOLERANCE_AMOUNT

        

        annotation SummarizationSetBy = Automatic

        
    column 'TOLERANCE_PERCENTAGE'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: TOLERANCE_PERCENTAGE

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_LAST_UPDATED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: SITE_LAST_UPDATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ON_HOLD'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_ON_HOLD

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_LAST_UPDATED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: ITEM_LAST_UPDATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_PROPERTY_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: UNIT_OF_PROPERTY_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_PROPERTY_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: UNIT_OF_PROPERTY_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_ISSUED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_LAST_ISSUED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_RETURNED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_LAST_RETURNED

        

        annotation SummarizationSetBy = Automatic

        
    column 'CRITICAL_ITEM'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: CRITICAL_ITEM

        

        annotation SummarizationSetBy = Automatic

        
    column 'REVIEW_DATE'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: REVIEW_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'SAP_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SAP_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: DESCRIPTION

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_MEASURE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: UNIT_OF_MEASURE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_CREATED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_CREATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'TAX_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: TAX_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TYPE_CODE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: TYPE_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'FUNCTIONAL_GROUP'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: FUNCTIONAL_GROUP

        

        annotation SummarizationSetBy = Automatic

        
    column 'MATERIAL_CLASS'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: MATERIAL_CLASS

        

        annotation SummarizationSetBy = Automatic

        
    column 'STATUS'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_RANK'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SITE_RANK

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_INVENTORIED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_LAST_INVENTORIED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ON_ORDER'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_ON_ORDER

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ON_HAND'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_ON_HAND

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_AVAILABLE'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_AVAILABLE

        

        annotation SummarizationSetBy = Automatic

        
    column 'MINIMUM'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: MINIMUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'MAXIMUM'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: MAXIMUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'EOQ_QTY'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: EOQ_QTY

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CODE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: QA_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_LEVEL'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: QA_LEVEL

        

        annotation SummarizationSetBy = Automatic

        
    column 'CYCLE_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: CYCLE_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'SHELF_LIFE_DATE'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: SHELF_LIFE_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_RECEIVED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_LAST_RECEIVED

        

        annotation SummarizationSetBy = Automatic

        
    column 'FERC_CODE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: FERC_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PRIMARY_LOC'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PRIMARY_LOC

        

        annotation SummarizationSetBy = Automatic

        
    column 'SECONDARY_LOC'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SECONDARY_LOC

        

        annotation SummarizationSetBy = Automatic

        
    column 'EXTRA_LOCS'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: EXTRA_LOCS

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_APPROVED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_LAST_APPROVED

        

        annotation SummarizationSetBy = Automatic

        
    column 'APPROVER_ID'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: APPROVER_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'APPROVER_BADGE_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: APPROVER_BADGE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'APPROVAL_SWITCH'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: APPROVAL_SWITCH

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT1'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: QA_CERT1

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT2'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: QA_CERT2

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT3'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: QA_CERT3

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT4'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: QA_CERT4

        

        annotation SummarizationSetBy = Automatic

        
    column 'VALUE_ON_HAND'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: VALUE_ON_HAND

        

        annotation SummarizationSetBy = Automatic

        
    column 'PREVIOUS_ITEM_ID'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PREVIOUS_ITEM_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ALLOCATED'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_ALLOCATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'CONSUMABLE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: CONSUMABLE

        

        annotation SummarizationSetBy = Automatic

        
    column 'SHELF_LIFE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SHELF_LIFE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PREVENT_MAINTENANCE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PREVENT_MAINTENANCE

        

        annotation SummarizationSetBy = Automatic

        
    column 'CORPORATE_SWITCH'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: CORPORATE_SWITCH

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_OWNER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ITEM_OWNER

        

        annotation SummarizationSetBy = Automatic

        
    column 'SAFETY_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SAFETY_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'UTC_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: UTC_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_DEPT'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ITEM_DEPT

        

        annotation SummarizationSetBy = Automatic

        
    column 'IN_PROCESS_HOLD'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: IN_PROCESS_HOLD

        

        annotation SummarizationSetBy = Automatic

        
    column 'PIT'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PIT

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_EXCESS'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_EXCESS

        

        annotation SummarizationSetBy = Automatic

        
    column 'NEW_RANK'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: NEW_RANK

        

        annotation SummarizationSetBy = Automatic

        
    column 'SUB_STATUS'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SUB_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'STRATIFIED_TRANS_COUNT'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: STRATIFIED_TRANS_COUNT

        

        annotation SummarizationSetBy = Automatic

        
    column 'STRATIFIED_DATE'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: STRATIFIED_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TOLERANCE_AMOUNT'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: TOLERANCE_AMOUNT

        

        annotation SummarizationSetBy = Automatic

        
    column 'TOLERANCE_PERCENTAGE'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: TOLERANCE_PERCENTAGE

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_LAST_UPDATED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: SITE_LAST_UPDATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ON_HOLD'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_ON_HOLD

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_LAST_UPDATED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: ITEM_LAST_UPDATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_PROPERTY_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: UNIT_OF_PROPERTY_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_PROPERTY_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: UNIT_OF_PROPERTY_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_ISSUED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_LAST_ISSUED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_RETURNED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_LAST_RETURNED

        

        annotation SummarizationSetBy = Automatic

        
    column 'CRITICAL_ITEM'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: CRITICAL_ITEM

        

        annotation SummarizationSetBy = Automatic

        
    column 'REVIEW_DATE'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: REVIEW_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'SAP_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SAP_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER_SITE_NUMBER_Key'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER_SITE_NUMBER_Key

        isHidden
        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_NUMBER_ITEM_NUMBER_Key'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER_ITEM_NUMBER_Key

        isHidden
        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_NUMBER_ITEM_NUMBER_Key'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER_ITEM_NUMBER_Key

        isHidden
        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER_Key'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER_Key

        isHidden
        

        annotation SummarizationSetBy = Automatic

        



    partition 'ITEM_SITE_EXTRACT' = m
        mode: import
        source = 
            Select
    // Add composite key: ITEM_NUMBER_SITE_NUMBER_Key
    AddCompositeKey_1 = Table.AddColumn(Source, "ITEM_NUMBER_SITE_NUMBER_Key", each Text.Combine({[ITEM_NUMBER], [SITE_NUMBER]}, "|"), type text),
    // Add composite key: SITE_NUMBER_ITEM_NUMBER_Key
    AddCompositeKey_2 = Table.AddColumn(AddCompositeKey_1, "SITE_NUMBER_ITEM_NUMBER_Key", each Text.Combine({[SITE_NUMBER], [ITEM_NUMBER]}, "|"), type text),
    // Add composite key: SITE_NUMBER_ITEM_NUMBER_Key
    AddCompositeKey_3 = Table.AddColumn(AddCompositeKey_2, "SITE_NUMBER_ITEM_NUMBER_Key", each Text.Combine({[SITE_NUMBER], [ITEM_NUMBER]}, "|"), type text),
    // Add composite key: ITEM_NUMBER_Key
    AddCompositeKey_4 = Table.AddColumn(AddCompositeKey_3, "ITEM_NUMBER_Key", each [ITEM_NUMBER], type text)
in
    AddCompositeKey_4
        



    annotation PBI_ResultType = Table