table MANUFACTURER


    column 'ITEM_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'MFG_PART_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: MFG_PART_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'MODEL_PART_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: MODEL_PART_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'ACTIVITY_CODE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ACTIVITY_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'MFG_CODE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: MFG_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_CREATED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_CREATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'MFG_NAME'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: MFG_NAME

        

        annotation SummarizationSetBy = Automatic

        
    column 'COMPRESSED_PART_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: COMPRESSED_PART_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'FOSSIL_OR_NUCLEAR'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: FOSSIL_OR_NUCLEAR

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'MFG_PART_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: MFG_PART_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'MODEL_PART_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: MODEL_PART_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'ACTIVITY_CODE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ACTIVITY_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'MFG_CODE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: MFG_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_CREATED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_CREATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'MFG_NAME'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: MFG_NAME

        

        annotation SummarizationSetBy = Automatic

        
    column 'COMPRESSED_PART_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: COMPRESSED_PART_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'FOSSIL_OR_NUCLEAR'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: FOSSIL_OR_NUCLEAR

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER_Key'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER_Key

        isHidden
        

        annotation SummarizationSetBy = Automatic

        



    partition 'MANUFACTURER' = m
        mode: import
        source = 
            Select
    // Add composite key: ITEM_NUMBER_Key
    AddCompositeKey_1 = Table.AddColumn(Source, "ITEM_NUMBER_Key", each [ITEM_NUMBER], type text)
in
    AddCompositeKey_1
        



    annotation PBI_ResultType = Table