table MATERIAL_CHARGES


    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'CHARGED_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: CHARGED_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TIME_ENTERED'
        dataType: string
        summarizeBy: none
        sourceColumn: TIME_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOREKEEPER_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: STOREKEEPER_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'EMPLOYEE_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: EMPLOYEE_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'ISSUE_TICKET_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ISSUE_TICKET_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'TRANSACTION_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: TRANSACTION_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ADJUSTMENT_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: ADJUSTMENT_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QUANTITY'
        dataType: int64
        summarizeBy: none
        sourceColumn: QUANTITY

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: int64
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TRANSACTION_VALUE'
        dataType: int64
        summarizeBy: none
        sourceColumn: TRANSACTION_VALUE

        

        annotation SummarizationSetBy = Automatic

        
    column 'JOB_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: JOB_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'BU_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: BU_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_INDICATOR'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_INDICATOR

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ENTERED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_STATUS_EFFECTIVE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_STATUS_EFFECTIVE

        

        annotation SummarizationSetBy = Automatic

        
    column 'REFURB_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: REFURB_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'ISSUE_OVERRIDE_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: ISSUE_OVERRIDE_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'RECORD_STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: RECORD_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_MEASURE'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_OF_MEASURE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ADJUSTMENT_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ADJUSTMENT_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ADJUSTMENT_DESC'
        dataType: string
        summarizeBy: none
        sourceColumn: ADJUSTMENT_DESC

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_TO_RECONCILE'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_TO_RECONCILE

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'TRANSFER_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: TRANSFER_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'MATERIAL_CLASS'
        dataType: string
        summarizeBy: none
        sourceColumn: MATERIAL_CLASS

        

        annotation SummarizationSetBy = Automatic

        
    column 'ROOT_DESCRIPTION'
        dataType: string
        summarizeBy: none
        sourceColumn: ROOT_DESCRIPTION

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITT_KEY_NO'
        dataType: string
        summarizeBy: none
        sourceColumn: ITT_KEY_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'UTC_NO'
        dataType: string
        summarizeBy: none
        sourceColumn: UTC_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'PIT_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: PIT_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'UM'
        dataType: string
        summarizeBy: none
        sourceColumn: UM

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_NUMBER_ITEM_NUMBER_Key'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER_ITEM_NUMBER_Key

        isHidden
        

        annotation SummarizationSetBy = Automatic

        



    partition 'MATERIAL_CHARGES' = m
        mode: import
        source = 
            let
                    Source = Sql.Database(#"DB Server", #"DB Name"),
                    ExecuteQuery = Value.NativeQuery(Source, "SELECT ""SITE_NUMBER"", ""ITEM_NUMBER"", ""CHARGED_DATE"", ""TIME_ENTERED"", ""STOREKEEPER_ID"", ""EMPLOYEE_ID"", ""ISSUE_TICKET_NUMBER"", ""TRANSACTION_TYPE"", ""ADJUSTMENT_TYPE"", ""QUANTITY"", ""UNIT_PRICE"", ""TRANSACTION_VALUE"", ""JOB_NUMBER"", ""BU_NUMBER"", ""PO_NUMBER"", ""PO_INDICATOR"", ""DATE_ENTERED"", ""DATE_STATUS_EFFECTIVE"", ""REFURB_IND"", ""ISSUE_OVERRIDE_IND"", ""RECORD_STATUS"", ""UNIT_OF_MEASURE"", ""ADJUSTMENT_NUMBER"", ""ADJUSTMENT_DESC"", ""QTY_TO_RECONCILE"", ""STOP"", ""TRANSFER_NUMBER"", ""MATERIAL_CLASS"", ""ROOT_DESCRIPTION"", ""ITT_KEY_NO"", ""UTC_NO"", ""PIT_IND"", ""UM"" FROM ""MATERIAL_CHARGES""", null, [EnableFolding=true]),
                    #"Removed Errors" = Table.RemoveRowsWithErrors(ExecuteQuery)
                    // Add composite key: SITE_NUMBER_ITEM_NUMBER_Key
                    AddCompositeKey_1 = Table.AddColumn(#"Removed Errors", "SITE_NUMBER_ITEM_NUMBER_Key", each Text.Combine({[SITE_NUMBER], [ITEM_NUMBER]}, "|"), type text),
                    // Add composite key: SITE_NUMBER_ITEM_NUMBER_Key
                    AddCompositeKey_2 = Table.AddColumn(AddCompositeKey_1, "SITE_NUMBER_ITEM_NUMBER_Key", each Text.Combine({[SITE_NUMBER], [ITEM_NUMBER]}, "|"), type text)
                in
                    AddCompositeKey_2
        



    annotation PBI_ResultType = Table