table MATERIAL_CHARGES


    column 'SITE_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'CHARGED_DATE'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: CHARGED_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TIME_ENTERED'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: TIME_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOREKEEPER_ID'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: STOREKEEPER_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'EMPLOYEE_ID'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: EMPLOYEE_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'ISSUE_TICKET_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ISSUE_TICKET_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'TRANSACTION_TYPE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: TRANSACTION_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ADJUSTMENT_TYPE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ADJUSTMENT_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QUANTITY'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QUANTITY

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TRANSACTION_VALUE'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: TRANSACTION_VALUE

        

        annotation SummarizationSetBy = Automatic

        
    column 'JOB_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: JOB_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'BU_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: BU_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PO_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_INDICATOR'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PO_INDICATOR

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ENTERED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_STATUS_EFFECTIVE'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_STATUS_EFFECTIVE

        

        annotation SummarizationSetBy = Automatic

        
    column 'REFURB_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: REFURB_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'ISSUE_OVERRIDE_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ISSUE_OVERRIDE_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'RECORD_STATUS'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: RECORD_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_MEASURE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: UNIT_OF_MEASURE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ADJUSTMENT_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ADJUSTMENT_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ADJUSTMENT_DESC'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ADJUSTMENT_DESC

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_TO_RECONCILE'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_TO_RECONCILE

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'TRANSFER_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: TRANSFER_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'MATERIAL_CLASS'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: MATERIAL_CLASS

        

        annotation SummarizationSetBy = Automatic

        
    column 'ROOT_DESCRIPTION'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ROOT_DESCRIPTION

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITT_KEY_NO'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ITT_KEY_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'UTC_NO'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: UTC_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'PIT_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PIT_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'UM'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: UM

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'CHARGED_DATE'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: CHARGED_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TIME_ENTERED'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: TIME_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOREKEEPER_ID'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: STOREKEEPER_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'EMPLOYEE_ID'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: EMPLOYEE_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'ISSUE_TICKET_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ISSUE_TICKET_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'TRANSACTION_TYPE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: TRANSACTION_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ADJUSTMENT_TYPE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ADJUSTMENT_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QUANTITY'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QUANTITY

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TRANSACTION_VALUE'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: TRANSACTION_VALUE

        

        annotation SummarizationSetBy = Automatic

        
    column 'JOB_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: JOB_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'BU_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: BU_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PO_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_INDICATOR'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PO_INDICATOR

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ENTERED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_STATUS_EFFECTIVE'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_STATUS_EFFECTIVE

        

        annotation SummarizationSetBy = Automatic

        
    column 'REFURB_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: REFURB_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'ISSUE_OVERRIDE_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ISSUE_OVERRIDE_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'RECORD_STATUS'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: RECORD_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_MEASURE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: UNIT_OF_MEASURE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ADJUSTMENT_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ADJUSTMENT_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ADJUSTMENT_DESC'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ADJUSTMENT_DESC

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_TO_RECONCILE'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_TO_RECONCILE

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'TRANSFER_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: TRANSFER_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'MATERIAL_CLASS'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: MATERIAL_CLASS

        

        annotation SummarizationSetBy = Automatic

        
    column 'ROOT_DESCRIPTION'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ROOT_DESCRIPTION

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITT_KEY_NO'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ITT_KEY_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'UTC_NO'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: UTC_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'PIT_IND'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PIT_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'UM'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: UM

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_NUMBER_ITEM_NUMBER_Key'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER_ITEM_NUMBER_Key

        isHidden
        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_NUMBER_ITEM_NUMBER_Key'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER_ITEM_NUMBER_Key

        isHidden
        

        annotation SummarizationSetBy = Automatic

        



    partition 'MATERIAL_CHARGES' = m
        mode: import
        source = 
            Select
    // Add composite key: SITE_NUMBER_ITEM_NUMBER_Key
    AddCompositeKey_1 = Table.AddColumn(Source, "SITE_NUMBER_ITEM_NUMBER_Key", each Text.Combine({[SITE_NUMBER], [ITEM_NUMBER]}, "|"), type text),
    // Add composite key: SITE_NUMBER_ITEM_NUMBER_Key
    AddCompositeKey_2 = Table.AddColumn(AddCompositeKey_1, "SITE_NUMBER_ITEM_NUMBER_Key", each Text.Combine({[SITE_NUMBER], [ITEM_NUMBER]}, "|"), type text)
in
    AddCompositeKey_2
        



    annotation PBI_ResultType = Table