table PURCHASE_ORDER_RECEIPT


    column 'SITE_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PO_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'CHANGE_ORDER_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: CHANGE_ORDER_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'RELEASE_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: RELEASE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_LINE_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PO_LINE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ENTERED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'TIME_ENTERED'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: TIME_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_RECEIVED'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_RECEIVED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_REJECTED'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_REJECTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CODE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: QA_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'SHELF_LIFE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SHELF_LIFE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_INSPECTOR'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: QA_INSPECTOR

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOREKEEPER_ID'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: STOREKEEPER_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'RECEIPT_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: RECEIPT_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_RECEIVED_AT_SITE'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_RECEIVED_AT_SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'RECEIPT_CODE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: RECEIPT_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_STATUS_EFFECTIVE'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_STATUS_EFFECTIVE

        

        annotation SummarizationSetBy = Automatic

        
    column 'HOLD_STATUS'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: HOLD_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'DSR_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: DSR_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_IN_HOLD'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_IN_HOLD

        

        annotation SummarizationSetBy = Automatic

        
    column 'RECORD_STATUS'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: RECORD_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITT_KEY_NO'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ITT_KEY_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PO_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'CHANGE_ORDER_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: CHANGE_ORDER_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'RELEASE_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: RELEASE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_LINE_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: PO_LINE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ENTERED'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'TIME_ENTERED'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: TIME_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_RECEIVED'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_RECEIVED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_REJECTED'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_REJECTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CODE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: QA_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'SHELF_LIFE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: SHELF_LIFE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_INSPECTOR'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: QA_INSPECTOR

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOREKEEPER_ID'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: STOREKEEPER_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'RECEIPT_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: RECEIPT_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_RECEIVED_AT_SITE'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_RECEIVED_AT_SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'RECEIPT_CODE'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: RECEIPT_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_STATUS_EFFECTIVE'
        dataType: DataType.DATE
        summarizeBy: none
        sourceColumn: DATE_STATUS_EFFECTIVE

        

        annotation SummarizationSetBy = Automatic

        
    column 'HOLD_STATUS'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: HOLD_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'DSR_NUMBER'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: DSR_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_IN_HOLD'
        dataType: DataType.INTEGER
        summarizeBy: none
        sourceColumn: QTY_IN_HOLD

        

        annotation SummarizationSetBy = Automatic

        
    column 'RECORD_STATUS'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: RECORD_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITT_KEY_NO'
        dataType: DataType.STRING
        summarizeBy: none
        sourceColumn: ITT_KEY_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NUMBER_RELEASE_NUMBER_PO_LINE_NUMBER_SITE_NUMBER_Key'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_NUMBER_RELEASE_NUMBER_PO_LINE_NUMBER_SITE_NUMBER_Key

        isHidden
        

        annotation SummarizationSetBy = Automatic

        



    partition 'PURCHASE_ORDER_RECEIPT' = m
        mode: import
        source = 
            let
                    Source = Sql.Database(#"DB Server", #"DB Name"),
                    ExecuteQuery = Value.NativeQuery(Source, "SELECT ""SITE_NUMBER"", ""PO_NUMBER"", ""CHANGE_ORDER_NUMBER"", ""RELEASE_NUMBER"", ""PO_LINE_NUMBER"", ""DATE_ENTERED"", ""TIME_ENTERED"", ""QTY_RECEIVED"", ""QTY_REJECTED"", ""QA_CODE"", ""SHELF_LIFE"", ""QA_INSPECTOR"", ""STOREKEEPER_ID"", ""RECEIPT_NUMBER"", ""UNIT_PRICE"", ""ITEM_NUMBER"", ""DATE_RECEIVED_AT_SITE"", ""RECEIPT_CODE"", ""DATE_STATUS_EFFECTIVE"", ""HOLD_STATUS"", ""DSR_NUMBER"", ""QTY_IN_HOLD"", ""RECORD_STATUS"", ""STOP"", ""ITT_KEY_NO"" FROM ""PURCHASE_ORDER_RECEIPT""", null, [EnableFolding=true]),
                    #"Removed Errors" = Table.RemoveRowsWithErrors(ExecuteQuery)
    // Add composite key: PO_NUMBER_RELEASE_NUMBER_PO_LINE_NUMBER_SITE_NUMBER_Key
    AddCompositeKey_1 = Table.AddColumn(#"Removed Errors", "PO_NUMBER_RELEASE_NUMBER_PO_LINE_NUMBER_SITE_NUMBER_Key", each Text.Combine({[PO_NUMBER], [RELEASE_NUMBER], [PO_LINE_NUMBER], [SITE_NUMBER]}, "|"), type text)
in
    AddCompositeKey_1
        



    annotation PBI_ResultType = Table