table 'Agency'


    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyUserID'
        dataType: string
        summarizeBy: none
        sourceColumn: AgencyUserID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyName'
        dataType: string
        summarizeBy: none
        sourceColumn: AgencyName

        annotation SummarizationSetBy = Automatic

        
    column 'Address1'
        dataType: string
        summarizeBy: none
        sourceColumn: Address1

        annotation SummarizationSetBy = Automatic

        
    column 'Address2'
        dataType: string
        summarizeBy: none
        sourceColumn: Address2

        annotation SummarizationSetBy = Automatic

        
    column 'City'
        dataType: string
        summarizeBy: none
        sourceColumn: City

        annotation SummarizationSetBy = Automatic

        
    column 'State'
        dataType: string
        summarizeBy: none
        sourceColumn: State

        annotation SummarizationSetBy = Automatic

        
    column 'Zip'
        dataType: string
        summarizeBy: none
        sourceColumn: Zip

        annotation SummarizationSetBy = Automatic

        
    column 'Phone'
        dataType: string
        summarizeBy: none
        sourceColumn: Phone

        annotation SummarizationSetBy = Automatic

        
    column 'Fax'
        dataType: string
        summarizeBy: none
        sourceColumn: Fax

        annotation SummarizationSetBy = Automatic

        
    column 'ContactName'
        dataType: string
        summarizeBy: none
        sourceColumn: ContactName

        annotation SummarizationSetBy = Automatic

        
    column 'Email'
        dataType: string
        summarizeBy: none
        sourceColumn: Email

        annotation SummarizationSetBy = Automatic

        
    column 'DistributionAgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: DistributionAgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'DivisionID'
        dataType: int64
        summarizeBy: none
        sourceColumn: DivisionID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyType'
        dataType: string
        summarizeBy: none
        sourceColumn: AgencyType

        annotation SummarizationSetBy = Automatic

        
    column 'IsActive'
        dataType: string
        summarizeBy: none
        sourceColumn: IsActive

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: string
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: string
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyUserID'
        dataType: string
        summarizeBy: none
        sourceColumn: AgencyUserID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyName'
        dataType: string
        summarizeBy: none
        sourceColumn: AgencyName

        annotation SummarizationSetBy = Automatic

        
    column 'Address1'
        dataType: string
        summarizeBy: none
        sourceColumn: Address1

        annotation SummarizationSetBy = Automatic

        
    column 'Address2'
        dataType: string
        summarizeBy: none
        sourceColumn: Address2

        annotation SummarizationSetBy = Automatic

        
    column 'City'
        dataType: string
        summarizeBy: none
        sourceColumn: City

        annotation SummarizationSetBy = Automatic

        
    column 'State'
        dataType: string
        summarizeBy: none
        sourceColumn: State

        annotation SummarizationSetBy = Automatic

        
    column 'Zip'
        dataType: string
        summarizeBy: none
        sourceColumn: Zip

        annotation SummarizationSetBy = Automatic

        
    column 'Phone'
        dataType: string
        summarizeBy: none
        sourceColumn: Phone

        annotation SummarizationSetBy = Automatic

        
    column 'Fax'
        dataType: string
        summarizeBy: none
        sourceColumn: Fax

        annotation SummarizationSetBy = Automatic

        
    column 'ContactName'
        dataType: string
        summarizeBy: none
        sourceColumn: ContactName

        annotation SummarizationSetBy = Automatic

        
    column 'Email'
        dataType: string
        summarizeBy: none
        sourceColumn: Email

        annotation SummarizationSetBy = Automatic

        
    column 'DistributionAgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: DistributionAgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'DivisionID'
        dataType: int64
        summarizeBy: none
        sourceColumn: DivisionID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyType'
        dataType: string
        summarizeBy: none
        sourceColumn: AgencyType

        annotation SummarizationSetBy = Automatic

        
    column 'IsActive'
        dataType: string
        summarizeBy: none
        sourceColumn: IsActive

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: string
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: string
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        



    partition 'Agency' = m
        mode: import
        source = 
            	let
					Source = /* Connect to data source based on context */,
					#"Changed Types" = Table.TransformColumnTypes(Source, {{"AgencyID", Int64.Type}, {"AgencyUserID", type text}, {"AgencyName", type text}, {"Address1", type text}, {"Address2", type text}, {"City", type text}, {"State", type text}, {"Zip", type text}, {"Phone", type text}, {"Fax", type text}, {"ContactName", type text}, {"Email", type text}, {"DistributionAgencyID", Int64.Type}, {"DivisionID", Int64.Type}, {"AgencyType", type text}, {"IsActive", type text}, {"CreatedBy", type text}, {"datecreated", type text}, {"UpdatedBy", type text}, {"LastUpdated", type text}, {"AgencyID", Int64.Type}, {"AgencyUserID", type text}, {"AgencyName", type text}, {"Address1", type text}, {"Address2", type text}, {"City", type text}, {"State", type text}, {"Zip", type text}, {"Phone", type text}, {"Fax", type text}, {"ContactName", type text}, {"Email", type text}, {"DistributionAgencyID", Int64.Type}, {"DivisionID", Int64.Type}, {"AgencyType", type text}, {"IsActive", type text}, {"CreatedBy", type text}, {"datecreated", type text}, {"UpdatedBy", type text}, {"LastUpdated", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table