table 'Assistance'


    column 'AssistanceReportID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AssistanceReportID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableMonth'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableMonth

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        annotation SummarizationSetBy = Automatic

        
    column 'HouseholdsAssisted'
        dataType: int64
        summarizeBy: none
        sourceColumn: HouseholdsAssisted

        annotation SummarizationSetBy = Automatic

        
    column 'Denials'
        dataType: int64
        summarizeBy: none
        sourceColumn: Denials

        annotation SummarizationSetBy = Automatic

        
    column 'PreparedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: PreparedBy

        annotation SummarizationSetBy = Automatic

        
    column 'PreparedDate'
        dataType: string
        summarizeBy: none
        sourceColumn: PreparedDate

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: string
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: string
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        
    column 'AssistanceReportID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AssistanceReportID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableMonth'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableMonth

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        annotation SummarizationSetBy = Automatic

        
    column 'HouseholdsAssisted'
        dataType: int64
        summarizeBy: none
        sourceColumn: HouseholdsAssisted

        annotation SummarizationSetBy = Automatic

        
    column 'Denials'
        dataType: int64
        summarizeBy: none
        sourceColumn: Denials

        annotation SummarizationSetBy = Automatic

        
    column 'PreparedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: PreparedBy

        annotation SummarizationSetBy = Automatic

        
    column 'PreparedDate'
        dataType: string
        summarizeBy: none
        sourceColumn: PreparedDate

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: string
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: string
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        



    partition 'Assistance' = m
        mode: import
        source = 
            	let
					Source = /* Connect to data source based on context */,
					#"Renamed Columns" = Table.RenameColumns(Source, {{"OldAssistanceReportID", "AssistanceReportID"}, {"OldAgencyID", "AgencyID"}, {"OldApplicableMonth", "ApplicableMonth"}, {"OldApplicableYear", "ApplicableYear"}, {"OldHouseholdsAssisted", "HouseholdsAssisted"}, {"OldDenials", "Denials"}, {"OldPreparedBy", "PreparedBy"}, {"OldPreparedDate", "PreparedDate"}, {"OldCreatedBy", "CreatedBy"}, {"Olddatecreated", "datecreated"}, {"OldUpdatedBy", "UpdatedBy"}, {"OldLastUpdated", "LastUpdated"}}),
					#"Changed Types" = Table.TransformColumnTypes(#"Renamed Columns", {{"AssistanceReportID", Int64.Type}, {"AgencyID", Int64.Type}, {"ApplicableMonth", Int64.Type}, {"ApplicableYear", Int64.Type}, {"HouseholdsAssisted", Int64.Type}, {"Denials", Int64.Type}, {"PreparedBy", type text}, {"PreparedDate", type text}, {"CreatedBy", type text}, {"datecreated", type text}, {"UpdatedBy", type text}, {"LastUpdated", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table