table 'tblAgencyTerritory'


    column 'AgencyTerritoryID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyTerritoryID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'TerritoryID'
        dataType: int64
        summarizeBy: none
        sourceColumn: TerritoryID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyTerritoryID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyTerritoryID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'TerritoryID'
        dataType: int64
        summarizeBy: none
        sourceColumn: TerritoryID

        annotation SummarizationSetBy = Automatic

        



    partition 'tblAgencyTerritory' = m
        mode: import
        source = 
            	let
					Source = /* Connect to data source based on context */,
					#"Changed Types" = Table.TransformColumnTypes(Source, {{"AgencyTerritoryID", Int64.Type}, {"AgencyID", Int64.Type}, {"TerritoryID", Int64.Type}, {"AgencyTerritoryID", Int64.Type}, {"AgencyID", Int64.Type}, {"TerritoryID", Int64.Type}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table