table 'tblFinancialReport'


    column 'FinancialReportID'
        dataType: int64
        summarizeBy: none
        sourceColumn: FinancialReportID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableMonth'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableMonth

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        annotation SummarizationSetBy = Automatic

        
    column 'BalanceForward'
        dataType: string
        summarizeBy: none
        sourceColumn: BalanceForward

        annotation SummarizationSetBy = Automatic

        
    column 'EnergyShareCheckAmount'
        dataType: string
        summarizeBy: none
        sourceColumn: EnergyShareCheckAmount

        annotation SummarizationSetBy = Automatic

        
    column 'EnergySharePartnerAmount'
        dataType: string
        summarizeBy: none
        sourceColumn: EnergySharePartnerAmount

        annotation SummarizationSetBy = Automatic

        
    column 'AmountSpentPayingEnergyBills'
        dataType: string
        summarizeBy: none
        sourceColumn: AmountSpentPayingEnergyBills

        annotation SummarizationSetBy = Automatic

        
    column 'BalanceOnHand'
        dataType: string
        summarizeBy: none
        sourceColumn: BalanceOnHand

        annotation SummarizationSetBy = Automatic

        
    column 'PreparedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: PreparedBy

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: string
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: string
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        
    column 'FinancialReportID'
        dataType: int64
        summarizeBy: none
        sourceColumn: FinancialReportID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableMonth'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableMonth

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        annotation SummarizationSetBy = Automatic

        
    column 'BalanceForward'
        dataType: string
        summarizeBy: none
        sourceColumn: BalanceForward

        annotation SummarizationSetBy = Automatic

        
    column 'EnergyShareCheckAmount'
        dataType: string
        summarizeBy: none
        sourceColumn: EnergyShareCheckAmount

        annotation SummarizationSetBy = Automatic

        
    column 'EnergySharePartnerAmount'
        dataType: string
        summarizeBy: none
        sourceColumn: EnergySharePartnerAmount

        annotation SummarizationSetBy = Automatic

        
    column 'AmountSpentPayingEnergyBills'
        dataType: string
        summarizeBy: none
        sourceColumn: AmountSpentPayingEnergyBills

        annotation SummarizationSetBy = Automatic

        
    column 'BalanceOnHand'
        dataType: string
        summarizeBy: none
        sourceColumn: BalanceOnHand

        annotation SummarizationSetBy = Automatic

        
    column 'PreparedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: PreparedBy

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: string
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: string
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        



    partition 'tblFinancialReport' = m
        mode: import
        source = 
            	let
					Source = /* Connect to data source based on context */,
					#"Changed Types" = Table.TransformColumnTypes(Source, {{"FinancialReportID", Int64.Type}, {"AgencyID", Int64.Type}, {"ApplicableMonth", Int64.Type}, {"ApplicableYear", Int64.Type}, {"BalanceForward", type text}, {"EnergyShareCheckAmount", type text}, {"EnergySharePartnerAmount", type text}, {"AmountSpentPayingEnergyBills", type text}, {"BalanceOnHand", type text}, {"PreparedBy", type text}, {"CreatedBy", type text}, {"datecreated", type text}, {"UpdatedBy", type text}, {"LastUpdated", type text}, {"FinancialReportID", Int64.Type}, {"AgencyID", Int64.Type}, {"ApplicableMonth", Int64.Type}, {"ApplicableYear", Int64.Type}, {"BalanceForward", type text}, {"EnergyShareCheckAmount", type text}, {"EnergySharePartnerAmount", type text}, {"AmountSpentPayingEnergyBills", type text}, {"BalanceOnHand", type text}, {"PreparedBy", type text}, {"CreatedBy", type text}, {"datecreated", type text}, {"UpdatedBy", type text}, {"LastUpdated", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table