table 'tblTerritory'


    column 'TerritoryID'
        dataType: int64
        summarizeBy: none
        sourceColumn: TerritoryID

        annotation SummarizationSetBy = Automatic

        
    column 'Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Name

        annotation SummarizationSetBy = Automatic

        
    column 'IsActive'
        dataType: string
        summarizeBy: none
        sourceColumn: IsActive

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: string
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: string
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        
    column 'TerritoryID'
        dataType: int64
        summarizeBy: none
        sourceColumn: TerritoryID

        annotation SummarizationSetBy = Automatic

        
    column 'Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Name

        annotation SummarizationSetBy = Automatic

        
    column 'IsActive'
        dataType: string
        summarizeBy: none
        sourceColumn: IsActive

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: string
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: string
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        



    partition 'tblTerritory' = m
        mode: import
        source = 
            	let
					Source = /* Connect to data source based on context */,
					#"Renamed Columns" = Table.RenameColumns(Source, {{"OldTerritoryID", "TerritoryID"}, {"OldName", "Name"}, {"OldIsActive", "IsActive"}, {"OldCreatedBy", "CreatedBy"}, {"OldDateCreated", "datecreated"}, {"OldUpdatedBy", "UpdatedBy"}, {"OldLastUpdated", "LastUpdated"}}),
					#"Changed Types" = Table.TransformColumnTypes(#"Renamed Columns", {{"TerritoryID", Int64.Type}, {"Name", type text}, {"IsActive", type text}, {"CreatedBy", type text}, {"datecreated", type text}, {"UpdatedBy", type text}, {"LastUpdated", type text}}),
					#"Final Selected Columns" = Table.SelectColumns(#"Changed Types", {"TerritoryID", "Name", "IsActive", "CreatedBy", "datecreated", "UpdatedBy", "LastUpdated"})
				in
					#"Final Selected Columns"
        



    annotation PBI_ResultType = Table