table MaterialReceiptDetail_UC016


    column 'DATE_ENTERED'
        dataType: string
        summarizeBy: none
        sourceColumn: DATE_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_LINE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_LINE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'RELEASE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: RELEASE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_RECEIVED_AT_SITE'
        dataType: string
        summarizeBy: none
        sourceColumn: DATE_RECEIVED_AT_SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_RECEIVED'
        dataType: string
        summarizeBy: none
        sourceColumn: QTY_RECEIVED

        

        annotation SummarizationSetBy = Automatic

        
    column 'TIME_ENTERED'
        dataType: string
        summarizeBy: none
        sourceColumn: TIME_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'JOB_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: JOB_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_MEASURE'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_OF_MEASURE

        

        annotation SummarizationSetBy = Automatic

        
    column 'REQUESTOR_NAME'
        dataType: string
        summarizeBy: none
        sourceColumn: REQUESTOR_NAME

        

        annotation SummarizationSetBy = Automatic

        
    column 'VENDOR_NAME'
        dataType: string
        summarizeBy: none
        sourceColumn: VENDOR_NAME

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION1'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION1

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION2'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION2

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION1'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION1

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC1' = ```
            substring(rpad([LOCATION1], 12, ' '), 1,2) + ' ' +
substring(rpad([LOCATION1], 12, ' '), 3,2) + ' ' +
substring(rpad([LOCATION1], 12, ' '), 5,2) + ' ' +
substring(rpad([LOCATION1], 12, ' '), 7,2) + ' ' +
substring(rpad([LOCATION1], 12, ' '), 9,2) + ' ' +
substring(rpad([LOCATION1], 12, ' '), 11,2)
    ```
        dataType: string
        summarizeBy: none

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC2' = ```
            substring(rpad([LOCATION2], 12, ' '), 1,2) + ' ' +
substring(rpad([LOCATION2], 12, ' '), 3,2) + ' ' +
substring(rpad([LOCATION2], 12, ' '), 5,2) + ' ' +
substring(rpad([LOCATION2], 12, ' '), 7,2) + ' ' +
substring(rpad([LOCATION2], 12, ' '), 9,2) + ' ' +
substring(rpad([LOCATION2], 12, ' '), 11,2)
    ```
        dataType: string
        summarizeBy: none

        

        annotation SummarizationSetBy = Automatic

        
    column 'TotalCost' = ```
            [UNIT_PRICE] * [QTY_RECEIVED]
    ```
        dataType: decimal
        summarizeBy: sum

        

        annotation SummarizationSetBy = User

        



    partition 'MaterialReceiptDetail_UC016' = m
        mode: import
        source = 
            	let
					Source = Excel.Workbook(File.Contents("C:\\Users\\PowerBIUser\\Documents\\sample_data.xlsx"), null, true),
					Sheet1_Sheet = Source{{[Item = "Sheet1",Kind = "Sheet"]}}[Data],
					#"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars = true]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(#"Promoted Headers"),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"DATE_ENTERED", type text}, {"SITE_NUMBER", type text}, {"PO_NUMBER", type text}, {"PO_LINE_NUMBER", type text}, {"RELEASE_NUMBER", type text}, {"DATE_RECEIVED_AT_SITE", type text}, {"QTY_RECEIVED", type text}, {"TIME_ENTERED", type text}, {"ITEM_NUMBER", type text}, {"JOB_NUMBER", type text}, {"UNIT_OF_MEASURE", type text}, {"REQUESTOR_NAME", type text}, {"VENDOR_NAME", type text}, {"LOCATION1", type text}, {"LOCATION2", type text}, {"UNIT_PRICE", type text}, {"DESCRIPTION1", type text}, {"LOC1", type text}, {"LOC2", type text}, {"TotalCost", type number}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table