table ITEM_SITE_EXTRACT


    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_MEASURE'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_OF_MEASURE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_CREATED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_CREATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'TAX_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: TAX_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: int64
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TYPE_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: TYPE_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'FUNCTIONAL_GROUP'
        dataType: string
        summarizeBy: none
        sourceColumn: FUNCTIONAL_GROUP

        

        annotation SummarizationSetBy = Automatic

        
    column 'MATERIAL_CLASS'
        dataType: string
        summarizeBy: none
        sourceColumn: MATERIAL_CLASS

        

        annotation SummarizationSetBy = Automatic

        
    column 'STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_RANK'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_RANK

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_INVENTORIED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_INVENTORIED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ON_ORDER'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_ON_ORDER

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ON_HAND'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_ON_HAND

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_AVAILABLE'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_AVAILABLE

        

        annotation SummarizationSetBy = Automatic

        
    column 'MINIMUM'
        dataType: int64
        summarizeBy: none
        sourceColumn: MINIMUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'MAXIMUM'
        dataType: int64
        summarizeBy: none
        sourceColumn: MAXIMUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'EOQ_QTY'
        dataType: int64
        summarizeBy: none
        sourceColumn: EOQ_QTY

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_LEVEL'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_LEVEL

        

        annotation SummarizationSetBy = Automatic

        
    column 'CYCLE_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: CYCLE_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'SHELF_LIFE_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: SHELF_LIFE_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_RECEIVED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_RECEIVED

        

        annotation SummarizationSetBy = Automatic

        
    column 'FERC_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: FERC_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PRIMARY_LOC'
        dataType: string
        summarizeBy: none
        sourceColumn: PRIMARY_LOC

        

        annotation SummarizationSetBy = Automatic

        
    column 'SECONDARY_LOC'
        dataType: string
        summarizeBy: none
        sourceColumn: SECONDARY_LOC

        

        annotation SummarizationSetBy = Automatic

        
    column 'EXTRA_LOCS'
        dataType: string
        summarizeBy: none
        sourceColumn: EXTRA_LOCS

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_APPROVED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_APPROVED

        

        annotation SummarizationSetBy = Automatic

        
    column 'APPROVER_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: APPROVER_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'APPROVER_BADGE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: APPROVER_BADGE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'APPROVAL_SWITCH'
        dataType: string
        summarizeBy: none
        sourceColumn: APPROVAL_SWITCH

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT1'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_CERT1

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT2'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_CERT2

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT3'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_CERT3

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT4'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_CERT4

        

        annotation SummarizationSetBy = Automatic

        
    column 'VALUE_ON_HAND'
        dataType: int64
        summarizeBy: none
        sourceColumn: VALUE_ON_HAND

        

        annotation SummarizationSetBy = Automatic

        
    column 'PREVIOUS_ITEM_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: PREVIOUS_ITEM_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ALLOCATED'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_ALLOCATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'CONSUMABLE'
        dataType: string
        summarizeBy: none
        sourceColumn: CONSUMABLE

        

        annotation SummarizationSetBy = Automatic

        
    column 'SHELF_LIFE'
        dataType: string
        summarizeBy: none
        sourceColumn: SHELF_LIFE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PREVENT_MAINTENANCE'
        dataType: string
        summarizeBy: none
        sourceColumn: PREVENT_MAINTENANCE

        

        annotation SummarizationSetBy = Automatic

        
    column 'CORPORATE_SWITCH'
        dataType: string
        summarizeBy: none
        sourceColumn: CORPORATE_SWITCH

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_OWNER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_OWNER

        

        annotation SummarizationSetBy = Automatic

        
    column 'SAFETY_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: SAFETY_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'UTC_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: UTC_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_DEPT'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_DEPT

        

        annotation SummarizationSetBy = Automatic

        
    column 'IN_PROCESS_HOLD'
        dataType: int64
        summarizeBy: none
        sourceColumn: IN_PROCESS_HOLD

        

        annotation SummarizationSetBy = Automatic

        
    column 'PIT'
        dataType: string
        summarizeBy: none
        sourceColumn: PIT

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_EXCESS'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_EXCESS

        

        annotation SummarizationSetBy = Automatic

        
    column 'NEW_RANK'
        dataType: string
        summarizeBy: none
        sourceColumn: NEW_RANK

        

        annotation SummarizationSetBy = Automatic

        
    column 'SUB_STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: SUB_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'STRATIFIED_TRANS_COUNT'
        dataType: int64
        summarizeBy: none
        sourceColumn: STRATIFIED_TRANS_COUNT

        

        annotation SummarizationSetBy = Automatic

        
    column 'STRATIFIED_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: STRATIFIED_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TOLERANCE_AMOUNT'
        dataType: int64
        summarizeBy: none
        sourceColumn: TOLERANCE_AMOUNT

        

        annotation SummarizationSetBy = Automatic

        
    column 'TOLERANCE_PERCENTAGE'
        dataType: int64
        summarizeBy: none
        sourceColumn: TOLERANCE_PERCENTAGE

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_LAST_UPDATED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: SITE_LAST_UPDATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ON_HOLD'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_ON_HOLD

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_LAST_UPDATED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: ITEM_LAST_UPDATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_PROPERTY_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_OF_PROPERTY_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_PROPERTY_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_OF_PROPERTY_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_ISSUED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_ISSUED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_RETURNED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_RETURNED

        

        annotation SummarizationSetBy = Automatic

        
    column 'CRITICAL_ITEM'
        dataType: string
        summarizeBy: none
        sourceColumn: CRITICAL_ITEM

        

        annotation SummarizationSetBy = Automatic

        
    column 'REVIEW_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: REVIEW_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'SAP_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: SAP_IND

        

        annotation SummarizationSetBy = Automatic

        

    measure 'ITEM_SITE_EXTRACT - Count by DATE_CREATED' = ```
            CALCULATE(
    COUNTROWS('ITEM_SITE_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITEM_SITE_EXTRACT'[DATE_CREATED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'ITEM_SITE_EXTRACT - Count by DATE_LAST_APPROVED' = ```
            CALCULATE(
    COUNTROWS('ITEM_SITE_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITEM_SITE_EXTRACT'[DATE_LAST_APPROVED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'ITEM_SITE_EXTRACT - Count by DATE_LAST_INVENTORIED' = ```
            CALCULATE(
    COUNTROWS('ITEM_SITE_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITEM_SITE_EXTRACT'[DATE_LAST_INVENTORIED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'ITEM_SITE_EXTRACT - Count by DATE_LAST_ISSUED' = ```
            CALCULATE(
    COUNTROWS('ITEM_SITE_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITEM_SITE_EXTRACT'[DATE_LAST_ISSUED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'ITEM_SITE_EXTRACT - Count by DATE_LAST_RECEIVED' = ```
            CALCULATE(
    COUNTROWS('ITEM_SITE_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITEM_SITE_EXTRACT'[DATE_LAST_RECEIVED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'ITEM_SITE_EXTRACT - Count by DATE_LAST_RETURNED' = ```
            CALCULATE(
    COUNTROWS('ITEM_SITE_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITEM_SITE_EXTRACT'[DATE_LAST_RETURNED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'ITEM_SITE_EXTRACT - Count by ITEM_LAST_UPDATED' = ```
            CALCULATE(
    COUNTROWS('ITEM_SITE_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITEM_SITE_EXTRACT'[ITEM_LAST_UPDATED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'ITEM_SITE_EXTRACT - Count by REVIEW_DATE' = ```
            CALCULATE(
    COUNTROWS('ITEM_SITE_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITEM_SITE_EXTRACT'[REVIEW_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'ITEM_SITE_EXTRACT - Count by SHELF_LIFE_DATE' = ```
            CALCULATE(
    COUNTROWS('ITEM_SITE_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITEM_SITE_EXTRACT'[SHELF_LIFE_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'ITEM_SITE_EXTRACT - Count by SITE_LAST_UPDATED' = ```
            CALCULATE(
    COUNTROWS('ITEM_SITE_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITEM_SITE_EXTRACT'[SITE_LAST_UPDATED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'ITEM_SITE_EXTRACT - Count by STRATIFIED_DATE' = ```
            CALCULATE(
    COUNTROWS('ITEM_SITE_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITEM_SITE_EXTRACT'[STRATIFIED_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'ITEM_SITE_EXTRACT' = m
        mode: import
        source = 
            let
    Source = Sql.Database(#"DB Server", #"DB Name"),
    ExecuteQuery = Value.NativeQuery(Source, "SELECT
    ""SITE_NUMBER"",\n    ""ITEM_NUMBER"",\n    ""DESCRIPTION"",\n    ""UNIT_OF_MEASURE"",\n    ""DATE_CREATED"",\n    ""TAX_IND"",\n    ""UNIT_PRICE"",\n    ""TYPE_CODE"",\n    ""FUNCTIONAL_GROUP"",\n    ""MATERIAL_CLASS"",\n    ""STATUS"",\n    ""SITE_RANK"",\n    ""DATE_LAST_INVENTORIED"",\n    ""QTY_ON_ORDER"",\n    ""QTY_ON_HAND"",\n    ""QTY_AVAILABLE"",\n    ""MINIMUM"",\n    ""MAXIMUM"",\n    ""EOQ_QTY"",\n    ""QA_CODE"",\n    ""QA_LEVEL"",\n    ""CYCLE_IND"",\n    ""SHELF_LIFE_DATE"",\n    ""DATE_LAST_RECEIVED"",\n    ""FERC_CODE"",\n    ""PRIMARY_LOC"",\n    ""SECONDARY_LOC"",\n    ""EXTRA_LOCS"",\n    ""DATE_LAST_APPROVED"",\n    ""APPROVER_ID"",\n    ""APPROVER_BADGE_NUMBER"",\n    ""APPROVAL_SWITCH"",\n    ""QA_CERT1"",\n    ""QA_CERT2"",\n    ""QA_CERT3"",\n    ""QA_CERT4"",\n    ""VALUE_ON_HAND"",\n    ""PREVIOUS_ITEM_ID"",\n    ""QTY_ALLOCATED"",\n    ""CONSUMABLE"",\n    ""SHELF_LIFE"",\n    ""PREVENT_MAINTENANCE"",\n    ""CORPORATE_SWITCH"",\n    ""ITEM_OWNER"",\n    ""SAFETY_IND"",\n    ""UTC_IND"",\n    ""ITEM_DEPT"",\n    ""IN_PROCESS_HOLD"",\n    ""PIT"",\n    ""QTY_EXCESS"",\n    ""NEW_RANK"",\n    ""SUB_STATUS"",\n    ""STRATIFIED_TRANS_COUNT"",\n    ""STRATIFIED_DATE"",\n    ""TOLERANCE_AMOUNT"",\n    ""TOLERANCE_PERCENTAGE"",\n    ""SITE_LAST_UPDATED"",\n    ""QTY_ON_HOLD"",\n    ""ITEM_LAST_UPDATED"",\n    ""UNIT_OF_PROPERTY_NUMBER"",\n    ""UNIT_OF_PROPERTY_IND"",\n    ""DATE_LAST_ISSUED"",\n    ""DATE_LAST_RETURNED"",\n    ""CRITICAL_ITEM"",\n    ""REVIEW_DATE"",\n    ""STOP"",\n    ""SAP_IND"",\n    ""SITE_NUMBER"",\n    ""ITEM_NUMBER"",\n    ""DESCRIPTION"",\n    ""UNIT_OF_MEASURE"",\n    ""DATE_CREATED"",\n    ""TAX_IND"",\n    ""UNIT_PRICE"",\n    ""TYPE_CODE"",\n    ""FUNCTIONAL_GROUP"",\n    ""MATERIAL_CLASS"",\n    ""STATUS"",\n    ""SITE_RANK"",\n    ""DATE_LAST_INVENTORIED"",\n    ""QTY_ON_ORDER"",\n    ""QTY_ON_HAND"",\n    ""QTY_AVAILABLE"",\n    ""MINIMUM"",\n    ""MAXIMUM"",\n    ""EOQ_QTY"",\n    ""QA_CODE"",\n    ""QA_LEVEL"",\n    ""CYCLE_IND"",\n    ""SHELF_LIFE_DATE"",\n    ""DATE_LAST_RECEIVED"",\n    ""FERC_CODE"",\n    ""PRIMARY_LOC"",\n    ""SECONDARY_LOC"",\n    ""EXTRA_LOCS"",\n    ""DATE_LAST_APPROVED"",\n    ""APPROVER_ID"",\n    ""APPROVER_BADGE_NUMBER"",\n    ""APPROVAL_SWITCH"",\n    ""QA_CERT1"",\n    ""QA_CERT2"",\n    ""QA_CERT3"",\n    ""QA_CERT4"",\n    ""VALUE_ON_HAND"",\n    ""PREVIOUS_ITEM_ID"",\n    ""QTY_ALLOCATED"",\n    ""CONSUMABLE"",\n    ""SHELF_LIFE"",\n    ""PREVENT_MAINTENANCE"",\n    ""CORPORATE_SWITCH"",\n    ""ITEM_OWNER"",\n    ""SAFETY_IND"",\n    ""UTC_IND"",\n    ""ITEM_DEPT"",\n    ""IN_PROCESS_HOLD"",\n    ""PIT"",\n    ""QTY_EXCESS"",\n    ""NEW_RANK"",\n    ""SUB_STATUS"",\n    ""STRATIFIED_TRANS_COUNT"",\n    ""STRATIFIED_DATE"",\n    ""TOLERANCE_AMOUNT"",\n    ""TOLERANCE_PERCENTAGE"",\n    ""SITE_LAST_UPDATED"",\n    ""QTY_ON_HOLD"",\n    ""ITEM_LAST_UPDATED"",\n    ""UNIT_OF_PROPERTY_NUMBER"",\n    ""UNIT_OF_PROPERTY_IND"",\n    ""DATE_LAST_ISSUED"",\n    ""DATE_LAST_RETURNED"",\n    ""CRITICAL_ITEM"",\n    ""REVIEW_DATE"",\n    ""STOP"",\n    ""SAP_IND""
FROM
    ""ITEM_SITE_EXTRACT""", null, [EnableFolding=true])
in
    ExecuteQuery
        



    annotation PBI_ResultType = Table