table 'Sheet1 (sample_sales_data)'


    column 'Region Sales'
        dataType: string
        summarizeBy: none

        sourceColumn = ```
            
            'Sheet1 (sample_sales_data)'[Region] & " Sales"
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Region Split'
        dataType: string
        summarizeBy: none

        sourceColumn = ```
            
            SWITCH(
    'Sheet1 (sample_sales_data)'[Calculation_606860061092720640],
    "North Sales", "North East",
    "East Sales", "North East",
    "South Sales", "South West",
    "West Sales", "South West"
)
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Order ID'
        dataType: int64
        summarizeBy: sum

        sourceColumn: Order ID

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Order Date'
        dataType: datetime
        summarizeBy: none

        sourceColumn: Order Date

        annotation SummarizationSetBy = Automatic

        
    column 'Region'
        dataType: string
        summarizeBy: none

        sourceColumn: Region

        annotation SummarizationSetBy = Automatic

        
    column 'Product Category'
        dataType: string
        summarizeBy: none

        sourceColumn: Product Category

        annotation SummarizationSetBy = Automatic

        
    column 'Product Name'
        dataType: string
        summarizeBy: none

        sourceColumn: Product Name

        annotation SummarizationSetBy = Automatic

        
    column 'Sales'
        dataType: double
        summarizeBy: sum

        sourceColumn: Sales

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Quantity'
        dataType: int64
        summarizeBy: sum

        sourceColumn: Quantity

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Discount'
        dataType: double
        summarizeBy: sum

        sourceColumn: Discount

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Profit'
        dataType: double
        summarizeBy: sum

        sourceColumn: Profit

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        

    measure 'Units' = ```
			'Sheet1 (sample_sales_data)'[Sales] / 'Sheet1 (sample_sales_data)'[Quantity]
			```

    measure 'Units Measure' = ```
			SUM('Sheet1 (sample_sales_data)'[Calculation_606860061096038402])
			```



    partition 'Sheet1' = m
        mode: import
        source = 
            	let
					Source = Excel.Workbook(File.Contents("C:/Users/CodehiveBIVM/Desktop/Datasets/sample_sales_data.xlsx"), null, true),
					Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
					#"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Region Sales", type text}, {"Region Split", type text}, {"Order ID", Int64.Type}, {"Order Date", type datetime}, {"Region", type text}, {"Product Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
					#"Changed Type"
        



    annotation PBI_ResultType = Table
