table 'Query1'

	column '[Order Date]'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: [C].[C_Sample_data_module].[Sheet1].[Order_Date]

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation CognosUsage = identifier
		annotation CognosRegularAggregate = none

	column '[Region]'
		dataType: string
		summarizeBy: none
		sourceColumn: [C].[C_Sample_data_module].[Sheet1].[Region]

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation CognosUsage = identifier
		annotation CognosRegularAggregate = none

	column '[Product Category]'
		dataType: string
		summarizeBy: none
		sourceColumn: [C].[C_Sample_data_module].[Sheet1].[Product_Category]

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation CognosUsage = identifier
		annotation CognosRegularAggregate = none

	column '[Product Name]'
		dataType: string
		summarizeBy: none
		sourceColumn: [C].[C_Sample_data_module].[Sheet1].[Product_Name]

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation CognosUsage = attribute
		annotation CognosRegularAggregate = none

	column '[Sales]'
		dataType: decimal
		summarizeBy: sum
		sourceColumn: [C].[C_Sample_data_module].[Sheet1].[Sales]

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = fact
		annotation CognosRegularAggregate = total

	column '[Profit]'
		dataType: decimal
		summarizeBy: sum
		sourceColumn: [C].[C_Sample_data_module].[Sheet1].[Profit]

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = fact
		annotation CognosRegularAggregate = total

	column '[Order ID]'
		dataType: int64
		summarizeBy: none
		sourceColumn: [C].[C_Sample_data_module].[Sheet1].[Order_ID]

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = identifier
		annotation CognosRegularAggregate = none

	column '[Quantity]'
		dataType: decimal
		summarizeBy: sum
		sourceColumn: [C].[C_Sample_data_module].[Sheet1].[Quantity]

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = fact
		annotation CognosRegularAggregate = total

	column '[Discount]'
		dataType: decimal
		summarizeBy: sum
		sourceColumn: [C].[C_Sample_data_module].[Sheet1].[Discount]

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = fact
		annotation CognosRegularAggregate = total

	column '[Profit Margin (%)]'
		dataType: decimal
		summarizeBy: sum
		sourceColumn: ([Profit]/[Sales])*100

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = fact

	column '[Average Sales per Order]'
		dataType: decimal
		summarizeBy: sum
		sourceColumn: [Sales] / count([Order ID] for [Order ID])

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = fact

	column '[Sales per Unit]'
		dataType: decimal
		summarizeBy: sum
		sourceColumn: [Sales] / [Quantity]

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = fact

	column '[Discounted Sales]'
		dataType: decimal
		summarizeBy: sum
		sourceColumn: [Sales] - ([Sales] * [Discount])

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = fact

	column '[Profit per Unit]'
		dataType: decimal
		summarizeBy: sum
		sourceColumn: [Profit] / [Quantity]

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = fact

	column '[Discount Percentage]'
		dataType: decimal
		summarizeBy: sum
		sourceColumn: [Discount] * 100

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = fact

	partition 'Query1-partition' = m
		mode: import
		source = 
			let
				Source = Excel.Workbook(File.Contents("Query1.xlsx"), null, true),
				Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				#"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

	annotation PBI_ResultType = Table
