table Dim_PURCHASE_ORDER_LINE_MATERIAL_CHARGES


    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER_SITE_NUMBER_Key'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER_SITE_NUMBER_Key

        

        annotation SummarizationSetBy = Automatic

        



    partition 'Dim_PURCHASE_ORDER_LINE_MATERIAL_CHARGES' = m
        mode: directQuery
        source = 
            let
                // Get data from PURCHASE_ORDER_LINE
                Data_From_PURCHASE_ORDER_LINE = Table.SelectColumns(PURCHASE_ORDER_LINE, {"SITE_NUMBER", "ITEM_NUMBER"}),
                // Get data from MATERIAL_CHARGES
                Data_From_MATERIAL_CHARGES = Table.SelectColumns(MATERIAL_CHARGES, {"SITE_NUMBER", "ITEM_NUMBER"}),
                // Combine data from all source tables
                CombinedData = Table.Combine({Data_From_PURCHASE_ORDER_LINE, Data_From_MATERIAL_CHARGES}),
                // Get unique combinations of dimension keys
                UniqueRows = Table.Distinct(CombinedData, {"SITE_NUMBER", "ITEM_NUMBER"}),
                // Create composite key for relationships
                AddCompositeKey = Table.AddColumn(UniqueRows, "ITEM_NUMBER_SITE_NUMBER_Key", each Text.Combine({[ITEM_NUMBER], [SITE_NUMBER]}, "|"), type text),
                // Filter out rows with null or empty composite keys
                FilteredRows = Table.SelectRows(AddCompositeKey, each [ITEM_NUMBER_SITE_NUMBER_Key] <> null and [ITEM_NUMBER_SITE_NUMBER_Key] <> "")
            in
                FilteredRows
        



    annotation PBI_ResultType = Table