table Dim_ITEM_SITE_EXTRACT_STORAGE_LOCATION


    column 'Column'
        dataType: string
        summarizeBy: none
        sourceColumn: Column

        

        annotation SummarizationSetBy = Automatic

        
    column 'Column'
        dataType: string
        summarizeBy: none
        sourceColumn: Column

        

        annotation SummarizationSetBy = Automatic

        
    column 'Column'
        dataType: string
        summarizeBy: none
        sourceColumn: Column

        

        annotation SummarizationSetBy = Automatic

        



    partition 'Dim_ITEM_SITE_EXTRACT_STORAGE_LOCATION' = m
        mode: directQuery
        source = 
            let
                // Get data from ITEM_SITE_EXTRACT
                Data_From_ITEM_SITE_EXTRACT = Table.SelectColumns(ITEM_SITE_EXTRACT, {"ITEM_NUMBER", "SITE_NUMBER"}),
                // Get data from STORAGE_LOCATION
                Data_From_STORAGE_LOCATION = Table.SelectColumns(STORAGE_LOCATION, {"ITEM_NUMBER", "SITE_NUMBER"}),
                // Combine data from all source tables
                CombinedData = Table.Combine({Data_From_ITEM_SITE_EXTRACT, Data_From_STORAGE_LOCATION}),
                // Get unique combinations of dimension keys
                UniqueRows = Table.Distinct(CombinedData, {"ITEM_NUMBER", "SITE_NUMBER"}),
                // Create composite key for relationships
                AddCompositeKey = Table.AddColumn(UniqueRows, "ITEM_NUMBER_SITE_NUMBER_Key", each Text.Combine({[ITEM_NUMBER], [SITE_NUMBER]}, "|"), type text),
                // Filter out rows with null or empty composite keys
                FilteredRows = Table.SelectRows(AddCompositeKey, each [ITEM_NUMBER_SITE_NUMBER_Key] <> null and [ITEM_NUMBER_SITE_NUMBER_Key] <> "")
            in
                FilteredRows
        



    annotation PBI_ResultType = Table