table ITEM_NUMBER


    column 'SITE'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'MARK_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: MARK_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_ALT'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_ALT

        

        annotation SummarizationSetBy = Automatic

        
    column 'SOURCE'
        dataType: string
        summarizeBy: none
        sourceColumn: SOURCE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ONBILL'
        dataType: string
        summarizeBy: none
        sourceColumn: ONBILL

        

        annotation SummarizationSetBy = Automatic

        
    column 'LAST_ISSUE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: LAST_ISSUE

        

        annotation SummarizationSetBy = Automatic

        
    column 'AUDIT_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: AUDIT_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_IN_USE'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_IN_USE

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNKNOWN'
        dataType: string
        summarizeBy: none
        sourceColumn: UNKNOWN

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'MARK_NUMBER_COMPRESSED'
        dataType: string
        summarizeBy: none
        sourceColumn: MARK_NUMBER_COMPRESSED

        

        annotation SummarizationSetBy = Automatic

        

    measure 'ITEM_NUMBER - Count by AUDIT_DATE' = ```
            CALCULATE(
    COUNTROWS('ITEM_NUMBER'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITEM_NUMBER'[AUDIT_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'ITEM_NUMBER - Count by LAST_ISSUE' = ```
            CALCULATE(
    COUNTROWS('ITEM_NUMBER'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITEM_NUMBER'[LAST_ISSUE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'ITEM_NUMBER' = m
        mode: import
        source = 
            // ERROR: argument should be a str or an os.PathLike object where __fspath__ returns a str, not 'LLMServiceClient'
let
				Source = Table.FromRows({})
				in
				Source
        



    annotation PBI_ResultType = Table