table ITEM_NUMBER


    column 'SITE'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'MARK_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: MARK_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_ALT'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_ALT

        

        annotation SummarizationSetBy = Automatic

        
    column 'SOURCE'
        dataType: string
        summarizeBy: none
        sourceColumn: SOURCE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ONBILL'
        dataType: string
        summarizeBy: none
        sourceColumn: ONBILL

        

        annotation SummarizationSetBy = Automatic

        
    column 'LAST_ISSUE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: LAST_ISSUE

        

        annotation SummarizationSetBy = Automatic

        
    column 'AUDIT_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: AUDIT_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_IN_USE'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_IN_USE

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNKNOWN'
        dataType: string
        summarizeBy: none
        sourceColumn: UNKNOWN

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'MARK_NUMBER_COMPRESSED'
        dataType: string
        summarizeBy: none
        sourceColumn: MARK_NUMBER_COMPRESSED

        

        annotation SummarizationSetBy = Automatic

        

    measure 'ITEM_NUMBER - Count by AUDIT_DATE' = ```
            CALCULATE(
    COUNTROWS('ITEM_NUMBER'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITEM_NUMBER'[AUDIT_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'ITEM_NUMBER - Count by LAST_ISSUE' = ```
            CALCULATE(
    COUNTROWS('ITEM_NUMBER'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITEM_NUMBER'[LAST_ISSUE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'ITEM_NUMBER' = m
        mode: import
        source = 
            	let
					Source = Sql.Database(#"DB Server", #"DB Name"),
					// Validate connection
ValidateConnection = try Source otherwise error 
"Failed to connect to database. Error: " & Text.From([Error][Message]),
					// Execute query with folding
ExecuteQuery = Value.NativeQuery(
ValidateConnection, 
"Select",
null,
[EnableFolding=true]
),
					// Validate results
ValidateResults = if Table.IsEmpty(ExecuteQuery) then error "No data returned from query for table ITEM_NUMBER" else ExecuteQuery,
					// Apply data type transformations
TransformTypes = Table.TransformColumnTypes( ValidateResults, { {"$SITE", type string}, {"$ITEM_NUMBER", type string}, {"$MARK_NUMBER", type string}, {"$ITEM_ALT", type string}, {"$SOURCE", type string}, {"$ONBILL", type string}, {"$LAST_ISSUE", type datetime}, {"$AUDIT_DATE", type datetime}, {"$QTY_IN_USE", type int64}, {"$UNKNOWN", type string}, {"$STOP", type string}, {"$MARK_NUMBER_COMPRESSED", type string}, {"$SITE", type string}, {"$ITEM_NUMBER", type string}, {"$MARK_NUMBER", type string}, {"$ITEM_ALT", type string}, {"$SOURCE", type string}, {"$ONBILL", type string}, {"$LAST_ISSUE", type datetime}, {"$AUDIT_DATE", type datetime}, {"$QTY_IN_USE", type int64}, {"$UNKNOWN", type string}, {"$STOP", type string}, {"$MARK_NUMBER_COMPRESSED", type string} } ),
					// Handle nulls appropriately
HandleNulls = Table.ReplaceValue( TransformTypes, null, "", Replacer.ReplaceValue, Table.ColumnNames(TransformTypes) )
				in
					HandleNulls
        



    annotation PBI_ResultType = Table