table ITEM_ROOT_EXTENDED_DESCRIPTION


    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ROOT_DESCRIPTION'
        dataType: string
        summarizeBy: none
        sourceColumn: ROOT_DESCRIPTION

        

        annotation SummarizationSetBy = Automatic

        
    column 'TOTAL_NUMBER_SEGMENTS'
        dataType: int64
        summarizeBy: none
        sourceColumn: TOTAL_NUMBER_SEGMENTS

        

        annotation SummarizationSetBy = Automatic

        
    column 'NUMBER_SEGMENTS_SELECTED'
        dataType: int64
        summarizeBy: none
        sourceColumn: NUMBER_SEGMENTS_SELECTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'LINE_NUMBER1'
        dataType: string
        summarizeBy: none
        sourceColumn: LINE_NUMBER1

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION1'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION1

        

        annotation SummarizationSetBy = Automatic

        
    column 'TYPE1'
        dataType: string
        summarizeBy: none
        sourceColumn: TYPE1

        

        annotation SummarizationSetBy = Automatic

        
    column 'LINE_NUMBER2'
        dataType: string
        summarizeBy: none
        sourceColumn: LINE_NUMBER2

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION2'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION2

        

        annotation SummarizationSetBy = Automatic

        
    column 'TYPE2'
        dataType: string
        summarizeBy: none
        sourceColumn: TYPE2

        

        annotation SummarizationSetBy = Automatic

        
    column 'LINE_NUMBER3'
        dataType: string
        summarizeBy: none
        sourceColumn: LINE_NUMBER3

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION3'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION3

        

        annotation SummarizationSetBy = Automatic

        
    column 'TYPE3'
        dataType: string
        summarizeBy: none
        sourceColumn: TYPE3

        

        annotation SummarizationSetBy = Automatic

        
    column 'LINE_NUMBER4'
        dataType: string
        summarizeBy: none
        sourceColumn: LINE_NUMBER4

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION4'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION4

        

        annotation SummarizationSetBy = Automatic

        
    column 'TYPE4'
        dataType: string
        summarizeBy: none
        sourceColumn: TYPE4

        

        annotation SummarizationSetBy = Automatic

        
    column 'LINE_NUMBER5'
        dataType: string
        summarizeBy: none
        sourceColumn: LINE_NUMBER5

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION5'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION5

        

        annotation SummarizationSetBy = Automatic

        
    column 'TYPE5'
        dataType: string
        summarizeBy: none
        sourceColumn: TYPE5

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE

        

        annotation SummarizationSetBy = Automatic

        



    partition 'ITEM_ROOT_EXTENDED_DESCRIPTION' = m
        mode: import
        source = 
            	let
					Source = Sql.Database(#"DB Server", #"DB Name"),
					// Validate connection
ValidateConnection = try Source otherwise error 
"Failed to connect to database. Error: " & Text.From([Error][Message]),
					// Execute query with folding
ExecuteQuery = Value.NativeQuery(
ValidateConnection, 
"Select",
null,
[EnableFolding=true]
),
					// Validate results
ValidateResults = if Table.IsEmpty(ExecuteQuery) then error "No data returned from query for table ITEM_ROOT_EXTENDED_DESCRIPTION" else ExecuteQuery,
					// Apply data type transformations
TransformTypes = Table.TransformColumnTypes( ValidateResults, { {"$ITEM_NUMBER", type string}, {"$ROOT_DESCRIPTION", type string}, {"$TOTAL_NUMBER_SEGMENTS", type int64}, {"$NUMBER_SEGMENTS_SELECTED", type int64}, {"$LINE_NUMBER1", type string}, {"$DESCRIPTION1", type string}, {"$TYPE1", type string}, {"$LINE_NUMBER2", type string}, {"$DESCRIPTION2", type string}, {"$TYPE2", type string}, {"$LINE_NUMBER3", type string}, {"$DESCRIPTION3", type string}, {"$TYPE3", type string}, {"$LINE_NUMBER4", type string}, {"$DESCRIPTION4", type string}, {"$TYPE4", type string}, {"$LINE_NUMBER5", type string}, {"$DESCRIPTION5", type string}, {"$TYPE5", type string}, {"$STOP", type string}, {"$SITE", type string}, {"$ITEM_NUMBER", type string}, {"$ROOT_DESCRIPTION", type string}, {"$TOTAL_NUMBER_SEGMENTS", type int64}, {"$NUMBER_SEGMENTS_SELECTED", type int64}, {"$LINE_NUMBER1", type string}, {"$DESCRIPTION1", type string}, {"$TYPE1", type string}, {"$LINE_NUMBER2", type string}, {"$DESCRIPTION2", type string}, {"$TYPE2", type string}, {"$LINE_NUMBER3", type string}, {"$DESCRIPTION3", type string}, {"$TYPE3", type string}, {"$LINE_NUMBER4", type string}, {"$DESCRIPTION4", type string}, {"$TYPE4", type string}, {"$LINE_NUMBER5", type string}, {"$DESCRIPTION5", type string}, {"$TYPE5", type string}, {"$STOP", type string}, {"$SITE", type string} } ),
					// Handle nulls appropriately
HandleNulls = Table.ReplaceValue( TransformTypes, null, "", Replacer.ReplaceValue, Table.ColumnNames(TransformTypes) )
				in
					HandleNulls
        



    annotation PBI_ResultType = Table