table ITT_MATERIAL


    column 'ITT_KEY_NO'
        dataType: string
        summarizeBy: none
        sourceColumn: ITT_KEY_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'CREATION_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: CREATION_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_RELEASED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_RELEASED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_UPDATED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_UPDATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'EMP_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: EMP_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_IPH'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_IPH

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_BEING_TESTED'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_BEING_TESTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ACCEPTED'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_ACCEPTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_REJECTED'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_REJECTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'PRICE_OF_ITEM_IPH'
        dataType: int64
        summarizeBy: none
        sourceColumn: PRICE_OF_ITEM_IPH

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITT_LOCATION'
        dataType: string
        summarizeBy: none
        sourceColumn: ITT_LOCATION

        

        annotation SummarizationSetBy = Automatic

        
    column 'PTE_NO'
        dataType: string
        summarizeBy: none
        sourceColumn: PTE_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NO'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'CHG_ORDER_NO'
        dataType: string
        summarizeBy: none
        sourceColumn: CHG_ORDER_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'RELEASE_NO'
        dataType: string
        summarizeBy: none
        sourceColumn: RELEASE_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_LINE_NO'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_LINE_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_SUB_LINE_NO'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_SUB_LINE_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'ORIGIN'
        dataType: string
        summarizeBy: none
        sourceColumn: ORIGIN

        

        annotation SummarizationSetBy = Automatic

        
    column 'PTE_REV_NO'
        dataType: string
        summarizeBy: none
        sourceColumn: PTE_REV_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'FILLER'
        dataType: string
        summarizeBy: none
        sourceColumn: FILLER

        

        annotation SummarizationSetBy = Automatic

        
    column 'TEST_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: TEST_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TEST_DESC'
        dataType: string
        summarizeBy: none
        sourceColumn: TEST_DESC

        

        annotation SummarizationSetBy = Automatic

        
    column 'TEST_LOC'
        dataType: string
        summarizeBy: none
        sourceColumn: TEST_LOC

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_DESC'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_DESC

        

        annotation SummarizationSetBy = Automatic

        
    column 'TEST_RESULT'
        dataType: string
        summarizeBy: none
        sourceColumn: TEST_RESULT

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_IN_TEST'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_IN_TEST

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_TEST_COMP'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_TEST_COMP

        

        annotation SummarizationSetBy = Automatic

        

    measure 'ITT_MATERIAL - Count by CREATION_DATE' = ```
            CALCULATE(
    COUNTROWS('ITT_MATERIAL'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITT_MATERIAL'[CREATION_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'ITT_MATERIAL - Count by DATE_IN_TEST' = ```
            CALCULATE(
    COUNTROWS('ITT_MATERIAL'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITT_MATERIAL'[DATE_IN_TEST])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'ITT_MATERIAL - Count by DATE_LAST_RELEASED' = ```
            CALCULATE(
    COUNTROWS('ITT_MATERIAL'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITT_MATERIAL'[DATE_LAST_RELEASED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'ITT_MATERIAL - Count by DATE_LAST_UPDATED' = ```
            CALCULATE(
    COUNTROWS('ITT_MATERIAL'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITT_MATERIAL'[DATE_LAST_UPDATED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'ITT_MATERIAL - Count by DATE_TEST_COMP' = ```
            CALCULATE(
    COUNTROWS('ITT_MATERIAL'),
    USERELATIONSHIP('CentralDateTable'[Date], 'ITT_MATERIAL'[DATE_TEST_COMP])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'ITT_MATERIAL' = m
        mode: import
        source = 
            	let
					Source = Sql.Database(#"DB Server", #"DB Name"),
					// Validate connection
ValidateConnection = try Source otherwise error 
"Failed to connect to database. Error: " & Text.From([Error][Message]),
					// Execute query with folding
ExecuteQuery = Value.NativeQuery(
ValidateConnection, 
"Select",
null,
[EnableFolding=true]
),
					// Validate results
ValidateResults = if Table.IsEmpty(ExecuteQuery) then error "No data returned from query for table ITT_MATERIAL" else ExecuteQuery,
					// Apply data type transformations
TransformTypes = Table.TransformColumnTypes( ValidateResults, { {"$ITT_KEY_NO", type string}, {"$SITE_NUMBER", type string}, {"$ITEM_NUMBER", type string}, {"$CREATION_DATE", type datetime}, {"$DATE_LAST_RELEASED", type datetime}, {"$DATE_LAST_UPDATED", type datetime}, {"$EMP_ID", type string}, {"$QTY_IPH", type int64}, {"$QTY_BEING_TESTED", type int64}, {"$QTY_ACCEPTED", type int64}, {"$QTY_REJECTED", type int64}, {"$PRICE_OF_ITEM_IPH", type int64}, {"$ITT_LOCATION", type string}, {"$PTE_NO", type string}, {"$PO_NO", type string}, {"$CHG_ORDER_NO", type string}, {"$RELEASE_NO", type string}, {"$PO_LINE_NO", type string}, {"$PO_SUB_LINE_NO", type string}, {"$ORIGIN", type string}, {"$PTE_REV_NO", type string}, {"$FILLER", type string}, {"$TEST_TYPE", type string}, {"$TEST_DESC", type string}, {"$TEST_LOC", type string}, {"$LOC_DESC", type string}, {"$TEST_RESULT", type string}, {"$DATE_IN_TEST", type datetime}, {"$DATE_TEST_COMP", type datetime}, {"$ITT_KEY_NO", type string}, {"$SITE_NUMBER", type string}, {"$ITEM_NUMBER", type string}, {"$CREATION_DATE", type datetime}, {"$DATE_LAST_RELEASED", type datetime}, {"$DATE_LAST_UPDATED", type datetime}, {"$EMP_ID", type string}, {"$QTY_IPH", type int64}, {"$QTY_BEING_TESTED", type int64}, {"$QTY_ACCEPTED", type int64}, {"$QTY_REJECTED", type int64}, {"$PRICE_OF_ITEM_IPH", type int64}, {"$ITT_LOCATION", type string}, {"$PTE_NO", type string}, {"$PO_NO", type string}, {"$CHG_ORDER_NO", type string}, {"$RELEASE_NO", type string}, {"$PO_LINE_NO", type string}, {"$PO_SUB_LINE_NO", type string}, {"$ORIGIN", type string}, {"$PTE_REV_NO", type string}, {"$FILLER", type string}, {"$TEST_TYPE", type string}, {"$TEST_DESC", type string}, {"$TEST_LOC", type string}, {"$LOC_DESC", type string}, {"$TEST_RESULT", type string}, {"$DATE_IN_TEST", type datetime}, {"$DATE_TEST_COMP", type datetime} } ),
					// Handle nulls appropriately
HandleNulls = Table.ReplaceValue( TransformTypes, null, "", Replacer.ReplaceValue, Table.ColumnNames(TransformTypes) )
				in
					HandleNulls
        



    annotation PBI_ResultType = Table