table MANUFACTURER


    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'MFG_PART_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: MFG_PART_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'MODEL_PART_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: MODEL_PART_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'ACTIVITY_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: ACTIVITY_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'MFG_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: MFG_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_CREATED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_CREATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'MFG_NAME'
        dataType: string
        summarizeBy: none
        sourceColumn: MFG_NAME

        

        annotation SummarizationSetBy = Automatic

        
    column 'COMPRESSED_PART_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: COMPRESSED_PART_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'FOSSIL_OR_NUCLEAR'
        dataType: string
        summarizeBy: none
        sourceColumn: FOSSIL_OR_NUCLEAR

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE

        

        annotation SummarizationSetBy = Automatic

        

    measure 'MANUFACTURER - Count by DATE_CREATED' = ```
            CALCULATE(
    COUNTROWS('MANUFACTURER'),
    USERELATIONSHIP('CentralDateTable'[Date], 'MANUFACTURER'[DATE_CREATED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'MANUFACTURER' = m
        mode: import
        source = 
            	let
					Source = Sql.Database(#"DB Server", #"DB Name"),
					// Validate connection
ValidateConnection = try Source otherwise error 
"Failed to connect to database. Error: " & Text.From([Error][Message]),
					// Execute query with folding
ExecuteQuery = Value.NativeQuery(
ValidateConnection, 
"Select",
null,
[EnableFolding=true]
),
					// Validate results
ValidateResults = if Table.IsEmpty(ExecuteQuery) then error "No data returned from query for table MANUFACTURER" else ExecuteQuery,
					// Apply data type transformations
TransformTypes = Table.TransformColumnTypes( ValidateResults, { {"$ITEM_NUMBER", type string}, {"$MFG_PART_NUMBER", type string}, {"$MODEL_PART_IND", type string}, {"$ACTIVITY_CODE", type string}, {"$MFG_CODE", type string}, {"$DATE_CREATED", type datetime}, {"$MFG_NAME", type string}, {"$COMPRESSED_PART_NUMBER", type string}, {"$FOSSIL_OR_NUCLEAR", type string}, {"$STOP", type string}, {"$SITE", type string}, {"$ITEM_NUMBER", type string}, {"$MFG_PART_NUMBER", type string}, {"$MODEL_PART_IND", type string}, {"$ACTIVITY_CODE", type string}, {"$MFG_CODE", type string}, {"$DATE_CREATED", type datetime}, {"$MFG_NAME", type string}, {"$COMPRESSED_PART_NUMBER", type string}, {"$FOSSIL_OR_NUCLEAR", type string}, {"$STOP", type string}, {"$SITE", type string} } ),
					// Handle nulls appropriately
HandleNulls = Table.ReplaceValue( TransformTypes, null, "", Replacer.ReplaceValue, Table.ColumnNames(TransformTypes) )
				in
					HandleNulls
        



    annotation PBI_ResultType = Table