table MATERIAL_CHARGES


    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'CHARGED_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: CHARGED_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TIME_ENTERED'
        dataType: string
        summarizeBy: none
        sourceColumn: TIME_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOREKEEPER_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: STOREKEEPER_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'EMPLOYEE_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: EMPLOYEE_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'ISSUE_TICKET_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ISSUE_TICKET_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'TRANSACTION_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: TRANSACTION_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ADJUSTMENT_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: ADJUSTMENT_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QUANTITY'
        dataType: int64
        summarizeBy: none
        sourceColumn: QUANTITY

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: int64
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TRANSACTION_VALUE'
        dataType: int64
        summarizeBy: none
        sourceColumn: TRANSACTION_VALUE

        

        annotation SummarizationSetBy = Automatic

        
    column 'JOB_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: JOB_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'BU_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: BU_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_INDICATOR'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_INDICATOR

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ENTERED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_STATUS_EFFECTIVE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_STATUS_EFFECTIVE

        

        annotation SummarizationSetBy = Automatic

        
    column 'REFURB_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: REFURB_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'ISSUE_OVERRIDE_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: ISSUE_OVERRIDE_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'RECORD_STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: RECORD_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_MEASURE'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_OF_MEASURE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ADJUSTMENT_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ADJUSTMENT_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ADJUSTMENT_DESC'
        dataType: string
        summarizeBy: none
        sourceColumn: ADJUSTMENT_DESC

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_TO_RECONCILE'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_TO_RECONCILE

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'TRANSFER_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: TRANSFER_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'MATERIAL_CLASS'
        dataType: string
        summarizeBy: none
        sourceColumn: MATERIAL_CLASS

        

        annotation SummarizationSetBy = Automatic

        
    column 'ROOT_DESCRIPTION'
        dataType: string
        summarizeBy: none
        sourceColumn: ROOT_DESCRIPTION

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITT_KEY_NO'
        dataType: string
        summarizeBy: none
        sourceColumn: ITT_KEY_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'UTC_NO'
        dataType: string
        summarizeBy: none
        sourceColumn: UTC_NO

        

        annotation SummarizationSetBy = Automatic

        
    column 'PIT_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: PIT_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'UM'
        dataType: string
        summarizeBy: none
        sourceColumn: UM

        

        annotation SummarizationSetBy = Automatic

        

    measure 'MATERIAL_CHARGES - Count by CHARGED_DATE' = ```
            CALCULATE(
    COUNTROWS('MATERIAL_CHARGES'),
    USERELATIONSHIP('CentralDateTable'[Date], 'MATERIAL_CHARGES'[CHARGED_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'MATERIAL_CHARGES - Count by DATE_ENTERED' = ```
            CALCULATE(
    COUNTROWS('MATERIAL_CHARGES'),
    USERELATIONSHIP('CentralDateTable'[Date], 'MATERIAL_CHARGES'[DATE_ENTERED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'MATERIAL_CHARGES - Count by DATE_STATUS_EFFECTIVE' = ```
            CALCULATE(
    COUNTROWS('MATERIAL_CHARGES'),
    USERELATIONSHIP('CentralDateTable'[Date], 'MATERIAL_CHARGES'[DATE_STATUS_EFFECTIVE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'MATERIAL_CHARGES' = m
        mode: import
        source = 
            	let
					Source = Sql.Database(#"DB Server", #"DB Name"),
					// Validate connection
ValidateConnection = try Source otherwise error 
"Failed to connect to database. Error: " & Text.From([Error][Message]),
					// Execute query with folding
ExecuteQuery = Value.NativeQuery(
ValidateConnection, 
"Select",
null,
[EnableFolding=true]
),
					// Validate results
ValidateResults = if Table.IsEmpty(ExecuteQuery) then error "No data returned from query for table MATERIAL_CHARGES" else ExecuteQuery,
					// Apply data type transformations
TransformTypes = Table.TransformColumnTypes( ValidateResults, { {"$SITE_NUMBER", type string}, {"$ITEM_NUMBER", type string}, {"$CHARGED_DATE", type datetime}, {"$TIME_ENTERED", type string}, {"$STOREKEEPER_ID", type string}, {"$EMPLOYEE_ID", type string}, {"$ISSUE_TICKET_NUMBER", type string}, {"$TRANSACTION_TYPE", type string}, {"$ADJUSTMENT_TYPE", type string}, {"$QUANTITY", type int64}, {"$UNIT_PRICE", type int64}, {"$TRANSACTION_VALUE", type int64}, {"$JOB_NUMBER", type string}, {"$BU_NUMBER", type string}, {"$PO_NUMBER", type string}, {"$PO_INDICATOR", type string}, {"$DATE_ENTERED", type datetime}, {"$DATE_STATUS_EFFECTIVE", type datetime}, {"$REFURB_IND", type string}, {"$ISSUE_OVERRIDE_IND", type string}, {"$RECORD_STATUS", type string}, {"$UNIT_OF_MEASURE", type string}, {"$ADJUSTMENT_NUMBER", type string}, {"$ADJUSTMENT_DESC", type string}, {"$QTY_TO_RECONCILE", type int64}, {"$STOP", type string}, {"$TRANSFER_NUMBER", type string}, {"$MATERIAL_CLASS", type string}, {"$ROOT_DESCRIPTION", type string}, {"$ITT_KEY_NO", type string}, {"$UTC_NO", type string}, {"$PIT_IND", type string}, {"$UM", type string}, {"$SITE_NUMBER", type string}, {"$ITEM_NUMBER", type string}, {"$CHARGED_DATE", type datetime}, {"$TIME_ENTERED", type string}, {"$STOREKEEPER_ID", type string}, {"$EMPLOYEE_ID", type string}, {"$ISSUE_TICKET_NUMBER", type string}, {"$TRANSACTION_TYPE", type string}, {"$ADJUSTMENT_TYPE", type string}, {"$QUANTITY", type int64}, {"$UNIT_PRICE", type int64}, {"$TRANSACTION_VALUE", type int64}, {"$JOB_NUMBER", type string}, {"$BU_NUMBER", type string}, {"$PO_NUMBER", type string}, {"$PO_INDICATOR", type string}, {"$DATE_ENTERED", type datetime}, {"$DATE_STATUS_EFFECTIVE", type datetime}, {"$REFURB_IND", type string}, {"$ISSUE_OVERRIDE_IND", type string}, {"$RECORD_STATUS", type string}, {"$UNIT_OF_MEASURE", type string}, {"$ADJUSTMENT_NUMBER", type string}, {"$ADJUSTMENT_DESC", type string}, {"$QTY_TO_RECONCILE", type int64}, {"$STOP", type string}, {"$TRANSFER_NUMBER", type string}, {"$MATERIAL_CLASS", type string}, {"$ROOT_DESCRIPTION", type string}, {"$ITT_KEY_NO", type string}, {"$UTC_NO", type string}, {"$PIT_IND", type string}, {"$UM", type string} } ),
					// Handle nulls appropriately
HandleNulls = Table.ReplaceValue( TransformTypes, null, "", Replacer.ReplaceValue, Table.ColumnNames(TransformTypes) )
				in
					HandleNulls
        



    annotation PBI_ResultType = Table