table PURCHASE_ORDER_RECEIPT


    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'CHANGE_ORDER_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: CHANGE_ORDER_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'RELEASE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: RELEASE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_LINE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_LINE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ENTERED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'TIME_ENTERED'
        dataType: string
        summarizeBy: none
        sourceColumn: TIME_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_RECEIVED'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_RECEIVED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_REJECTED'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_REJECTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'SHELF_LIFE'
        dataType: string
        summarizeBy: none
        sourceColumn: SHELF_LIFE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_INSPECTOR'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_INSPECTOR

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOREKEEPER_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: STOREKEEPER_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'RECEIPT_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: RECEIPT_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: int64
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_RECEIVED_AT_SITE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_RECEIVED_AT_SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'RECEIPT_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: RECEIPT_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_STATUS_EFFECTIVE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_STATUS_EFFECTIVE

        

        annotation SummarizationSetBy = Automatic

        
    column 'HOLD_STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: HOLD_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'DSR_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: DSR_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_IN_HOLD'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_IN_HOLD

        

        annotation SummarizationSetBy = Automatic

        
    column 'RECORD_STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: RECORD_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITT_KEY_NO'
        dataType: string
        summarizeBy: none
        sourceColumn: ITT_KEY_NO

        

        annotation SummarizationSetBy = Automatic

        

    measure 'PURCHASE_ORDER_RECEIPT - Count by DATE_ENTERED' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_RECEIPT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_RECEIPT'[DATE_ENTERED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_RECEIPT - Count by DATE_RECEIVED_AT_SITE' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_RECEIPT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_RECEIPT'[DATE_RECEIVED_AT_SITE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_RECEIPT - Count by DATE_STATUS_EFFECTIVE' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_RECEIPT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_RECEIPT'[DATE_STATUS_EFFECTIVE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'PURCHASE_ORDER_RECEIPT' = m
        mode: import
        source = 
            	let
					Source = Sql.Database(#"DB Server", #"DB Name"),
					// Validate connection
ValidateConnection = try Source otherwise error 
"Failed to connect to database. Error: " & Text.From([Error][Message]),
					// Execute query with folding
ExecuteQuery = Value.NativeQuery(
ValidateConnection, 
"Select",
null,
[EnableFolding=true]
),
					// Validate results
ValidateResults = if Table.IsEmpty(ExecuteQuery) then error "No data returned from query for table PURCHASE_ORDER_RECEIPT" else ExecuteQuery,
					// Apply data type transformations
TransformTypes = Table.TransformColumnTypes( ValidateResults, { {"$SITE_NUMBER", type string}, {"$PO_NUMBER", type string}, {"$CHANGE_ORDER_NUMBER", type string}, {"$RELEASE_NUMBER", type string}, {"$PO_LINE_NUMBER", type string}, {"$DATE_ENTERED", type datetime}, {"$TIME_ENTERED", type string}, {"$QTY_RECEIVED", type int64}, {"$QTY_REJECTED", type int64}, {"$QA_CODE", type string}, {"$SHELF_LIFE", type string}, {"$QA_INSPECTOR", type string}, {"$STOREKEEPER_ID", type string}, {"$RECEIPT_NUMBER", type string}, {"$UNIT_PRICE", type int64}, {"$ITEM_NUMBER", type string}, {"$DATE_RECEIVED_AT_SITE", type datetime}, {"$RECEIPT_CODE", type string}, {"$DATE_STATUS_EFFECTIVE", type datetime}, {"$HOLD_STATUS", type string}, {"$DSR_NUMBER", type string}, {"$QTY_IN_HOLD", type int64}, {"$RECORD_STATUS", type string}, {"$STOP", type string}, {"$ITT_KEY_NO", type string}, {"$SITE_NUMBER", type string}, {"$PO_NUMBER", type string}, {"$CHANGE_ORDER_NUMBER", type string}, {"$RELEASE_NUMBER", type string}, {"$PO_LINE_NUMBER", type string}, {"$DATE_ENTERED", type datetime}, {"$TIME_ENTERED", type string}, {"$QTY_RECEIVED", type int64}, {"$QTY_REJECTED", type int64}, {"$QA_CODE", type string}, {"$SHELF_LIFE", type string}, {"$QA_INSPECTOR", type string}, {"$STOREKEEPER_ID", type string}, {"$RECEIPT_NUMBER", type string}, {"$UNIT_PRICE", type int64}, {"$ITEM_NUMBER", type string}, {"$DATE_RECEIVED_AT_SITE", type datetime}, {"$RECEIPT_CODE", type string}, {"$DATE_STATUS_EFFECTIVE", type datetime}, {"$HOLD_STATUS", type string}, {"$DSR_NUMBER", type string}, {"$QTY_IN_HOLD", type int64}, {"$RECORD_STATUS", type string}, {"$STOP", type string}, {"$ITT_KEY_NO", type string} } ),
					// Handle nulls appropriately
HandleNulls = Table.ReplaceValue( TransformTypes, null, "", Replacer.ReplaceValue, Table.ColumnNames(TransformTypes) )
				in
					HandleNulls
        



    annotation PBI_ResultType = Table