table PURCHASE_ORDER_LINE


    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'CHANGE_ORDER_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: CHANGE_ORDER_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'RELEASE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: RELEASE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_LINE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_LINE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'STATUS_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: STATUS_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: int64
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'BU_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: BU_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'JOB_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: JOB_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_MEASURE'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_OF_MEASURE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PROMISED_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: PROMISED_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_REJECTED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_REJECTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_IN_INVENT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_IN_INVENT

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_RECD_SITE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_RECD_SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_IN_HOLD'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_IN_HOLD

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ENTERED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ORDERED'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_ORDERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_RECD_TO_DATE'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_RECD_TO_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ON_HOLD'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_ON_HOLD

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_INSPECTOR'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_INSPECTOR

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_LEVEL'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_LEVEL

        

        annotation SummarizationSetBy = Automatic

        
    column 'REQUISITION'
        dataType: string
        summarizeBy: none
        sourceColumn: REQUISITION

        

        annotation SummarizationSetBy = Automatic

        
    column 'VENDOR_NAME'
        dataType: string
        summarizeBy: none
        sourceColumn: VENDOR_NAME

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_CLASS'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_CLASS

        

        annotation SummarizationSetBy = Automatic

        
    column 'BLANKET_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: BLANKET_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'BLANKET_BEGIN_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: BLANKET_BEGIN_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'BLANKET_END_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: BLANKET_END_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ROOT_ENTERED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_ROOT_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ROOT_ORDERED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_ROOT_ORDERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ROOT_STATUS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_ROOT_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'DOLLARS_COMMITTED'
        dataType: int64
        summarizeBy: none
        sourceColumn: DOLLARS_COMMITTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'MAX_DOLLARS'
        dataType: int64
        summarizeBy: none
        sourceColumn: MAX_DOLLARS

        

        annotation SummarizationSetBy = Automatic

        
    column 'LAST_BLANKET_RELEASE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: LAST_BLANKET_RELEASE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_ROOT_STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_ROOT_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'REVISION_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: REVISION_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'SERVICE'
        dataType: string
        summarizeBy: none
        sourceColumn: SERVICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DOLLARS_RECEIVED'
        dataType: int64
        summarizeBy: none
        sourceColumn: DOLLARS_RECEIVED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DSR_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: DSR_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'DSR_HOLD_STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: DSR_HOLD_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'PROMISE_DATE_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: PROMISE_DATE_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'PRICE_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: PRICE_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PROCUREMENT_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: PROCUREMENT_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_REJECTED_TO_DATE'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_REJECTED_TO_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'REQUESTOR_NAME'
        dataType: string
        summarizeBy: none
        sourceColumn: REQUESTOR_NAME

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_PURCHASE'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_OF_PURCHASE

        

        annotation SummarizationSetBy = Automatic

        
    column 'CONVERSION_FACTOR'
        dataType: int64
        summarizeBy: none
        sourceColumn: CONVERSION_FACTOR

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        

    measure 'PURCHASE_ORDER_LINE - Count by BLANKET_BEGIN_DATE' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[BLANKET_BEGIN_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by BLANKET_END_DATE' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[BLANKET_END_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by DATE_ENTERED' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[DATE_ENTERED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by DATE_LAST_IN_HOLD' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[DATE_LAST_IN_HOLD])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by DATE_LAST_IN_INVENT' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[DATE_LAST_IN_INVENT])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by DATE_LAST_RECD_SITE' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[DATE_LAST_RECD_SITE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by DATE_LAST_REJECTED' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[DATE_LAST_REJECTED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by DATE_ROOT_ENTERED' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[DATE_ROOT_ENTERED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by DATE_ROOT_ORDERED' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[DATE_ROOT_ORDERED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by DATE_ROOT_STATUS' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[DATE_ROOT_STATUS])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by PROMISED_DATE' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[PROMISED_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by STATUS_DATE' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[STATUS_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'PURCHASE_ORDER_LINE' = m
        mode: import
        source = 
            	let
					Source = Sql.Database(#"DB Server", #"DB Name"),
					// Validate connection
ValidateConnection = try Source otherwise error 
"Failed to connect to database. Error: " & Text.From([Error][Message]),
					// Execute query with folding
ExecuteQuery = Value.NativeQuery(
ValidateConnection, 
"Select",
null,
[EnableFolding=true]
),
					// Validate results
ValidateResults = if Table.IsEmpty(ExecuteQuery) then error "No data returned from query for table PURCHASE_ORDER_LINE" else ExecuteQuery,
					// Apply data type transformations
TransformTypes = Table.TransformColumnTypes( ValidateResults, { {"$SITE_NUMBER", type string}, {"$PO_NUMBER", type string}, {"$CHANGE_ORDER_NUMBER", type string}, {"$RELEASE_NUMBER", type string}, {"$PO_LINE_NUMBER", type string}, {"$STATUS", type string}, {"$STATUS_DATE", type datetime}, {"$ITEM_NUMBER", type string}, {"$UNIT_PRICE", type int64}, {"$BU_NUMBER", type string}, {"$JOB_NUMBER", type string}, {"$UNIT_OF_MEASURE", type string}, {"$PROMISED_DATE", type datetime}, {"$DATE_LAST_REJECTED", type datetime}, {"$DATE_LAST_IN_INVENT", type datetime}, {"$DATE_LAST_RECD_SITE", type datetime}, {"$DATE_LAST_IN_HOLD", type datetime}, {"$DATE_ENTERED", type datetime}, {"$QTY_ORDERED", type int64}, {"$QTY_RECD_TO_DATE", type int64}, {"$QTY_ON_HOLD", type int64}, {"$QA_CODE", type string}, {"$QA_INSPECTOR", type string}, {"$QA_LEVEL", type string}, {"$REQUISITION", type string}, {"$VENDOR_NAME", type string}, {"$PO_TYPE", type string}, {"$PO_CLASS", type string}, {"$BLANKET_TYPE", type string}, {"$BLANKET_BEGIN_DATE", type datetime}, {"$BLANKET_END_DATE", type datetime}, {"$DATE_ROOT_ENTERED", type datetime}, {"$DATE_ROOT_ORDERED", type datetime}, {"$DATE_ROOT_STATUS", type datetime}, {"$DOLLARS_COMMITTED", type int64}, {"$MAX_DOLLARS", type int64}, {"$LAST_BLANKET_RELEASE_NUMBER", type string}, {"$PO_ROOT_STATUS", type string}, {"$REVISION_NUMBER", type string}, {"$SERVICE", type string}, {"$DOLLARS_RECEIVED", type int64}, {"$DSR_NUMBER", type string}, {"$DSR_HOLD_STATUS", type string}, {"$PROMISE_DATE_IND", type string}, {"$PRICE_CODE", type string}, {"$PROCUREMENT_CODE", type string}, {"$QTY_REJECTED_TO_DATE", type int64}, {"$REQUESTOR_NAME", type string}, {"$UNIT_OF_PURCHASE", type string}, {"$CONVERSION_FACTOR", type int64}, {"$STOP", type string}, {"$SITE_NUMBER", type string}, {"$PO_NUMBER", type string}, {"$CHANGE_ORDER_NUMBER", type string}, {"$RELEASE_NUMBER", type string}, {"$PO_LINE_NUMBER", type string}, {"$STATUS", type string}, {"$STATUS_DATE", type datetime}, {"$ITEM_NUMBER", type string}, {"$UNIT_PRICE", type int64}, {"$BU_NUMBER", type string}, {"$JOB_NUMBER", type string}, {"$UNIT_OF_MEASURE", type string}, {"$PROMISED_DATE", type datetime}, {"$DATE_LAST_REJECTED", type datetime}, {"$DATE_LAST_IN_INVENT", type datetime}, {"$DATE_LAST_RECD_SITE", type datetime}, {"$DATE_LAST_IN_HOLD", type datetime}, {"$DATE_ENTERED", type datetime}, {"$QTY_ORDERED", type int64}, {"$QTY_RECD_TO_DATE", type int64}, {"$QTY_ON_HOLD", type int64}, {"$QA_CODE", type string}, {"$QA_INSPECTOR", type string}, {"$QA_LEVEL", type string}, {"$REQUISITION", type string}, {"$VENDOR_NAME", type string}, {"$PO_TYPE", type string}, {"$PO_CLASS", type string}, {"$BLANKET_TYPE", type string}, {"$BLANKET_BEGIN_DATE", type datetime}, {"$BLANKET_END_DATE", type datetime}, {"$DATE_ROOT_ENTERED", type datetime}, {"$DATE_ROOT_ORDERED", type datetime}, {"$DATE_ROOT_STATUS", type datetime}, {"$DOLLARS_COMMITTED", type int64}, {"$MAX_DOLLARS", type int64}, {"$LAST_BLANKET_RELEASE_NUMBER", type string}, {"$PO_ROOT_STATUS", type string}, {"$REVISION_NUMBER", type string}, {"$SERVICE", type string}, {"$DOLLARS_RECEIVED", type int64}, {"$DSR_NUMBER", type string}, {"$DSR_HOLD_STATUS", type string}, {"$PROMISE_DATE_IND", type string}, {"$PRICE_CODE", type string}, {"$PROCUREMENT_CODE", type string}, {"$QTY_REJECTED_TO_DATE", type int64}, {"$REQUESTOR_NAME", type string}, {"$UNIT_OF_PURCHASE", type string}, {"$CONVERSION_FACTOR", type int64}, {"$STOP", type string} } ),
					// Handle nulls appropriately
HandleNulls = Table.ReplaceValue( TransformTypes, null, "", Replacer.ReplaceValue, Table.ColumnNames(TransformTypes) )
				in
					HandleNulls
        



    annotation PBI_ResultType = Table