table PURCHASE_ORDER_LINE


    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'CHANGE_ORDER_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: CHANGE_ORDER_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'RELEASE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: RELEASE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_LINE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_LINE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'STATUS_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: STATUS_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: int64
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'BU_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: BU_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'JOB_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: JOB_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_MEASURE'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_OF_MEASURE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PROMISED_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: PROMISED_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_REJECTED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_REJECTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_IN_INVENT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_IN_INVENT

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_RECD_SITE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_RECD_SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_IN_HOLD'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_IN_HOLD

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ENTERED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ORDERED'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_ORDERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_RECD_TO_DATE'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_RECD_TO_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ON_HOLD'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_ON_HOLD

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_INSPECTOR'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_INSPECTOR

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_LEVEL'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_LEVEL

        

        annotation SummarizationSetBy = Automatic

        
    column 'REQUISITION'
        dataType: string
        summarizeBy: none
        sourceColumn: REQUISITION

        

        annotation SummarizationSetBy = Automatic

        
    column 'VENDOR_NAME'
        dataType: string
        summarizeBy: none
        sourceColumn: VENDOR_NAME

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_CLASS'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_CLASS

        

        annotation SummarizationSetBy = Automatic

        
    column 'BLANKET_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: BLANKET_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'BLANKET_BEGIN_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: BLANKET_BEGIN_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'BLANKET_END_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: BLANKET_END_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ROOT_ENTERED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_ROOT_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ROOT_ORDERED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_ROOT_ORDERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ROOT_STATUS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_ROOT_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'DOLLARS_COMMITTED'
        dataType: int64
        summarizeBy: none
        sourceColumn: DOLLARS_COMMITTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'MAX_DOLLARS'
        dataType: int64
        summarizeBy: none
        sourceColumn: MAX_DOLLARS

        

        annotation SummarizationSetBy = Automatic

        
    column 'LAST_BLANKET_RELEASE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: LAST_BLANKET_RELEASE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_ROOT_STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_ROOT_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'REVISION_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: REVISION_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'SERVICE'
        dataType: string
        summarizeBy: none
        sourceColumn: SERVICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DOLLARS_RECEIVED'
        dataType: int64
        summarizeBy: none
        sourceColumn: DOLLARS_RECEIVED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DSR_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: DSR_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'DSR_HOLD_STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: DSR_HOLD_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'PROMISE_DATE_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: PROMISE_DATE_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'PRICE_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: PRICE_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PROCUREMENT_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: PROCUREMENT_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_REJECTED_TO_DATE'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_REJECTED_TO_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'REQUESTOR_NAME'
        dataType: string
        summarizeBy: none
        sourceColumn: REQUESTOR_NAME

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_PURCHASE'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_OF_PURCHASE

        

        annotation SummarizationSetBy = Automatic

        
    column 'CONVERSION_FACTOR'
        dataType: int64
        summarizeBy: none
        sourceColumn: CONVERSION_FACTOR

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        

    measure 'PURCHASE_ORDER_LINE - Count by BLANKET_BEGIN_DATE' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[BLANKET_BEGIN_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by BLANKET_END_DATE' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[BLANKET_END_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by DATE_ENTERED' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[DATE_ENTERED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by DATE_LAST_IN_HOLD' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[DATE_LAST_IN_HOLD])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by DATE_LAST_IN_INVENT' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[DATE_LAST_IN_INVENT])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by DATE_LAST_RECD_SITE' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[DATE_LAST_RECD_SITE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by DATE_LAST_REJECTED' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[DATE_LAST_REJECTED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by DATE_ROOT_ENTERED' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[DATE_ROOT_ENTERED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by DATE_ROOT_ORDERED' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[DATE_ROOT_ORDERED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by DATE_ROOT_STATUS' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[DATE_ROOT_STATUS])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by PROMISED_DATE' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[PROMISED_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'PURCHASE_ORDER_LINE - Count by STATUS_DATE' = ```
            CALCULATE(
    COUNTROWS('PURCHASE_ORDER_LINE'),
    USERELATIONSHIP('CentralDateTable'[Date], 'PURCHASE_ORDER_LINE'[STATUS_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'PURCHASE_ORDER_LINE' = m
        mode: import
        source = 
            let
    // --- 1. DEFINE THE SQL QUERY ---
    SQL_Statement = "SELECT * FROM PURCHASE_ORDER_LINE",

    // --- 2. CONNECT TO THE DATABASE ---
    Source = Sql.Database(#"DB Server", #"DB Name"),

    // --- 3. EXECUTE THE NATIVE SQL QUERY ---
    ExecuteQuery = Value.NativeQuery(
        Source,
        SQL_Statement,
        null,
        [EnableFolding=true]
    ),

    // --- 4. VALIDATE THAT DATA WAS RETURNED ---
    ValidateResults = if Table.IsEmpty(ExecuteQuery) then
                        error "No data was returned from the SQL query for the PURCHASE_ORDER_LINE table."
                      else
                        ExecuteQuery
in
    ValidateResults
        



    annotation PBI_ResultType = Table