table REQUISITION_DESCRIPTIONS


    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'REQUISITION'
        dataType: string
        summarizeBy: none
        sourceColumn: REQUISITION

        

        annotation SummarizationSetBy = Automatic

        
    column 'TOTAL_NUMBER_SEGMENTS'
        dataType: int64
        summarizeBy: none
        sourceColumn: TOTAL_NUMBER_SEGMENTS

        

        annotation SummarizationSetBy = Automatic

        
    column 'NUMBER_SEGMENTS_SELECTED'
        dataType: int64
        summarizeBy: none
        sourceColumn: NUMBER_SEGMENTS_SELECTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'SEGMENT_NUMBER1'
        dataType: string
        summarizeBy: none
        sourceColumn: SEGMENT_NUMBER1

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION1'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION1

        

        annotation SummarizationSetBy = Automatic

        
    column 'SEGMENT_NUMBER2'
        dataType: string
        summarizeBy: none
        sourceColumn: SEGMENT_NUMBER2

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION2'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION2

        

        annotation SummarizationSetBy = Automatic

        
    column 'SEGMENT_NUMBER3'
        dataType: string
        summarizeBy: none
        sourceColumn: SEGMENT_NUMBER3

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION3'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION3

        

        annotation SummarizationSetBy = Automatic

        
    column 'SEGMENT_NUMBER4'
        dataType: string
        summarizeBy: none
        sourceColumn: SEGMENT_NUMBER4

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION4'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION4

        

        annotation SummarizationSetBy = Automatic

        
    column 'SEGMENT_NUMBER5'
        dataType: string
        summarizeBy: none
        sourceColumn: SEGMENT_NUMBER5

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION5'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION5

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        



    partition 'REQUISITION_DESCRIPTIONS' = m
        mode: import
        source = 
            	let
					Source = Sql.Database(#"DB Server", #"DB Name"),
					// Validate connection
ValidateConnection = try Source otherwise error 
"Failed to connect to database. Error: " & Text.From([Error][Message]),
					// Execute query with folding
ExecuteQuery = Value.NativeQuery(
ValidateConnection, 
"Select",
null,
[EnableFolding=true]
),
					// Validate results
ValidateResults = if Table.IsEmpty(ExecuteQuery) then error "No data returned from query for table REQUISITION_DESCRIPTIONS" else ExecuteQuery,
					// Apply data type transformations
TransformTypes = Table.TransformColumnTypes( ValidateResults, { {"$ITEM_NUMBER", type string}, {"$SITE_NUMBER", type string}, {"$REQUISITION", type string}, {"$TOTAL_NUMBER_SEGMENTS", type int64}, {"$NUMBER_SEGMENTS_SELECTED", type int64}, {"$SEGMENT_NUMBER1", type string}, {"$DESCRIPTION1", type string}, {"$SEGMENT_NUMBER2", type string}, {"$DESCRIPTION2", type string}, {"$SEGMENT_NUMBER3", type string}, {"$DESCRIPTION3", type string}, {"$SEGMENT_NUMBER4", type string}, {"$DESCRIPTION4", type string}, {"$SEGMENT_NUMBER5", type string}, {"$DESCRIPTION5", type string}, {"$STOP", type string}, {"$ITEM_NUMBER", type string}, {"$SITE_NUMBER", type string}, {"$REQUISITION", type string}, {"$TOTAL_NUMBER_SEGMENTS", type int64}, {"$NUMBER_SEGMENTS_SELECTED", type int64}, {"$SEGMENT_NUMBER1", type string}, {"$DESCRIPTION1", type string}, {"$SEGMENT_NUMBER2", type string}, {"$DESCRIPTION2", type string}, {"$SEGMENT_NUMBER3", type string}, {"$DESCRIPTION3", type string}, {"$SEGMENT_NUMBER4", type string}, {"$DESCRIPTION4", type string}, {"$SEGMENT_NUMBER5", type string}, {"$DESCRIPTION5", type string}, {"$STOP", type string} } ),
					// Handle nulls appropriately
HandleNulls = Table.ReplaceValue( TransformTypes, null, "", Replacer.ReplaceValue, Table.ColumnNames(TransformTypes) )
				in
					HandleNulls
        



    annotation PBI_ResultType = Table