table STORAGE_LOCATION


    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'SEGMENTS'
        dataType: int64
        summarizeBy: none
        sourceColumn: SEGMENTS

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION1'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION1

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_1'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_1

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION2'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION2

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_2'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_2

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION3'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION3

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_3'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_3

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION4'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION4

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_4'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_4

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION5'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION5

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_5'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_5

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION6'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION6

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_6'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_6

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION7'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION7

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_7'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_7

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION8'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION8

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_8'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_8

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION9'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION9

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_9'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_9

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION10'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION10

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_10'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_10

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        



    partition 'STORAGE_LOCATION' = m
        mode: import
        source = 
            	let
					Source = Sql.Database(#"DB Server", #"DB Name"),
					// Validate connection
ValidateConnection = try Source otherwise error 
"Failed to connect to database. Error: " & Text.From([Error][Message]),
					// Execute query with folding
ExecuteQuery = Value.NativeQuery(
ValidateConnection, 
"Select",
null,
[EnableFolding=true]
),
					// Validate results
ValidateResults = if Table.IsEmpty(ExecuteQuery) then error "No data returned from query for table STORAGE_LOCATION" else ExecuteQuery,
					// Apply data type transformations
TransformTypes = Table.TransformColumnTypes( ValidateResults, { {"$ITEM_NUMBER", type string}, {"$SITE_NUMBER", type string}, {"$SEGMENTS", type int64}, {"$LOCATION1", type string}, {"$LOC_NUMBER_1", type string}, {"$LOCATION2", type string}, {"$LOC_NUMBER_2", type string}, {"$LOCATION3", type string}, {"$LOC_NUMBER_3", type string}, {"$LOCATION4", type string}, {"$LOC_NUMBER_4", type string}, {"$LOCATION5", type string}, {"$LOC_NUMBER_5", type string}, {"$LOCATION6", type string}, {"$LOC_NUMBER_6", type string}, {"$LOCATION7", type string}, {"$LOC_NUMBER_7", type string}, {"$LOCATION8", type string}, {"$LOC_NUMBER_8", type string}, {"$LOCATION9", type string}, {"$LOC_NUMBER_9", type string}, {"$LOCATION10", type string}, {"$LOC_NUMBER_10", type string}, {"$STOP", type string}, {"$ITEM_NUMBER", type string}, {"$SITE_NUMBER", type string}, {"$SEGMENTS", type int64}, {"$LOCATION1", type string}, {"$LOC_NUMBER_1", type string}, {"$LOCATION2", type string}, {"$LOC_NUMBER_2", type string}, {"$LOCATION3", type string}, {"$LOC_NUMBER_3", type string}, {"$LOCATION4", type string}, {"$LOC_NUMBER_4", type string}, {"$LOCATION5", type string}, {"$LOC_NUMBER_5", type string}, {"$LOCATION6", type string}, {"$LOC_NUMBER_6", type string}, {"$LOCATION7", type string}, {"$LOC_NUMBER_7", type string}, {"$LOCATION8", type string}, {"$LOC_NUMBER_8", type string}, {"$LOCATION9", type string}, {"$LOC_NUMBER_9", type string}, {"$LOCATION10", type string}, {"$LOC_NUMBER_10", type string}, {"$STOP", type string} } ),
					// Handle nulls appropriately
HandleNulls = Table.ReplaceValue( TransformTypes, null, "", Replacer.ReplaceValue, Table.ColumnNames(TransformTypes) )
				in
					HandleNulls
        



    annotation PBI_ResultType = Table