table WO_DOCUMENTS


    column 'SITE'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'WORKORDER'
        dataType: string
        summarizeBy: none
        sourceColumn: WORKORDER

        

        annotation SummarizationSetBy = Automatic

        
    column 'REC_TYP'
        dataType: string
        summarizeBy: none
        sourceColumn: REC_TYP

        

        annotation SummarizationSetBy = Automatic

        
    column 'TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DOCUMENT_NUM'
        dataType: string
        summarizeBy: none
        sourceColumn: DOCUMENT_NUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'CLASS'
        dataType: string
        summarizeBy: none
        sourceColumn: CLASS

        

        annotation SummarizationSetBy = Automatic

        
    column 'SHEET'
        dataType: string
        summarizeBy: none
        sourceColumn: SHEET

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION

        

        annotation SummarizationSetBy = Automatic

        
    column 'MODEL_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: MODEL_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'MARK_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: MARK_NUMBER

        

        annotation SummarizationSetBy = Automatic

        



    partition 'WO_DOCUMENTS' = m
        mode: import
        source = 
            	let
					Source = Sql.Database(#"DB Server", #"DB Name"),
					// Validate connection
ValidateConnection = try Source otherwise error 
"Failed to connect to database. Error: " & Text.From([Error][Message]),
					// Execute query with folding
ExecuteQuery = Value.NativeQuery(
ValidateConnection, 
"Select",
null,
[EnableFolding=true]
),
					// Validate results
ValidateResults = if Table.IsEmpty(ExecuteQuery) then error "No data returned from query for table WO_DOCUMENTS" else ExecuteQuery,
					// Apply data type transformations
TransformTypes = Table.TransformColumnTypes( ValidateResults, { {"$SITE", type string}, {"$WORKORDER", type string}, {"$REC_TYP", type string}, {"$TYPE", type string}, {"$DOCUMENT_NUM", type string}, {"$CLASS", type string}, {"$SHEET", type string}, {"$LOCATION", type string}, {"$MODEL_TYPE", type string}, {"$MARK_NUMBER", type string}, {"$SITE", type string}, {"$WORKORDER", type string}, {"$REC_TYP", type string}, {"$TYPE", type string}, {"$DOCUMENT_NUM", type string}, {"$CLASS", type string}, {"$SHEET", type string}, {"$LOCATION", type string}, {"$MODEL_TYPE", type string}, {"$MARK_NUMBER", type string} } ),
					// Handle nulls appropriately
HandleNulls = Table.ReplaceValue( TransformTypes, null, "", Replacer.ReplaceValue, Table.ColumnNames(TransformTypes) )
				in
					HandleNulls
        



    annotation PBI_ResultType = Table