table WO_MATERIALS


    column 'SITE'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'WORKORDER'
        dataType: string
        summarizeBy: none
        sourceColumn: WORKORDER

        

        annotation SummarizationSetBy = Automatic

        
    column 'REC_TYP'
        dataType: string
        summarizeBy: none
        sourceColumn: REC_TYP

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUM'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NUM'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_NUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'SERIAL_NUM'
        dataType: string
        summarizeBy: none
        sourceColumn: SERIAL_NUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'MODEL_NUM'
        dataType: string
        summarizeBy: none
        sourceColumn: MODEL_NUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_MEAS'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_MEAS

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY'
        dataType: string
        summarizeBy: none
        sourceColumn: QTY

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION

        

        annotation SummarizationSetBy = Automatic

        
    column 'MODEL_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: MODEL_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'MARK_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: MARK_NUMBER

        

        annotation SummarizationSetBy = Automatic

        



    partition 'WO_MATERIALS' = m
        mode: import
        source = 
            	let
					Source = Sql.Database(#"DB Server", #"DB Name"),
					// Validate connection
ValidateConnection = try Source otherwise error 
"Failed to connect to database. Error: " & Text.From([Error][Message]),
					// Execute query with folding
ExecuteQuery = Value.NativeQuery(
ValidateConnection, 
"Select",
null,
[EnableFolding=true]
),
					// Validate results
ValidateResults = if Table.IsEmpty(ExecuteQuery) then error "No data returned from query for table WO_MATERIALS" else ExecuteQuery,
					// Apply data type transformations
TransformTypes = Table.TransformColumnTypes( ValidateResults, { {"$SITE", type string}, {"$WORKORDER", type string}, {"$REC_TYP", type string}, {"$ITEM_NUM", type string}, {"$PO_NUM", type string}, {"$SERIAL_NUM", type string}, {"$MODEL_NUM", type string}, {"$UNIT_MEAS", type string}, {"$QTY", type string}, {"$DESCRIPTION", type string}, {"$MODEL_TYPE", type string}, {"$MARK_NUMBER", type string}, {"$SITE", type string}, {"$WORKORDER", type string}, {"$REC_TYP", type string}, {"$ITEM_NUM", type string}, {"$PO_NUM", type string}, {"$SERIAL_NUM", type string}, {"$MODEL_NUM", type string}, {"$UNIT_MEAS", type string}, {"$QTY", type string}, {"$DESCRIPTION", type string}, {"$MODEL_TYPE", type string}, {"$MARK_NUMBER", type string} } ),
					// Handle nulls appropriately
HandleNulls = Table.ReplaceValue( TransformTypes, null, "", Replacer.ReplaceValue, Table.ColumnNames(TransformTypes) )
				in
					HandleNulls
        



    annotation PBI_ResultType = Table