table WO_SERVICES


    column 'SITE'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'WORKORDER'
        dataType: string
        summarizeBy: none
        sourceColumn: WORKORDER

        

        annotation SummarizationSetBy = Automatic

        
    column 'REC_TYP'
        dataType: string
        summarizeBy: none
        sourceColumn: REC_TYP

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_CONTRACT'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_CONTRACT

        

        annotation SummarizationSetBy = Automatic

        
    column 'COST'
        dataType: string
        summarizeBy: none
        sourceColumn: COST

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION

        

        annotation SummarizationSetBy = Automatic

        



    partition 'WO_SERVICES' = m
        mode: import
        source = 
            	let
					Source = Sql.Database(#"DB Server", #"DB Name"),
					// Validate connection
ValidateConnection = try Source otherwise error 
"Failed to connect to database. Error: " & Text.From([Error][Message]),
					// Execute query with folding
ExecuteQuery = Value.NativeQuery(
ValidateConnection, 
"Select",
null,
[EnableFolding=true]
),
					// Validate results
ValidateResults = if Table.IsEmpty(ExecuteQuery) then error "No data returned from query for table WO_SERVICES" else ExecuteQuery,
					// Apply data type transformations
TransformTypes = Table.TransformColumnTypes( ValidateResults, { {"$SITE", type string}, {"$WORKORDER", type string}, {"$REC_TYP", type string}, {"$PO_CONTRACT", type string}, {"$COST", type string}, {"$DESCRIPTION", type string}, {"$SITE", type string}, {"$WORKORDER", type string}, {"$REC_TYP", type string}, {"$PO_CONTRACT", type string}, {"$COST", type string}, {"$DESCRIPTION", type string} } ),
					// Handle nulls appropriately
HandleNulls = Table.ReplaceValue( TransformTypes, null, "", Replacer.ReplaceValue, Table.ColumnNames(TransformTypes) )
				in
					HandleNulls
        



    annotation PBI_ResultType = Table