table WO_STEPS


    column 'SITE'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'WORKORDER'
        dataType: string
        summarizeBy: none
        sourceColumn: WORKORDER

        

        annotation SummarizationSetBy = Automatic

        
    column 'REC_TYP'
        dataType: string
        summarizeBy: none
        sourceColumn: REC_TYP

        

        annotation SummarizationSetBy = Automatic

        
    column 'STEP'
        dataType: string
        summarizeBy: none
        sourceColumn: STEP

        

        annotation SummarizationSetBy = Automatic

        
    column 'DURATION'
        dataType: string
        summarizeBy: none
        sourceColumn: DURATION

        

        annotation SummarizationSetBy = Automatic

        
    column 'CRAFT'
        dataType: string
        summarizeBy: none
        sourceColumn: CRAFT

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY'
        dataType: string
        summarizeBy: none
        sourceColumn: QTY

        

        annotation SummarizationSetBy = Automatic

        
    column 'MAN_HOURS'
        dataType: string
        summarizeBy: none
        sourceColumn: MAN_HOURS

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION

        

        annotation SummarizationSetBy = Automatic

        
    column 'MODEL_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: MODEL_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'MARK_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: MARK_NUMBER

        

        annotation SummarizationSetBy = Automatic

        



    partition 'WO_STEPS' = m
        mode: import
        source = 
            	let
					Source = Sql.Database(#"DB Server", #"DB Name"),
					// Validate connection
ValidateConnection = try Source otherwise error 
"Failed to connect to database. Error: " & Text.From([Error][Message]),
					// Execute query with folding
ExecuteQuery = Value.NativeQuery(
ValidateConnection, 
"Select",
null,
[EnableFolding=true]
),
					// Validate results
ValidateResults = if Table.IsEmpty(ExecuteQuery) then error "No data returned from query for table WO_STEPS" else ExecuteQuery,
					// Apply data type transformations
TransformTypes = Table.TransformColumnTypes( ValidateResults, { {"$SITE", type string}, {"$WORKORDER", type string}, {"$REC_TYP", type string}, {"$STEP", type string}, {"$DURATION", type string}, {"$CRAFT", type string}, {"$QTY", type string}, {"$MAN_HOURS", type string}, {"$DESCRIPTION", type string}, {"$MODEL_TYPE", type string}, {"$MARK_NUMBER", type string}, {"$SITE", type string}, {"$WORKORDER", type string}, {"$REC_TYP", type string}, {"$STEP", type string}, {"$DURATION", type string}, {"$CRAFT", type string}, {"$QTY", type string}, {"$MAN_HOURS", type string}, {"$DESCRIPTION", type string}, {"$MODEL_TYPE", type string}, {"$MARK_NUMBER", type string} } ),
					// Handle nulls appropriately
HandleNulls = Table.ReplaceValue( TransformTypes, null, "", Replacer.ReplaceValue, Table.ColumnNames(TransformTypes) )
				in
					HandleNulls
        



    annotation PBI_ResultType = Table