table WO_SUPPLEMENTAL


    column 'SITE'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'WORKORDER'
        dataType: string
        summarizeBy: none
        sourceColumn: WORKORDER

        

        annotation SummarizationSetBy = Automatic

        
    column 'REC_TYP'
        dataType: string
        summarizeBy: none
        sourceColumn: REC_TYP

        

        annotation SummarizationSetBy = Automatic

        
    column 'SUMMARY'
        dataType: string
        summarizeBy: none
        sourceColumn: SUMMARY

        

        annotation SummarizationSetBy = Automatic

        



    partition 'WO_SUPPLEMENTAL' = m
        mode: import
        source = 
            	let
					Source = Sql.Database(#"DB Server", #"DB Name"),
					// Validate connection
ValidateConnection = try Source otherwise error 
"Failed to connect to database. Error: " & Text.From([Error][Message]),
					// Execute query with folding
ExecuteQuery = Value.NativeQuery(
ValidateConnection, 
"Select",
null,
[EnableFolding=true]
),
					// Validate results
ValidateResults = if Table.IsEmpty(ExecuteQuery) then error "No data returned from query for table WO_SUPPLEMENTAL" else ExecuteQuery,
					// Apply data type transformations
TransformTypes = Table.TransformColumnTypes( ValidateResults, { {"$SITE", type string}, {"$WORKORDER", type string}, {"$REC_TYP", type string}, {"$SUMMARY", type string}, {"$SITE", type string}, {"$WORKORDER", type string}, {"$REC_TYP", type string}, {"$SUMMARY", type string} } ),
					// Handle nulls appropriately
HandleNulls = Table.ReplaceValue( TransformTypes, null, "", Replacer.ReplaceValue, Table.ColumnNames(TransformTypes) )
				in
					HandleNulls
        



    annotation PBI_ResultType = Table