table C_ITEM_SITE_EXTRACT_PURCHASE_ORDER_LINE


    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_MEASURE'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_OF_MEASURE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_CREATED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_CREATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'TAX_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: TAX_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: int64
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TYPE_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: TYPE_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'FUNCTIONAL_GROUP'
        dataType: string
        summarizeBy: none
        sourceColumn: FUNCTIONAL_GROUP

        

        annotation SummarizationSetBy = Automatic

        
    column 'MATERIAL_CLASS'
        dataType: string
        summarizeBy: none
        sourceColumn: MATERIAL_CLASS

        

        annotation SummarizationSetBy = Automatic

        
    column 'STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_RANK'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_RANK

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_INVENTORIED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_INVENTORIED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ON_ORDER'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_ON_ORDER

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ON_HAND'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_ON_HAND

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_AVAILABLE'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_AVAILABLE

        

        annotation SummarizationSetBy = Automatic

        
    column 'MINIMUM'
        dataType: int64
        summarizeBy: none
        sourceColumn: MINIMUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'MAXIMUM'
        dataType: int64
        summarizeBy: none
        sourceColumn: MAXIMUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'EOQ_QTY'
        dataType: int64
        summarizeBy: none
        sourceColumn: EOQ_QTY

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_LEVEL'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_LEVEL

        

        annotation SummarizationSetBy = Automatic

        
    column 'CYCLE_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: CYCLE_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'SHELF_LIFE_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: SHELF_LIFE_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_RECEIVED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_RECEIVED

        

        annotation SummarizationSetBy = Automatic

        
    column 'FERC_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: FERC_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PRIMARY_LOC'
        dataType: string
        summarizeBy: none
        sourceColumn: PRIMARY_LOC

        

        annotation SummarizationSetBy = Automatic

        
    column 'SECONDARY_LOC'
        dataType: string
        summarizeBy: none
        sourceColumn: SECONDARY_LOC

        

        annotation SummarizationSetBy = Automatic

        
    column 'EXTRA_LOCS'
        dataType: string
        summarizeBy: none
        sourceColumn: EXTRA_LOCS

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_APPROVED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_APPROVED

        

        annotation SummarizationSetBy = Automatic

        
    column 'APPROVER_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: APPROVER_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'APPROVER_BADGE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: APPROVER_BADGE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'APPROVAL_SWITCH'
        dataType: string
        summarizeBy: none
        sourceColumn: APPROVAL_SWITCH

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT1'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_CERT1

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT2'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_CERT2

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT3'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_CERT3

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT4'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_CERT4

        

        annotation SummarizationSetBy = Automatic

        
    column 'VALUE_ON_HAND'
        dataType: int64
        summarizeBy: none
        sourceColumn: VALUE_ON_HAND

        

        annotation SummarizationSetBy = Automatic

        
    column 'PREVIOUS_ITEM_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: PREVIOUS_ITEM_ID

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ALLOCATED'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_ALLOCATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'CONSUMABLE'
        dataType: string
        summarizeBy: none
        sourceColumn: CONSUMABLE

        

        annotation SummarizationSetBy = Automatic

        
    column 'SHELF_LIFE'
        dataType: string
        summarizeBy: none
        sourceColumn: SHELF_LIFE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PREVENT_MAINTENANCE'
        dataType: string
        summarizeBy: none
        sourceColumn: PREVENT_MAINTENANCE

        

        annotation SummarizationSetBy = Automatic

        
    column 'CORPORATE_SWITCH'
        dataType: string
        summarizeBy: none
        sourceColumn: CORPORATE_SWITCH

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_OWNER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_OWNER

        

        annotation SummarizationSetBy = Automatic

        
    column 'SAFETY_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: SAFETY_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'UTC_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: UTC_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_DEPT'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_DEPT

        

        annotation SummarizationSetBy = Automatic

        
    column 'IN_PROCESS_HOLD'
        dataType: int64
        summarizeBy: none
        sourceColumn: IN_PROCESS_HOLD

        

        annotation SummarizationSetBy = Automatic

        
    column 'PIT'
        dataType: string
        summarizeBy: none
        sourceColumn: PIT

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_EXCESS'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_EXCESS

        

        annotation SummarizationSetBy = Automatic

        
    column 'NEW_RANK'
        dataType: string
        summarizeBy: none
        sourceColumn: NEW_RANK

        

        annotation SummarizationSetBy = Automatic

        
    column 'SUB_STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: SUB_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'STRATIFIED_TRANS_COUNT'
        dataType: int64
        summarizeBy: none
        sourceColumn: STRATIFIED_TRANS_COUNT

        

        annotation SummarizationSetBy = Automatic

        
    column 'STRATIFIED_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: STRATIFIED_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TOLERANCE_AMOUNT'
        dataType: int64
        summarizeBy: none
        sourceColumn: TOLERANCE_AMOUNT

        

        annotation SummarizationSetBy = Automatic

        
    column 'TOLERANCE_PERCENTAGE'
        dataType: int64
        summarizeBy: none
        sourceColumn: TOLERANCE_PERCENTAGE

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_LAST_UPDATED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: SITE_LAST_UPDATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ON_HOLD'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_ON_HOLD

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_LAST_UPDATED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: ITEM_LAST_UPDATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_PROPERTY_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_OF_PROPERTY_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_PROPERTY_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_OF_PROPERTY_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_ISSUED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_ISSUED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_RETURNED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_RETURNED

        

        annotation SummarizationSetBy = Automatic

        
    column 'CRITICAL_ITEM'
        dataType: string
        summarizeBy: none
        sourceColumn: CRITICAL_ITEM

        

        annotation SummarizationSetBy = Automatic

        
    column 'REVIEW_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: REVIEW_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'SAP_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: SAP_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'CHANGE_ORDER_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: CHANGE_ORDER_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'RELEASE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: RELEASE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_LINE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_LINE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'STATUS_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: STATUS_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'BU_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: BU_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'JOB_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: JOB_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PROMISED_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: PROMISED_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_REJECTED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_REJECTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_IN_INVENT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_IN_INVENT

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_RECD_SITE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_RECD_SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_LAST_IN_HOLD'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_LAST_IN_HOLD

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ENTERED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_ORDERED'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_ORDERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_RECD_TO_DATE'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_RECD_TO_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_INSPECTOR'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_INSPECTOR

        

        annotation SummarizationSetBy = Automatic

        
    column 'REQUISITION'
        dataType: string
        summarizeBy: none
        sourceColumn: REQUISITION

        

        annotation SummarizationSetBy = Automatic

        
    column 'VENDOR_NAME'
        dataType: string
        summarizeBy: none
        sourceColumn: VENDOR_NAME

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_CLASS'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_CLASS

        

        annotation SummarizationSetBy = Automatic

        
    column 'BLANKET_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: BLANKET_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'BLANKET_BEGIN_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: BLANKET_BEGIN_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'BLANKET_END_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: BLANKET_END_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ROOT_ENTERED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_ROOT_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ROOT_ORDERED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_ROOT_ORDERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ROOT_STATUS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_ROOT_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'DOLLARS_COMMITTED'
        dataType: int64
        summarizeBy: none
        sourceColumn: DOLLARS_COMMITTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'MAX_DOLLARS'
        dataType: int64
        summarizeBy: none
        sourceColumn: MAX_DOLLARS

        

        annotation SummarizationSetBy = Automatic

        
    column 'LAST_BLANKET_RELEASE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: LAST_BLANKET_RELEASE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_ROOT_STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_ROOT_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'REVISION_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: REVISION_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'SERVICE'
        dataType: string
        summarizeBy: none
        sourceColumn: SERVICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DOLLARS_RECEIVED'
        dataType: int64
        summarizeBy: none
        sourceColumn: DOLLARS_RECEIVED

        

        annotation SummarizationSetBy = Automatic

        
    column 'DSR_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: DSR_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'DSR_HOLD_STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: DSR_HOLD_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'PROMISE_DATE_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: PROMISE_DATE_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'PRICE_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: PRICE_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PROCUREMENT_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: PROCUREMENT_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_REJECTED_TO_DATE'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_REJECTED_TO_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'REQUESTOR_NAME'
        dataType: string
        summarizeBy: none
        sourceColumn: REQUESTOR_NAME

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_PURCHASE'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_OF_PURCHASE

        

        annotation SummarizationSetBy = Automatic

        
    column 'CONVERSION_FACTOR'
        dataType: int64
        summarizeBy: none
        sourceColumn: CONVERSION_FACTOR

        

        annotation SummarizationSetBy = Automatic

        



    partition 'C_ITEM_SITE_EXTRACT_PURCHASE_ORDER_LINE' = m
        mode: directQuery
        source = 
            let
                Source = Table.NestedJoin(ITEM_SITE_EXTRACT, {"SITE_NUMBER", "ITEM_NUMBER"}, PURCHASE_ORDER_LINE, {"SITE_NUMBER", "ITEM_NUMBER"}, "PURCHASE_ORDER_LINE_Nested", JoinKind.RightOuter),
                #"Expanded PURCHASE_ORDER_LINE" = Table.ExpandTableColumn(Source, "PURCHASE_ORDER_LINE_Nested", {"PO_NUMBER", "CHANGE_ORDER_NUMBER", "RELEASE_NUMBER", "PO_LINE_NUMBER", "STATUS_DATE", "BU_NUMBER", "JOB_NUMBER", "PROMISED_DATE", "DATE_LAST_REJECTED", "DATE_LAST_IN_INVENT", "DATE_LAST_RECD_SITE", "DATE_LAST_IN_HOLD", "DATE_ENTERED", "QTY_ORDERED", "QTY_RECD_TO_DATE", "QA_INSPECTOR", "REQUISITION", "VENDOR_NAME", "PO_TYPE", "PO_CLASS", "BLANKET_TYPE", "BLANKET_BEGIN_DATE", "BLANKET_END_DATE", "DATE_ROOT_ENTERED", "DATE_ROOT_ORDERED", "DATE_ROOT_STATUS", "DOLLARS_COMMITTED", "MAX_DOLLARS", "LAST_BLANKET_RELEASE_NUMBER", "PO_ROOT_STATUS", "REVISION_NUMBER", "SERVICE", "DOLLARS_RECEIVED", "DSR_NUMBER", "DSR_HOLD_STATUS", "PROMISE_DATE_IND", "PRICE_CODE", "PROCUREMENT_CODE", "QTY_REJECTED_TO_DATE", "REQUESTOR_NAME", "UNIT_OF_PURCHASE", "CONVERSION_FACTOR"})
            in
                #"Expanded PURCHASE_ORDER_LINE"
        



    annotation PBI_ResultType = Table