table MATERIAL_CHARGES


    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'CHARGED_DATE'
        dataType: string
        summarizeBy: none
        sourceColumn: CHARGED_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TRANSACTION_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: TRANSACTION_TYPE

        

        annotation SummarizationSetBy = Automatic

        



    partition 'MATERIAL_CHARGES' = m
        mode: import
        source = 
            
let
    Source = Excel.Workbook(File.Contents("C:\Users\PowerBIUser\Documents\sample_data.xlsx"), null, true),
    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SITE_NUMBER", type text}, {"ITEM_NUMBER", type text}, {"CHARGED_DATE", type text}, {"TRANSACTION_TYPE", type text}})
in
    #"Changed Type"

        



    annotation PBI_ResultType = Table