table PURCHASE_ORDER_RECEIPT


    column 'DATE_ENTERED'
        dataType: string
        summarizeBy: none
        sourceColumn: DATE_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_LINE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_LINE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'RELEASE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: RELEASE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_RECEIVED_AT_SITE'
        dataType: string
        summarizeBy: none
        sourceColumn: DATE_RECEIVED_AT_SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_RECEIVED'
        dataType: string
        summarizeBy: none
        sourceColumn: QTY_RECEIVED

        

        annotation SummarizationSetBy = Automatic

        
    column 'TIME_ENTERED'
        dataType: string
        summarizeBy: none
        sourceColumn: TIME_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        



    partition 'PURCHASE_ORDER_RECEIPT' = m
        mode: import
        source = 
            
let
    Source = Excel.Workbook(File.Contents("C:\Users\PowerBIUser\Documents\sample_data.xlsx"), null, true),
    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DATE_ENTERED", type text}, {"SITE_NUMBER", type text}, {"PO_NUMBER", type text}, {"PO_LINE_NUMBER", type text}, {"RELEASE_NUMBER", type text}, {"DATE_RECEIVED_AT_SITE", type text}, {"QTY_RECEIVED", type text}, {"TIME_ENTERED", type text}, {"UNIT_PRICE", type text}})
in
    #"Changed Type"

        



    annotation PBI_ResultType = Table