table 'Dimensional_reportztest'


    column 'Year'
        dataType: decimal
        summarizeBy: none
        sourceColumn: Year

        annotation SummarizationSetBy = Automatic

        
    column 'Quarter'
        dataType: string
        summarizeBy: none
        sourceColumn: Quarter

        annotation SummarizationSetBy = Automatic

        
    column 'Month'
        dataType: string
        summarizeBy: none
        sourceColumn: Month

        annotation SummarizationSetBy = Automatic

        
    column 'ProductName'
        dataType: string
        summarizeBy: none
        sourceColumn: ProductName

        annotation SummarizationSetBy = Automatic

        
    column 'Country'
        dataType: string
        summarizeBy: none
        sourceColumn: Country

        annotation SummarizationSetBy = Automatic

        
    column 'State'
        dataType: string
        summarizeBy: none
        sourceColumn: State

        annotation SummarizationSetBy = Automatic

        
    column 'SalesAmount'
        dataType: decimal
        summarizeBy: sum
        sourceColumn: SalesAmount

        annotation SummarizationSetBy = User

        
    column 'Quantity'
        dataType: decimal
        summarizeBy: sum
        sourceColumn: Quantity

        annotation SummarizationSetBy = User

        
    column 'ProductID'
        dataType: decimal
        summarizeBy: none
        sourceColumn: ProductID

        annotation SummarizationSetBy = Automatic

        
    column 'ProductName'
        dataType: string
        summarizeBy: none
        sourceColumn: ProductName

        annotation SummarizationSetBy = Automatic

        



    partition 'Dimensional_reportztest' = m
        mode: import
        source = 
            let
				Source = / * Connect to data source based on context * /,
				#"Renamed Columns" = Table.RenameColumns(Source,
				{{"OldYear",
				"Year"},
				{"OldQuarter",
				"Quarter"},
				{"OldMonth",
				"Month"},
				{"OldProductName",
				"ProductName"},
				{"OldCountry",
				"Country"},
				{"OldState",
				"State"},
				{"OldSalesAmount",
				"SalesAmount"},
				{"OldQuantity",
				"Quantity"},
				{"OldProductID",
				"ProductID"},
				{"OldProductName2",
				"ProductName"}}),
				#"Changed Types" = Table.TransformColumnTypes(#"Renamed Columns",
				{{"Year",
				type number},
				{"Quarter",
				type text},
				{"Month",
				type text},
				{"ProductName",
				type text},
				{"Country",
				type text},
				{"State",
				type text},
				{"SalesAmount",
				type number},
				{"Quantity",
				type number},
				{"ProductID",
				type number},
				{"ProductName",
				type text}})
			in
				#"Changed Types"
        



    annotation PBI_ResultType = Table