table 'Assistance Report'


    column 'Season'
        dataType: string
        summarizeBy: none
        sourceColumn: Season

        annotation SummarizationSetBy = Automatic

        
    column 'AssistanceReportID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AssistanceReportID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyName'
        dataType: string
        summarizeBy: none
        sourceColumn: AgencyName

        annotation SummarizationSetBy = Automatic

        
    column 'State'
        dataType: string
        summarizeBy: none
        sourceColumn: State

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableMonth'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableMonth

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        annotation SummarizationSetBy = Automatic

        
    column 'TotalAssisted'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalAssisted

        annotation SummarizationSetBy = Automatic

        
    column 'HouseholdsAssisted'
        dataType: int64
        summarizeBy: none
        sourceColumn: HouseholdsAssisted

        annotation SummarizationSetBy = Automatic

        
    column 'TotalOver60'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalOver60

        annotation SummarizationSetBy = Automatic

        
    column 'TotalUnder5'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalUnder5

        annotation SummarizationSetBy = Automatic

        
    column 'TotalDisabled'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalDisabled

        annotation SummarizationSetBy = Automatic

        
    column 'Denials'
        dataType: int64
        summarizeBy: none
        sourceColumn: Denials

        annotation SummarizationSetBy = Automatic

        
    column 'PreparedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: PreparedBy

        annotation SummarizationSetBy = Automatic

        
    column 'PreparedDate'
        dataType: string
        summarizeBy: none
        sourceColumn: PreparedDate

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: string
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: string
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        
    column 'EditLink'
        dataType: string
        summarizeBy: none
        sourceColumn: EditLink

        annotation SummarizationSetBy = Automatic

        
    column 'TotalVeteranVoucher'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalVeteranVoucher

        annotation SummarizationSetBy = Automatic

        
    column 'TotalDisabilityVoucher'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalDisabilityVoucher

        annotation SummarizationSetBy = Automatic

        
    column 'TotalVeteran'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalVeteran

        annotation SummarizationSetBy = Automatic

        
    column 'TotalWeatherInterested'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalWeatherInterested

        annotation SummarizationSetBy = Automatic

        
    column 'Season'
        dataType: string
        summarizeBy: none
        sourceColumn: Season

        annotation SummarizationSetBy = Automatic

        
    column 'AssistanceReportID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AssistanceReportID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyName'
        dataType: string
        summarizeBy: none
        sourceColumn: AgencyName

        annotation SummarizationSetBy = Automatic

        
    column 'State'
        dataType: string
        summarizeBy: none
        sourceColumn: State

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableMonth'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableMonth

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        annotation SummarizationSetBy = Automatic

        
    column 'TotalAssisted'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalAssisted

        annotation SummarizationSetBy = Automatic

        
    column 'HouseholdsAssisted'
        dataType: int64
        summarizeBy: none
        sourceColumn: HouseholdsAssisted

        annotation SummarizationSetBy = Automatic

        
    column 'TotalOver60'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalOver60

        annotation SummarizationSetBy = Automatic

        
    column 'TotalUnder5'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalUnder5

        annotation SummarizationSetBy = Automatic

        
    column 'TotalDisabled'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalDisabled

        annotation SummarizationSetBy = Automatic

        
    column 'Denials'
        dataType: int64
        summarizeBy: none
        sourceColumn: Denials

        annotation SummarizationSetBy = Automatic

        
    column 'PreparedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: PreparedBy

        annotation SummarizationSetBy = Automatic

        
    column 'PreparedDate'
        dataType: string
        summarizeBy: none
        sourceColumn: PreparedDate

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: string
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: string
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        
    column 'EditLink'
        dataType: string
        summarizeBy: none
        sourceColumn: EditLink

        annotation SummarizationSetBy = Automatic

        
    column 'TotalVeteranVoucher'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalVeteranVoucher

        annotation SummarizationSetBy = Automatic

        
    column 'TotalDisabilityVoucher'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalDisabilityVoucher

        annotation SummarizationSetBy = Automatic

        
    column 'TotalVeteran'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalVeteran

        annotation SummarizationSetBy = Automatic

        
    column 'TotalWeatherInterested'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalWeatherInterested

        annotation SummarizationSetBy = Automatic

        



    partition 'Assistance Report' = m
        mode: import
        source = 
            	let
					Source = Value.NativeQuery(Sql.Database("YourServerName", "YourDatabaseName"), "select vwAssistanceReport.Season as Season, vwAssistanceReport.AssistanceReportID as AssistanceReportID, vwAssistanceReport.AgencyID as AgencyID, vwAssistanceReport.AgencyName as AgencyName, vwAssistanceReport.""State"" as State5, vwAssistanceReport.ApplicableMonth as ApplicableMonth, vwAssistanceReport.ApplicableYear as ApplicableYear, vwAssistanceReport.TotalAssisted as TotalAssisted, vwAssistanceReport.HouseholdsAssisted as HouseholdsAssisted, vwAssistanceReport.TotalOver60 as TotalOver60, vwAssistanceReport.TotalUnder5 as TotalUnder5, vwAssistanceReport.TotalDisabled as TotalDisabled, vwAssistanceReport.Denials as Denials, vwAssistanceReport.PreparedBy as PreparedBy, vwAssistanceReport.PreparedDate as PreparedDate, vwAssistanceReport.CreatedBy as CreatedBy, vwAssistanceReport.datecreated as datecreated, vwAssistanceReport.UpdatedBy as UpdatedBy, vwAssistanceReport.LastUpdated as LastUpdated, vwAssistanceReport.EditLink as EditLink from [Shared_Energy_Share].vwAssistanceReport vwAssistanceReport"),
					#"Renamed Columns" = Table.RenameColumns(Source, {{"State5", "State"}}),
					#"Changed Types" = Table.TransformColumnTypes(#"Renamed Columns", {{"Season", type text}, {"AssistanceReportID", Int64.Type}, {"AgencyID", Int64.Type}, {"AgencyName", type text}, {"State", type text}, {"ApplicableMonth", Int64.Type}, {"ApplicableYear", Int64.Type}, {"TotalAssisted", Int64.Type}, {"HouseholdsAssisted", Int64.Type}, {"TotalOver60", Int64.Type}, {"TotalUnder5", Int64.Type}, {"TotalDisabled", Int64.Type}, {"Denials", Int64.Type}, {"PreparedBy", type text}, {"PreparedDate", type text}, {"CreatedBy", type text}, {"datecreated", type text}, {"UpdatedBy", type text}, {"LastUpdated", type text}, {"EditLink", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table