table 'Payee Report'


    column 'Season'
        dataType: string
        summarizeBy: none
        sourceColumn: Season

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        annotation SummarizationSetBy = Automatic

        
    column 'State'
        dataType: string
        summarizeBy: none
        sourceColumn: State

        annotation SummarizationSetBy = Automatic

        
    column 'AuthorizationType'
        dataType: string
        summarizeBy: none
        sourceColumn: AuthorizationType

        annotation SummarizationSetBy = Automatic

        
    column 'VendorID'
        dataType: int64
        summarizeBy: none
        sourceColumn: VendorID

        annotation SummarizationSetBy = Automatic

        
    column 'Vendor'
        dataType: string
        summarizeBy: none
        sourceColumn: Vendor

        annotation SummarizationSetBy = Automatic

        
    column 'Agency'
        dataType: string
        summarizeBy: none
        sourceColumn: Agency

        annotation SummarizationSetBy = Automatic

        
    column 'Date Submitted'
        dataType: string
        summarizeBy: none
        sourceColumn: Date Submitted

        annotation SummarizationSetBy = Automatic

        
    column 'PaidByEnergyShare'
        dataType: string
        summarizeBy: none
        sourceColumn: PaidByEnergyShare

        annotation SummarizationSetBy = Automatic

        
    column 'EditLink'
        dataType: string
        summarizeBy: none
        sourceColumn: EditLink

        annotation SummarizationSetBy = Automatic

        
    column 'Season'
        dataType: string
        summarizeBy: none
        sourceColumn: Season

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        annotation SummarizationSetBy = Automatic

        
    column 'State'
        dataType: string
        summarizeBy: none
        sourceColumn: State

        annotation SummarizationSetBy = Automatic

        
    column 'AuthorizationType'
        dataType: string
        summarizeBy: none
        sourceColumn: AuthorizationType

        annotation SummarizationSetBy = Automatic

        
    column 'VendorID'
        dataType: int64
        summarizeBy: none
        sourceColumn: VendorID

        annotation SummarizationSetBy = Automatic

        
    column 'Vendor'
        dataType: string
        summarizeBy: none
        sourceColumn: Vendor

        annotation SummarizationSetBy = Automatic

        
    column 'Agency'
        dataType: string
        summarizeBy: none
        sourceColumn: Agency

        annotation SummarizationSetBy = Automatic

        
    column 'Date Submitted'
        dataType: string
        summarizeBy: none
        sourceColumn: Date Submitted

        annotation SummarizationSetBy = Automatic

        
    column 'PaidByEnergyShare'
        dataType: string
        summarizeBy: none
        sourceColumn: PaidByEnergyShare

        annotation SummarizationSetBy = Automatic

        
    column 'EditLink'
        dataType: string
        summarizeBy: none
        sourceColumn: EditLink

        annotation SummarizationSetBy = Automatic

        



    partition 'Payee Report' = m
        mode: import
        source = 
            	let
					/* Connect to the SQL Server database and execute the query */ Source = Sql.Database("", "", [Query = "select vwPayeeReport.Season as Season, vwPayeeReport.ApplicableYear as ApplicableYear, vwPayeeReport.""State"" as State3, vwPayeeReport.AuthorizationType as AuthorizationType, vwPayeeReport.VendorID as VendorID, vwPayeeReport.Vendor as Vendor, vwPayeeReport.Agency as Agency, vwPayeeReport.""Date Submitted"" as Date_Submitted, vwPayeeReport.PaidByEnergyShare as PaidByEnergyShare, vwPayeeReport.EditLink as EditLink from [Shared_Energy_Share].vwPayeeReport vwPayeeReport"]),
					/* Remove any rows with errors */ #"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					/* Rename columns to match the expected output */ #"Renamed Columns" = Table.RenameColumns(#"Removed Errors", {{"State3", "State"}, {"Date_Submitted", "Date Submitted"}}),
					/* Change data types of the columns to the specified types */ #"Changed Types" = Table.TransformColumnTypes(#"Renamed Columns", {{"Season", type text}, {"ApplicableYear", Int64.Type}, {"State", type text}, {"AuthorizationType", type text}, {"VendorID", Int64.Type}, {"Vendor", type text}, {"Agency", type text}, {"Date Submitted", type text}, {"PaidByEnergyShare", type text}, {"EditLink", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table