table 'vwAssistanceReport'


    column 'Season'
        dataType: string
        summarizeBy: none
        sourceColumn: Season

        annotation SummarizationSetBy = Automatic

        
    column 'AssistanceReportID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AssistanceReportID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyName'
        dataType: string
        summarizeBy: none
        sourceColumn: AgencyName

        annotation SummarizationSetBy = Automatic

        
    column 'State'
        dataType: string
        summarizeBy: none
        sourceColumn: State

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableMonth'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableMonth

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        annotation SummarizationSetBy = Automatic

        
    column 'TotalVeteran'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalVeteran

        annotation SummarizationSetBy = Automatic

        
    column 'TotalWeatherInterested'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalWeatherInterested

        annotation SummarizationSetBy = Automatic

        
    column 'HouseholdsAssisted'
        dataType: int64
        summarizeBy: none
        sourceColumn: HouseholdsAssisted

        annotation SummarizationSetBy = Automatic

        
    column 'Denials'
        dataType: int64
        summarizeBy: none
        sourceColumn: Denials

        annotation SummarizationSetBy = Automatic

        
    column 'PreparedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: PreparedBy

        annotation SummarizationSetBy = Automatic

        
    column 'PreparedDate'
        dataType: string
        summarizeBy: none
        sourceColumn: PreparedDate

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: string
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: string
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        
    column 'TotalAssisted'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalAssisted

        annotation SummarizationSetBy = Automatic

        
    column 'TotalOver60'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalOver60

        annotation SummarizationSetBy = Automatic

        
    column 'TotalUnder5'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalUnder5

        annotation SummarizationSetBy = Automatic

        
    column 'TotalDisabled'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalDisabled

        annotation SummarizationSetBy = Automatic

        
    column 'TotalVeteranVoucher'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalVeteranVoucher

        annotation SummarizationSetBy = Automatic

        
    column 'TotalDisabilityVoucher'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalDisabilityVoucher

        annotation SummarizationSetBy = Automatic

        
    column 'EditLink'
        dataType: string
        summarizeBy: none
        sourceColumn: EditLink

        annotation SummarizationSetBy = Automatic

        
    column 'Season'
        dataType: string
        summarizeBy: none
        sourceColumn: Season

        annotation SummarizationSetBy = Automatic

        
    column 'AssistanceReportID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AssistanceReportID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyName'
        dataType: string
        summarizeBy: none
        sourceColumn: AgencyName

        annotation SummarizationSetBy = Automatic

        
    column 'State'
        dataType: string
        summarizeBy: none
        sourceColumn: State

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableMonth'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableMonth

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        annotation SummarizationSetBy = Automatic

        
    column 'TotalVeteran'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalVeteran

        annotation SummarizationSetBy = Automatic

        
    column 'TotalWeatherInterested'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalWeatherInterested

        annotation SummarizationSetBy = Automatic

        
    column 'HouseholdsAssisted'
        dataType: int64
        summarizeBy: none
        sourceColumn: HouseholdsAssisted

        annotation SummarizationSetBy = Automatic

        
    column 'Denials'
        dataType: int64
        summarizeBy: none
        sourceColumn: Denials

        annotation SummarizationSetBy = Automatic

        
    column 'PreparedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: PreparedBy

        annotation SummarizationSetBy = Automatic

        
    column 'PreparedDate'
        dataType: string
        summarizeBy: none
        sourceColumn: PreparedDate

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: string
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: string
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        
    column 'TotalAssisted'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalAssisted

        annotation SummarizationSetBy = Automatic

        
    column 'TotalOver60'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalOver60

        annotation SummarizationSetBy = Automatic

        
    column 'TotalUnder5'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalUnder5

        annotation SummarizationSetBy = Automatic

        
    column 'TotalDisabled'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalDisabled

        annotation SummarizationSetBy = Automatic

        
    column 'TotalVeteranVoucher'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalVeteranVoucher

        annotation SummarizationSetBy = Automatic

        
    column 'TotalDisabilityVoucher'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalDisabilityVoucher

        annotation SummarizationSetBy = Automatic

        
    column 'EditLink'
        dataType: string
        summarizeBy: none
        sourceColumn: EditLink

        annotation SummarizationSetBy = Automatic

        



    partition 'vwAssistanceReport' = m
        mode: import
        source = 
            	let
					Source = Sql.Database("", "", [Query = "Select * from [Shared_Energy_Share].vwAssistanceReport"]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"Season", type text}, {"AssistanceReportID", Int64.Type}, {"AgencyID", Int64.Type}, {"AgencyName", type text}, {"State", type text}, {"ApplicableMonth", Int64.Type}, {"ApplicableYear", Int64.Type}, {"TotalVeteran", Int64.Type}, {"TotalWeatherInterested", Int64.Type}, {"HouseholdsAssisted", Int64.Type}, {"Denials", Int64.Type}, {"PreparedBy", type text}, {"PreparedDate", type text}, {"CreatedBy", type text}, {"datecreated", type text}, {"UpdatedBy", type text}, {"LastUpdated", type text}, {"TotalAssisted", Int64.Type}, {"TotalOver60", Int64.Type}, {"TotalUnder5", Int64.Type}, {"TotalDisabled", Int64.Type}, {"TotalVeteranVoucher", Int64.Type}, {"TotalDisabilityVoucher", Int64.Type}, {"EditLink", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table