table 'vwFinancialReportDrillDown'


    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableMonth'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableMonth

        annotation SummarizationSetBy = Automatic

        
    column 'FinancialReportID'
        dataType: int64
        summarizeBy: none
        sourceColumn: FinancialReportID

        annotation SummarizationSetBy = Automatic

        
    column 'AuthorizationID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AuthorizationID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'VendorID'
        dataType: int64
        summarizeBy: none
        sourceColumn: VendorID

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableDate'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicableDate

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantNumber'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantNumber

        annotation SummarizationSetBy = Automatic

        
    column 'AuthorizationType'
        dataType: string
        summarizeBy: none
        sourceColumn: AuthorizationType

        annotation SummarizationSetBy = Automatic

        
    column 'VendorAccountNumber'
        dataType: string
        summarizeBy: none
        sourceColumn: VendorAccountNumber

        annotation SummarizationSetBy = Automatic

        
    column 'FuelType'
        dataType: string
        summarizeBy: none
        sourceColumn: FuelType

        annotation SummarizationSetBy = Automatic

        
    column 'IsOver60'
        dataType: string
        summarizeBy: none
        sourceColumn: IsOver60

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantFirstName'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantFirstName

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantMiddleName'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantMiddleName

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantLastName'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantLastName

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantPhone'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantPhone

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantAddress'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantAddress

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantCity'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantCity

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantState'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantState

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantZip'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantZip

        annotation SummarizationSetBy = Automatic

        
    column 'TotalAssisted'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalAssisted

        annotation SummarizationSetBy = Automatic

        
    column 'TotalUnder5'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalUnder5

        annotation SummarizationSetBy = Automatic

        
    column 'TotalOver60'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalOver60

        annotation SummarizationSetBy = Automatic

        
    column 'TotalDisabled'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalDisabled

        annotation SummarizationSetBy = Automatic

        
    column 'AmountDue'
        dataType: string
        summarizeBy: none
        sourceColumn: AmountDue

        annotation SummarizationSetBy = Automatic

        
    column 'MatchingEnergyCredit'
        dataType: string
        summarizeBy: none
        sourceColumn: MatchingEnergyCredit

        annotation SummarizationSetBy = Automatic

        
    column 'PaidByEnergyShare'
        dataType: string
        summarizeBy: none
        sourceColumn: PaidByEnergyShare

        annotation SummarizationSetBy = Automatic

        
    column 'DepositGuarantee'
        dataType: string
        summarizeBy: none
        sourceColumn: DepositGuarantee

        annotation SummarizationSetBy = Automatic

        
    column 'PaymentAuthorizedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: PaymentAuthorizedBy

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: string
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: string
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        
    column 'EditLink'
        dataType: string
        summarizeBy: none
        sourceColumn: EditLink

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableMonth'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableMonth

        annotation SummarizationSetBy = Automatic

        
    column 'FinancialReportID'
        dataType: int64
        summarizeBy: none
        sourceColumn: FinancialReportID

        annotation SummarizationSetBy = Automatic

        
    column 'AuthorizationID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AuthorizationID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'VendorID'
        dataType: int64
        summarizeBy: none
        sourceColumn: VendorID

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableDate'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicableDate

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantNumber'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantNumber

        annotation SummarizationSetBy = Automatic

        
    column 'AuthorizationType'
        dataType: string
        summarizeBy: none
        sourceColumn: AuthorizationType

        annotation SummarizationSetBy = Automatic

        
    column 'VendorAccountNumber'
        dataType: string
        summarizeBy: none
        sourceColumn: VendorAccountNumber

        annotation SummarizationSetBy = Automatic

        
    column 'FuelType'
        dataType: string
        summarizeBy: none
        sourceColumn: FuelType

        annotation SummarizationSetBy = Automatic

        
    column 'IsOver60'
        dataType: string
        summarizeBy: none
        sourceColumn: IsOver60

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantFirstName'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantFirstName

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantMiddleName'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantMiddleName

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantLastName'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantLastName

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantPhone'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantPhone

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantAddress'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantAddress

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantCity'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantCity

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantState'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantState

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantZip'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantZip

        annotation SummarizationSetBy = Automatic

        
    column 'TotalAssisted'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalAssisted

        annotation SummarizationSetBy = Automatic

        
    column 'TotalUnder5'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalUnder5

        annotation SummarizationSetBy = Automatic

        
    column 'TotalOver60'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalOver60

        annotation SummarizationSetBy = Automatic

        
    column 'TotalDisabled'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalDisabled

        annotation SummarizationSetBy = Automatic

        
    column 'AmountDue'
        dataType: string
        summarizeBy: none
        sourceColumn: AmountDue

        annotation SummarizationSetBy = Automatic

        
    column 'MatchingEnergyCredit'
        dataType: string
        summarizeBy: none
        sourceColumn: MatchingEnergyCredit

        annotation SummarizationSetBy = Automatic

        
    column 'PaidByEnergyShare'
        dataType: string
        summarizeBy: none
        sourceColumn: PaidByEnergyShare

        annotation SummarizationSetBy = Automatic

        
    column 'DepositGuarantee'
        dataType: string
        summarizeBy: none
        sourceColumn: DepositGuarantee

        annotation SummarizationSetBy = Automatic

        
    column 'PaymentAuthorizedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: PaymentAuthorizedBy

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: string
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: string
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        
    column 'EditLink'
        dataType: string
        summarizeBy: none
        sourceColumn: EditLink

        annotation SummarizationSetBy = Automatic

        



    partition 'vwFinancialReportDrillDown' = m
        mode: import
        source = 
            	let
					Source = Value.NativeQuery(Sql.Database("YourServerName", "YourDatabaseName"), "Select * from [Shared_Energy_Share].vwFinancialReportDrillDown"),
					#"Changed Types" = Table.TransformColumnTypes(Source, {{"ApplicableYear", Int64.Type}, {"ApplicableMonth", Int64.Type}, {"FinancialReportID", Int64.Type}, {"AuthorizationID", Int64.Type}, {"AgencyID", Int64.Type}, {"VendorID", Int64.Type}, {"ApplicableDate", type text}, {"ApplicantNumber", type text}, {"AuthorizationType", type text}, {"VendorAccountNumber", type text}, {"FuelType", type text}, {"IsOver60", type text}, {"ApplicantFirstName", type text}, {"ApplicantMiddleName", type text}, {"ApplicantLastName", type text}, {"ApplicantPhone", type text}, {"ApplicantAddress", type text}, {"ApplicantCity", type text}, {"ApplicantState", type text}, {"ApplicantZip", type text}, {"TotalAssisted", Int64.Type}, {"TotalUnder5", Int64.Type}, {"TotalOver60", Int64.Type}, {"TotalDisabled", Int64.Type}, {"AmountDue", type text}, {"MatchingEnergyCredit", type text}, {"PaidByEnergyShare", type text}, {"DepositGuarantee", type text}, {"PaymentAuthorizedBy", type text}, {"CreatedBy", type text}, {"datecreated", type text}, {"UpdatedBy", type text}, {"LastUpdated", type text}, {"EditLink", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table