table 'vwPayeeReport'


    column 'Season'
        dataType: string
        summarizeBy: none
        sourceColumn: Season

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        annotation SummarizationSetBy = Automatic

        
    column 'State'
        dataType: string
        summarizeBy: none
        sourceColumn: State

        annotation SummarizationSetBy = Automatic

        
    column 'AuthorizationType'
        dataType: string
        summarizeBy: none
        sourceColumn: AuthorizationType

        annotation SummarizationSetBy = Automatic

        
    column 'VendorID'
        dataType: int64
        summarizeBy: none
        sourceColumn: VendorID

        annotation SummarizationSetBy = Automatic

        
    column 'Vendor'
        dataType: string
        summarizeBy: none
        sourceColumn: Vendor

        annotation SummarizationSetBy = Automatic

        
    column 'Agency'
        dataType: string
        summarizeBy: none
        sourceColumn: Agency

        annotation SummarizationSetBy = Automatic

        
    column 'Date Submitted'
        dataType: string
        summarizeBy: none
        sourceColumn: Date Submitted

        annotation SummarizationSetBy = Automatic

        
    column 'PaidByEnergyShare'
        dataType: string
        summarizeBy: none
        sourceColumn: PaidByEnergyShare

        annotation SummarizationSetBy = Automatic

        
    column 'EditLink'
        dataType: string
        summarizeBy: none
        sourceColumn: EditLink

        annotation SummarizationSetBy = Automatic

        
    column 'Season'
        dataType: string
        summarizeBy: none
        sourceColumn: Season

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        annotation SummarizationSetBy = Automatic

        
    column 'State'
        dataType: string
        summarizeBy: none
        sourceColumn: State

        annotation SummarizationSetBy = Automatic

        
    column 'AuthorizationType'
        dataType: string
        summarizeBy: none
        sourceColumn: AuthorizationType

        annotation SummarizationSetBy = Automatic

        
    column 'VendorID'
        dataType: int64
        summarizeBy: none
        sourceColumn: VendorID

        annotation SummarizationSetBy = Automatic

        
    column 'Vendor'
        dataType: string
        summarizeBy: none
        sourceColumn: Vendor

        annotation SummarizationSetBy = Automatic

        
    column 'Agency'
        dataType: string
        summarizeBy: none
        sourceColumn: Agency

        annotation SummarizationSetBy = Automatic

        
    column 'Date Submitted'
        dataType: string
        summarizeBy: none
        sourceColumn: Date Submitted

        annotation SummarizationSetBy = Automatic

        
    column 'PaidByEnergyShare'
        dataType: string
        summarizeBy: none
        sourceColumn: PaidByEnergyShare

        annotation SummarizationSetBy = Automatic

        
    column 'EditLink'
        dataType: string
        summarizeBy: none
        sourceColumn: EditLink

        annotation SummarizationSetBy = Automatic

        



    partition 'vwPayeeReport' = m
        mode: import
        source = 
            	let
					/* Connect to the SQL Server database and retrieve data from the specified view */ Source = Sql.Database("", "", [Query = "Select * from [Shared_Energy_Share].vwPayeeReport"]),
					/* Remove any rows with errors to ensure data integrity */ #"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					/* Change column types to ensure correct data types for each column */ #"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"Season", type text}, {"ApplicableYear", Int64.Type}, {"State", type text}, {"AuthorizationType", type text}, {"VendorID", Int64.Type}, {"Vendor", type text}, {"Agency", type text}, {"Date Submitted", type text}, {"PaidByEnergyShare", type text}, {"EditLink", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table