table 'Sheet1 (sample_sales_data)'


    column 'Order ID'
        dataType: int64
        summarizeBy: sum
        sourceColumn: Order ID

        
    column 'Order Date'
        dataType: datetime
        summarizeBy: none
        sourceColumn: Order Date

        
    column 'Region'
        dataType: string
        summarizeBy: none
        sourceColumn: Region

        
    column 'Product Category'
        dataType: string
        summarizeBy: none
        sourceColumn: Product Category

        
    column 'Product Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Product Name

        
    column 'Sales'
        dataType: double
        summarizeBy: sum
        sourceColumn: Sales

        
    column 'Quantity'
        dataType: int64
        summarizeBy: sum
        sourceColumn: Quantity

        
    column 'Discount'
        dataType: double
        summarizeBy: sum
        sourceColumn: Discount

        
    column 'Profit'
        dataType: double
        summarizeBy: sum
        sourceColumn: Profit

	partition Sheet1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\CodehiveBIVM\Desktop\Datasets\sample_sales_data.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order ID", Int64.Type}, {"Order Date", Int64.Type}, {"Region", type text}, {"Product Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table        





