table 'Sheet1'


    column 'Order ID'
        dataType: int64
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        
    column 'Order Date'
        dataType: datetime
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        
    column 'Region'
        dataType: string
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        
    column 'Product Category'
        dataType: string
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        
    column 'Product Name'
        dataType: string
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        
    column 'Sales'
        dataType: double
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        
    column 'Quantity'
        dataType: int64
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        
    column 'Discount'
        dataType: double
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        
    column 'Profit'
        dataType: double
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        



    partition 'Sheet1' = m
        mode: import
        source = 
            	let
					Source = Excel.Workbook(File.Contents("C:/Users/CodehiveBIVM/Desktop/Datasets/sample_sales_data.xlsx"), null, true),
					Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
					#"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Order ID", Int64.Type}, {"Order Date", type datetime}, {"Region", type text}, {"Product Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
					#"Changed Type"
        



    annotation PBI_ResultType = Table
