table 'Sheet1 (sample_sales_data)'


    column 'Order ID'
        dataType: int64
        summarizeBy: sum
        sourceColumn: Order ID

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Order Date'
        dataType: datetime
        summarizeBy: none
        sourceColumn: Order Date

        annotation SummarizationSetBy = Automatic

        
    column 'Region'
        dataType: string
        summarizeBy: none
        sourceColumn: Region

        annotation SummarizationSetBy = Automatic

        
    column 'Product Category'
        dataType: string
        summarizeBy: none
        sourceColumn: Product Category

        annotation SummarizationSetBy = Automatic

        
    column 'Product Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Product Name

        annotation SummarizationSetBy = Automatic

        
    column 'Sales'
        dataType: double
        summarizeBy: sum
        sourceColumn: Sales

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Quantity'
        dataType: int64
        summarizeBy: sum
        sourceColumn: Quantity

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Discount'
        dataType: double
        summarizeBy: sum
        sourceColumn: Discount

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Profit'
        dataType: double
        summarizeBy: sum
        sourceColumn: Profit

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        



    partition 'Sheet1 (sample_sales_data)-37ac1e29-3474-45b3-a722-5aa6abd02740' = M
        mode: import
        source = ```
            let
    Source = Excel.Workbook(File.Contents(&quot;C:\Path\To\File.xlsx&quot;), null, true),
    Sheet1_Table = Source{[Item=&quot;Sheet1&quot;,Kind=&quot;Sheet&quot;]}[Data],
    #&quot;Changed Type&quot; = Table.TransformColumnTypes(Sheet1_Table,{{&quot;Column1&quot;, type text}, {&quot;Column2&quot;, Int64.Type}, {&quot;Column3&quot;, type date}})
in
    #&quot;Changed Type&quot;
        ```



    annotation PBI_ResultType = Table
