table Financial


    column 'FinancialReportID'
        dataType: int64
        summarizeBy: none
        sourceColumn: FinancialReportID

        

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableMonth'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableMonth

        

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        

        annotation SummarizationSetBy = Automatic

        
    column 'BalanceForward'
        dataType: string
        summarizeBy: none
        sourceColumn: BalanceForward

        

        annotation SummarizationSetBy = Automatic

        
    column 'EnergyShareCheckAmount'
        dataType: string
        summarizeBy: none
        sourceColumn: EnergyShareCheckAmount

        

        annotation SummarizationSetBy = Automatic

        
    column 'EnergySharePartnerAmount'
        dataType: string
        summarizeBy: none
        sourceColumn: EnergySharePartnerAmount

        

        annotation SummarizationSetBy = Automatic

        
    column 'AmountSpentPayingEnergyBills'
        dataType: string
        summarizeBy: none
        sourceColumn: AmountSpentPayingEnergyBills

        

        annotation SummarizationSetBy = Automatic

        
    column 'BalanceOnHand'
        dataType: string
        summarizeBy: none
        sourceColumn: BalanceOnHand

        

        annotation SummarizationSetBy = Automatic

        
    column 'PreparedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: PreparedBy

        

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: datecreated

        
        variation Variation
            isDefault
            relationship: 784394e9-56ca-43b2-a7ef-1639dcb0a8d2
            defaultHierarchy: CentralDateTable.'Date Hierarchy'

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: LastUpdated

        

        annotation SummarizationSetBy = Automatic

        

    measure '' = ```
            CALCULATE(
    COUNTROWS('tblFinancialReport'),
    USERELATIONSHIP('CentralDateTable'[Date], 'tblFinancialReport'[datecreated])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure '' = ```
            CALCULATE(
    COUNTROWS('tblFinancialReport'),
    USERELATIONSHIP('CentralDateTable'[Date], 'tblFinancialReport'[LastUpdated])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure '' = ```
            CALCULATE(
    COUNTROWS('tblFinancialReport'),
    USERELATIONSHIP('CentralDateTable'[Date], 'tblFinancialReport'[LastUpdated])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'Financial' = m
        mode: import
        source = 
            	let
					Source = Sql.Database("", "", [Query = "Select * from [Shared_Energy_Share].tblFinancialReport"]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"FinancialReportID", Int64.Type}, {"AgencyID", Int64.Type}, {"ApplicableMonth", Int64.Type}, {"ApplicableYear", Int64.Type}, {"BalanceForward", type text}, {"EnergyShareCheckAmount", type text}, {"EnergySharePartnerAmount", type text}, {"AmountSpentPayingEnergyBills", type text}, {"BalanceOnHand", type text}, {"PreparedBy", type text}, {"CreatedBy", type text}, {"datecreated", type datetime}, {"UpdatedBy", type text}, {"LastUpdated", type datetime}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table