table Territory


    column 'TerritoryID'
        dataType: int64
        summarizeBy: none
        sourceColumn: TerritoryID

        

        annotation SummarizationSetBy = Automatic

        
    column 'Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Name

        

        annotation SummarizationSetBy = Automatic

        
    column 'IsActive'
        dataType: string
        summarizeBy: none
        sourceColumn: IsActive

        

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: datecreated

        
        variation Variation
            isDefault
            relationship: c63cf1f3-02a2-4420-9c70-15bf338665b2
            defaultHierarchy: CentralDateTable.'Date Hierarchy'

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: LastUpdated

        

        annotation SummarizationSetBy = Automatic

        

    measure 'Count of Rows by datecreated' = ```
            CALCULATE(
    COUNTROWS('Territory'),
    USERELATIONSHIP('CentralDateTable'[Date], 'Territory'[datecreated])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Count of Rows by LastUpdated' = ```
            CALCULATE(
    COUNTROWS('Territory'),
    USERELATIONSHIP('CentralDateTable'[Date], 'Territory'[LastUpdated])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'Territory' = m
        mode: import
        source = 
            	let
					Source = Sql.Database("", "", [Query = "Select * from [Shared_Energy_Share].tblTerritory"]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"TerritoryID", Int64.Type}, {"Name", type text}, {"IsActive", type text}, {"CreatedBy", type text}, {"datecreated", type datetime}, {"UpdatedBy", type text}, {"LastUpdated", type datetime}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table