table Vendor


    column 'VendorID'
        dataType: int64
        summarizeBy: none
        sourceColumn: VendorID

        

        annotation SummarizationSetBy = Automatic

        
    column 'Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Name

        

        annotation SummarizationSetBy = Automatic

        
    column 'Address1'
        dataType: string
        summarizeBy: none
        sourceColumn: Address1

        

        annotation SummarizationSetBy = Automatic

        
    column 'Address2'
        dataType: string
        summarizeBy: none
        sourceColumn: Address2

        

        annotation SummarizationSetBy = Automatic

        
    column 'City'
        dataType: string
        summarizeBy: none
        sourceColumn: City

        

        annotation SummarizationSetBy = Automatic

        
    column 'State'
        dataType: string
        summarizeBy: none
        sourceColumn: State

        

        annotation SummarizationSetBy = Automatic

        
    column 'Zip'
        dataType: string
        summarizeBy: none
        sourceColumn: Zip

        

        annotation SummarizationSetBy = Automatic

        
    column 'Phone'
        dataType: string
        summarizeBy: none
        sourceColumn: Phone

        

        annotation SummarizationSetBy = Automatic

        
    column 'IsDominionVendor'
        dataType: string
        summarizeBy: none
        sourceColumn: IsDominionVendor

        

        annotation SummarizationSetBy = Automatic

        
    column 'IsActive'
        dataType: string
        summarizeBy: none
        sourceColumn: IsActive

        

        annotation SummarizationSetBy = Automatic

        
    column 'DefaultState'
        dataType: string
        summarizeBy: none
        sourceColumn: DefaultState

        

        annotation SummarizationSetBy = Automatic

        
    column 'sellsDominion'
        dataType: string
        summarizeBy: none
        sourceColumn: sellsDominion

        

        annotation SummarizationSetBy = Automatic

        
    column 'sellsOtherElectric'
        dataType: string
        summarizeBy: none
        sourceColumn: sellsOtherElectric

        

        annotation SummarizationSetBy = Automatic

        
    column 'sellsFuelOil'
        dataType: string
        summarizeBy: none
        sourceColumn: sellsFuelOil

        

        annotation SummarizationSetBy = Automatic

        
    column 'sellsCoalOrWood'
        dataType: string
        summarizeBy: none
        sourceColumn: sellsCoalOrWood

        

        annotation SummarizationSetBy = Automatic

        
    column 'sellsNaturalGas'
        dataType: string
        summarizeBy: none
        sourceColumn: sellsNaturalGas

        

        annotation SummarizationSetBy = Automatic

        
    column 'sellsKerosene'
        dataType: string
        summarizeBy: none
        sourceColumn: sellsKerosene

        

        annotation SummarizationSetBy = Automatic

        
    column 'sellsPropane'
        dataType: string
        summarizeBy: none
        sourceColumn: sellsPropane

        

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: datecreated

        
        variation Variation
            isDefault
            relationship: 5edfe375-30e2-4520-8911-452098c879c5
            defaultHierarchy: CentralDateTable.'Date Hierarchy'

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: LastUpdated

        

        annotation SummarizationSetBy = Automatic

        

    measure 'Count of Rows by datecreated' = ```
            CALCULATE(
    COUNTROWS('Vendor'),
    USERELATIONSHIP('CentralDateTable'[Date], 'Vendor'[datecreated])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Count of Rows by LastUpdated' = ```
            CALCULATE(
    COUNTROWS('Vendor'),
    USERELATIONSHIP('CentralDateTable'[Date], 'Vendor'[LastUpdated])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'Vendor' = m
        mode: import
        source = 
            	let
					Source = Sql.Database("", "", [Query = "Select * from [Shared_Energy_Share].tblVendor"]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"VendorID", Int64.Type}, {"Name", type text}, {"Address1", type text}, {"Address2", type text}, {"City", type text}, {"State", type text}, {"Zip", type text}, {"Phone", type text}, {"IsDominionVendor", type text}, {"IsActive", type text}, {"DefaultState", type text}, {"sellsDominion", type text}, {"sellsOtherElectric", type text}, {"sellsFuelOil", type text}, {"sellsCoalOrWood", type text}, {"sellsNaturalGas", type text}, {"sellsKerosene", type text}, {"sellsPropane", type text}, {"CreatedBy", type text}, {"datecreated", type datetime}, {"UpdatedBy", type text}, {"LastUpdated", type datetime}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table