table vwAssistanceReportDrillDown


    column 'Season'
        dataType: string
        summarizeBy: none
        sourceColumn: Season

        

        annotation SummarizationSetBy = Automatic

        
    column 'AssistanceReportID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AssistanceReportID

        

        annotation SummarizationSetBy = Automatic

        
    column 'AuthorizationID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AuthorizationID

        

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyName'
        dataType: string
        summarizeBy: none
        sourceColumn: AgencyName

        

        annotation SummarizationSetBy = Automatic

        
    column 'State'
        dataType: string
        summarizeBy: none
        sourceColumn: State

        

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableMonth'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableMonth

        

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: datecreated

        
        variation Variation
            isDefault
            relationship: 9b7d7176-7b54-4d7d-aefa-51c57f923df3
            defaultHierarchy: CentralDateTable.'Date Hierarchy'

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: LastUpdated

        

        annotation SummarizationSetBy = Automatic

        
    column 'TotalVeteranVoucher'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalVeteranVoucher

        

        annotation SummarizationSetBy = Automatic

        
    column 'TotalDisabilityVoucher'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalDisabilityVoucher

        

        annotation SummarizationSetBy = Automatic

        
    column 'TotalAssisted'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalAssisted

        

        annotation SummarizationSetBy = Automatic

        
    column 'TotalOver60'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalOver60

        

        annotation SummarizationSetBy = Automatic

        
    column 'TotalUnder5'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalUnder5

        

        annotation SummarizationSetBy = Automatic

        
    column 'TotalDisabled'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalDisabled

        

        annotation SummarizationSetBy = Automatic

        
    column 'TotalVeteran'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalVeteran

        

        annotation SummarizationSetBy = Automatic

        
    column 'TotalWeatherInterested'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalWeatherInterested

        

        annotation SummarizationSetBy = Automatic

        
    column 'EditLink'
        dataType: string
        summarizeBy: none
        sourceColumn: EditLink

        

        annotation SummarizationSetBy = Automatic

        

    measure 'Count of Rows by datecreated' = ```
            CALCULATE(
    COUNTROWS('vwAssistanceReportDrillDown'),
    USERELATIONSHIP('CentralDateTable'[Date], 'vwAssistanceReportDrillDown'[datecreated])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Count of Rows by LastUpdated' = ```
            CALCULATE(
    COUNTROWS('vwAssistanceReportDrillDown'),
    USERELATIONSHIP('CentralDateTable'[Date], 'vwAssistanceReportDrillDown'[LastUpdated])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'vwAssistanceReportDrillDown' = m
        mode: import
        source = 
            	let
					Source = Sql.Database("", "", [Query = "Select * from [Shared_Energy_Share].vwAssistanceReportDrillDown"]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"Season", type text}, {"AssistanceReportID", Int64.Type}, {"AuthorizationID", Int64.Type}, {"AgencyID", Int64.Type}, {"AgencyName", type text}, {"State", type text}, {"ApplicableMonth", Int64.Type}, {"ApplicableYear", Int64.Type}, {"CreatedBy", type text}, {"datecreated", type datetime}, {"UpdatedBy", type text}, {"LastUpdated", type datetime}, {"TotalVeteranVoucher", Int64.Type}, {"TotalDisabilityVoucher", Int64.Type}, {"TotalAssisted", Int64.Type}, {"TotalOver60", Int64.Type}, {"TotalUnder5", Int64.Type}, {"TotalDisabled", Int64.Type}, {"TotalVeteran", Int64.Type}, {"TotalWeatherInterested", Int64.Type}, {"EditLink", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table