table vwFinancialReport


    column 'FinancialReportID'
        dataType: int64
        summarizeBy: none
        sourceColumn: FinancialReportID

        

        annotation SummarizationSetBy = Automatic

        
    column 'Zip'
        dataType: string
        summarizeBy: none
        sourceColumn: Zip

        

        annotation SummarizationSetBy = Automatic

        
    column 'ContactName'
        dataType: string
        summarizeBy: none
        sourceColumn: ContactName

        

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        

        annotation SummarizationSetBy = Automatic

        
    column 'Season'
        dataType: string
        summarizeBy: none
        sourceColumn: Season

        

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyName'
        dataType: string
        summarizeBy: none
        sourceColumn: AgencyName

        

        annotation SummarizationSetBy = Automatic

        
    column 'Address1'
        dataType: string
        summarizeBy: none
        sourceColumn: Address1

        

        annotation SummarizationSetBy = Automatic

        
    column 'Address2'
        dataType: string
        summarizeBy: none
        sourceColumn: Address2

        

        annotation SummarizationSetBy = Automatic

        
    column 'City'
        dataType: string
        summarizeBy: none
        sourceColumn: City

        

        annotation SummarizationSetBy = Automatic

        
    column 'State'
        dataType: string
        summarizeBy: none
        sourceColumn: State

        

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableMonth'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableMonth

        

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        

        annotation SummarizationSetBy = Automatic

        
    column 'TOTAL'
        dataType: string
        summarizeBy: none
        sourceColumn: TOTAL

        

        annotation SummarizationSetBy = Automatic

        
    column 'BalanceForward'
        dataType: string
        summarizeBy: none
        sourceColumn: BalanceForward

        

        annotation SummarizationSetBy = Automatic

        
    column 'EnergyShareCheckAmount'
        dataType: string
        summarizeBy: none
        sourceColumn: EnergyShareCheckAmount

        

        annotation SummarizationSetBy = Automatic

        
    column 'EnergySharePartnerAmount'
        dataType: string
        summarizeBy: none
        sourceColumn: EnergySharePartnerAmount

        

        annotation SummarizationSetBy = Automatic

        
    column 'AmountSpentPayingEnergyBills'
        dataType: string
        summarizeBy: none
        sourceColumn: AmountSpentPayingEnergyBills

        

        annotation SummarizationSetBy = Automatic

        
    column 'BalanceOnHand'
        dataType: string
        summarizeBy: none
        sourceColumn: BalanceOnHand

        

        annotation SummarizationSetBy = Automatic

        
    column 'PreparedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: PreparedBy

        

        annotation SummarizationSetBy = Automatic

        
    column 'Adjustment'
        dataType: string
        summarizeBy: none
        sourceColumn: Adjustment

        

        annotation SummarizationSetBy = Automatic

        
    column 'AdjustmentReason'
        dataType: string
        summarizeBy: none
        sourceColumn: AdjustmentReason

        

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: datecreated

        
        variation Variation
            isDefault
            relationship: 954fb3fd-3a0d-4b93-9d6f-773c8471a98c
            defaultHierarchy: CentralDateTable.'Date Hierarchy'

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: LastUpdated

        

        annotation SummarizationSetBy = Automatic

        
    column 'itemizedDominion'
        dataType: string
        summarizeBy: none
        sourceColumn: itemizedDominion

        

        annotation SummarizationSetBy = Automatic

        
    column 'itemizedOtherElectric'
        dataType: string
        summarizeBy: none
        sourceColumn: itemizedOtherElectric

        

        annotation SummarizationSetBy = Automatic

        
    column 'itemizedFuelOil'
        dataType: string
        summarizeBy: none
        sourceColumn: itemizedFuelOil

        

        annotation SummarizationSetBy = Automatic

        
    column 'itemizedCoalWood'
        dataType: string
        summarizeBy: none
        sourceColumn: itemizedCoalWood

        

        annotation SummarizationSetBy = Automatic

        
    column 'itemizedNaturalGas'
        dataType: string
        summarizeBy: none
        sourceColumn: itemizedNaturalGas

        

        annotation SummarizationSetBy = Automatic

        
    column 'itemizedKerosene'
        dataType: string
        summarizeBy: none
        sourceColumn: itemizedKerosene

        

        annotation SummarizationSetBy = Automatic

        
    column 'itemizedPropaneBottledGas'
        dataType: string
        summarizeBy: none
        sourceColumn: itemizedPropaneBottledGas

        

        annotation SummarizationSetBy = Automatic

        
    column 'itemizedNumberofDepositsGuaranteed'
        dataType: string
        summarizeBy: none
        sourceColumn: itemizedNumberofDepositsGuaranteed

        

        annotation SummarizationSetBy = Automatic

        
    column 'EditLink'
        dataType: string
        summarizeBy: none
        sourceColumn: EditLink

        

        annotation SummarizationSetBy = Automatic

        
    column 'DirectIndividualContributions'
        dataType: int64
        summarizeBy: none
        sourceColumn: DirectIndividualContributions

        

        annotation SummarizationSetBy = Automatic

        
    column 'DirectRecipientContributions'
        dataType: int64
        summarizeBy: none
        sourceColumn: DirectRecipientContributions

        

        annotation SummarizationSetBy = Automatic

        
    column 'itemizedCoalOrWood'
        dataType: string
        summarizeBy: none
        sourceColumn: itemizedCoalOrWood

        

        annotation SummarizationSetBy = Automatic

        
    column 'itemizedPropane'
        dataType: string
        summarizeBy: none
        sourceColumn: itemizedPropane

        

        annotation SummarizationSetBy = Automatic

        

    measure 'Count of Rows by datecreated' = ```
            CALCULATE(
    COUNTROWS('vwFinancialReport'),
    USERELATIONSHIP('CentralDateTable'[Date], 'vwFinancialReport'[datecreated])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Count of Rows by LastUpdated' = ```
            CALCULATE(
    COUNTROWS('vwFinancialReport'),
    USERELATIONSHIP('CentralDateTable'[Date], 'vwFinancialReport'[LastUpdated])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'vwFinancialReport' = m
        mode: import
        source = 
            	let
					Source = Sql.Database("", "", [Query = "Select * from [Shared_Energy_Share].vwFinancialReport"]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"FinancialReportID", Int64.Type}, {"Zip", type text}, {"ContactName", type text}, {"AgencyID", Int64.Type}, {"Season", type text}, {"AgencyName", type text}, {"Address1", type text}, {"Address2", type text}, {"City", type text}, {"State", type text}, {"ApplicableMonth", Int64.Type}, {"ApplicableYear", Int64.Type}, {"TOTAL", type text}, {"BalanceForward", type text}, {"EnergyShareCheckAmount", type text}, {"EnergySharePartnerAmount", type text}, {"AmountSpentPayingEnergyBills", type text}, {"BalanceOnHand", type text}, {"PreparedBy", type text}, {"Adjustment", type text}, {"AdjustmentReason", type text}, {"CreatedBy", type text}, {"datecreated", type datetime}, {"UpdatedBy", type text}, {"LastUpdated", type datetime}, {"itemizedDominion", type text}, {"itemizedOtherElectric", type text}, {"itemizedFuelOil", type text}, {"itemizedCoalWood", type text}, {"itemizedNaturalGas", type text}, {"itemizedKerosene", type text}, {"itemizedPropaneBottledGas", type text}, {"itemizedNumberofDepositsGuaranteed", type text}, {"EditLink", type text}, {"DirectIndividualContributions", Int64.Type}, {"DirectRecipientContributions", Int64.Type}, {"itemizedCoalOrWood", type text}, {"itemizedPropane", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table