table vwPayeeReport


    column 'Season'
        dataType: string
        summarizeBy: none
        sourceColumn: Season

        

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        

        annotation SummarizationSetBy = Automatic

        
    column 'State'
        dataType: string
        summarizeBy: none
        sourceColumn: State

        

        annotation SummarizationSetBy = Automatic

        
    column 'AuthorizationType'
        dataType: string
        summarizeBy: none
        sourceColumn: AuthorizationType

        

        annotation SummarizationSetBy = Automatic

        
    column 'VendorID'
        dataType: int64
        summarizeBy: none
        sourceColumn: VendorID

        

        annotation SummarizationSetBy = Automatic

        
    column 'Vendor'
        dataType: string
        summarizeBy: none
        sourceColumn: Vendor

        

        annotation SummarizationSetBy = Automatic

        
    column 'Agency'
        dataType: string
        summarizeBy: none
        sourceColumn: Agency

        

        annotation SummarizationSetBy = Automatic

        
    column 'Date Submitted'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: Date Submitted

        
        variation Variation
            isDefault
            relationship: b9307a34-9363-4c0c-8844-f598872464cf
            defaultHierarchy: CentralDateTable.'Date Hierarchy'

        annotation SummarizationSetBy = Automatic

        
    column 'PaidByEnergyShare'
        dataType: string
        summarizeBy: none
        sourceColumn: PaidByEnergyShare

        

        annotation SummarizationSetBy = Automatic

        
    column 'EditLink'
        dataType: string
        summarizeBy: none
        sourceColumn: EditLink

        

        annotation SummarizationSetBy = Automatic

        

    measure '' = ```
            CALCULATE(
    COUNTROWS('vwPayeeReport'),
    USERELATIONSHIP('CentralDateTable'[Date], 'vwPayeeReport'[Date Submitted])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'vwPayeeReport' = m
        mode: import
        source = 
            	let
					Source = Sql.Database("", "", [Query = "Select * from [Shared_Energy_Share].vwPayeeReport"]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"Season", type text}, {"ApplicableYear", Int64.Type}, {"State", type text}, {"AuthorizationType", type text}, {"VendorID", Int64.Type}, {"Vendor", type text}, {"Agency", type text}, {"Date Submitted", type datetime}, {"PaidByEnergyShare", type text}, {"EditLink", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table