table Dim_ITEM_SITE_EXTRACT_MATERIAL_CHARGES


    column 'Column'
        dataType: string
        summarizeBy: none
        sourceColumn: Column

        

        annotation SummarizationSetBy = Automatic

        
    column 'Column'
        dataType: string
        summarizeBy: none
        sourceColumn: Column

        

        annotation SummarizationSetBy = Automatic

        
    column 'Column'
        dataType: string
        summarizeBy: none
        sourceColumn: Column

        

        annotation SummarizationSetBy = Automatic

        



    partition 'Dim_ITEM_SITE_EXTRACT_MATERIAL_CHARGES' = m
        mode: import
        source = 
            let
                // Get data from ITEM_SITE_EXTRACT
                Data_From_ITEM_SITE_EXTRACT = Table.SelectColumns(ITEM_SITE_EXTRACT, {"SITE_NUMBER", "ITEM_NUMBER"}),
                // Get data from MATERIAL_CHARGES
                Data_From_MATERIAL_CHARGES = Table.SelectColumns(MATERIAL_CHARGES, {"SITE_NUMBER", "ITEM_NUMBER"}),
                // Combine data from all source tables
                CombinedData = Table.Combine({Data_From_ITEM_SITE_EXTRACT, Data_From_MATERIAL_CHARGES}),
                // Get unique combinations of dimension keys
                UniqueRows = Table.Distinct(CombinedData, {"SITE_NUMBER", "ITEM_NUMBER"}),
                // Create composite key for relationships
                AddCompositeKey = Table.AddColumn(UniqueRows, "ITEM_NUMBER_SITE_NUMBER_Key", each Text.Combine({[ITEM_NUMBER], [SITE_NUMBER]}, "|"), type text),
                // Filter out rows with null or empty composite keys
                FilteredRows = Table.SelectRows(AddCompositeKey, each [ITEM_NUMBER_SITE_NUMBER_Key] <> null and [ITEM_NUMBER_SITE_NUMBER_Key] <> "")
            in
                FilteredRows
        



    annotation PBI_ResultType = Table