table Dim_ITEM_SITE_EXTRACT_MANUFACTURER


    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER_Key'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER_Key

        

        annotation SummarizationSetBy = Automatic

        



    partition 'Dim_ITEM_SITE_EXTRACT_MANUFACTURER' = m
        mode: import
        source = 
            let
                // Get data from ITEM_SITE_EXTRACT
                Data_From_ITEM_SITE_EXTRACT = Table.SelectColumns(ITEM_SITE_EXTRACT, {"ITEM_NUMBER"}),
                // Get data from MANUFACTURER
                Data_From_MANUFACTURER = Table.SelectColumns(MANUFACTURER, {"ITEM_NUMBER"}),
                // Combine data from all source tables
                CombinedData = Table.Combine({Data_From_ITEM_SITE_EXTRACT, Data_From_MANUFACTURER}),
                // Get unique combinations of dimension keys
                UniqueRows = Table.Distinct(CombinedData, {"ITEM_NUMBER"}),
                // Create composite key for relationships
                AddCompositeKey = Table.AddColumn(UniqueRows, "ITEM_NUMBER_Key", each [ITEM_NUMBER], type text),
                // Filter out rows with null or empty composite keys
                FilteredRows = Table.SelectRows(AddCompositeKey, each [ITEM_NUMBER_Key] <> null and [ITEM_NUMBER_Key] <> "")
            in
                FilteredRows
        



    annotation PBI_ResultType = Table