table 'Custom SQL Query (dlh_nsec.objdb)'


    column 'weekday'
        dataType: int64
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            ISOWEEKDAY('Custom SQL Query (dlh_nsec.objdb)'[FISCAL_DATE])
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'max Week Flag'
        dataType: boolean
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            'Custom SQL Query (dlh_nsec.objdb)'[Calculation_1420604241837174785] = 'Custom SQL Query (dlh_nsec.objdb)'[Weekly count (copy)_1420604241838956546]
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Week Start Date'
        dataType: dateTime
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            VAR MinFiscalDate =
    MINX(
        FILTER(
            'Custom SQL Query (dlh_nsec.objdb)',
            'Custom SQL Query (dlh_nsec.objdb)'[FISCAL_WEEK] = VALUES('Custom SQL Query (dlh_nsec.objdb)'[FISCAL_WEEK])
        ),
        'Custom SQL Query (dlh_nsec.objdb)'[FISCAL_DATE]
    )
RETURN
    MinFiscalDate
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'diff flag'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            IF(
    'Custom SQL Query (dlh_nsec.objdb)'[Calculation_1420604241840762884] = 0,
    "Gold",
    IF(
        'Custom SQL Query (dlh_nsec.objdb)'[Calculation_1420604241840762884] > ('Parameters'[Parameter 1] / 100),
        "Flag",
        "Normal"
    )
)
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'help'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            'Help'
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Golden Date'
        dataType: dateTime
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            IF(
    'Custom SQL Query (dlh_nsec.objdb)'[Calculation_1420604241839083523],
    'Custom SQL Query (dlh_nsec.objdb)'[FISCAL_DATE],
    BLANK()
)
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Subject'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            "Data Load below " & FORMAT(LOOKUPVALUE('Custom SQL Query (dlh_nsec.objdb)'[Parameters].[Parameter 1], 'Custom SQL Query (dlh_nsec.objdb)'[Parameters], 'Custom SQL Query (dlh_nsec.objdb)'[Parameters].[Parameter 1]), "0%") & "% Of Golden Data Range"
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Avg Range'
        dataType: int64
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            INT('Custom SQL Query (dlh_nsec.objdb)'[AVG_DATA])
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Week End Date'
        dataType: dateTime
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            CALCULATE(
    MAX('Custom SQL Query (dlh_nsec.objdb)'[FISCAL_DATE]),
    VALUES('Custom SQL Query (dlh_nsec.objdb)'[FISCAL_WEEK])
)
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Tab_module'
        dataType: string
        summarizeBy: count
        sourceColumn: Tab_module

        
    column 'asup_date'
        dataType: string
        summarizeBy: count
        sourceColumn: asup_date

        
    column 'dt'
        dataType: string
        summarizeBy: count
        sourceColumn: dt

        
    column 'serial_count'
        dataType: int64
        summarizeBy: sum
        sourceColumn: serial_count

        
    column 'FISCAL_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: FISCAL_DATE

        
    column 'FISCAL_MONTH'
        dataType: string
        summarizeBy: count
        sourceColumn: FISCAL_MONTH

        
    column 'FISCAL_QTR'
        dataType: string
        summarizeBy: count
        sourceColumn: FISCAL_QTR

        
    column 'FISCAL_YEAR'
        dataType: string
        summarizeBy: count
        sourceColumn: FISCAL_YEAR

        
    column 'FISCAL_WEEK'
        dataType: string
        summarizeBy: count
        sourceColumn: FISCAL_WEEK

        
    column 'FT'
        dataType: string
        summarizeBy: count
        sourceColumn: FT

        
    column 'OBJ_SMF_TABLES'
        dataType: string
        summarizeBy: count
        sourceColumn: OBJ_SMF_TABLES

        
    column 'AVG_DATA'
        dataType: string
        summarizeBy: count
        sourceColumn: AVG_DATA

        
    column 'PUAT_Module'
        dataType: string
        summarizeBy: none
        sourceColumn: PUAT_Module

        

    measure 'Weekly count' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb)', { FIXED [FISCAL_WEEK]:SUM(IF [Calculation_1420604241832890368]=6 or [Calculation_1420604241832890368]=7 THEN [serial_count] END)})
			```

    measure '% diff' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb)', 1-[Calculation_1420604241837174785]/[Weekly count (copy)_1420604241838956546])
			```

    measure 'Body' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb)', "Date of Load "+STR(MIN([Calculation_1420604242555215877]))+"
"+
"System Count: "+STR(SUM(serial_count))+"

"

+"Golden Data Value: "+STR(MAX([Weekly count (copy)_1420604241838956546]))+"


"+
"
Regards,
PUAT Data Load")
			```

    measure '1500 flag' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb)', IF MIN([Calculation_1857734887845101576])-SUM([serial_count])>1500 THEN 'Flag'
ELSE 'Normal'
END)
			```

    measure 'Measure vs Golden' = ```
			/* Original TWB: MIN([Calculation_1857734887806193665])-SUM([serial_count]) */ MIN([Calculation_1857734887806193665])-SUM([serial_count])
			```

    measure 'Diffrence' = ```
			/* Original TWB: MIN([Calculation_1857734887845101576])-SUM([serial_count]) */ MIN([Calculation_1857734887845101576])-SUM([serial_count])
			```

    measure 'Max\Avg' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb)', IF [Parameters].[Parameter 3]='Max' THEN [Weekly count (copy)_1420604241838956546]
ELSEIF [Parameters].[Parameter 3]='Avg' THEN [Calculation_1857734887806193665] END)
			```

    measure 'Diffrence flag' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb)', IF  MIN([Calculation_1857734887845101576])-SUM([serial_count])>1500 THEN 'Flag'
ELSEIF MIN([Calculation_1857734887845101576])-SUM([serial_count])>=0 AND MIN([Calculation_1857734887845101576])-SUM([serial_count])<=1500 THEN 'Normal'
ELSEIF MIN([Calculation_1857734887845101576])-SUM([serial_count])<0 THEN 'Spike' END)
			```

    measure 'Max Weekly count' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb)', {MAX({ FIXED [FISCAL_WEEK]:SUM(IF [Calculation_1420604241832890368]=6 or [Calculation_1420604241832890368]=7 THEN [serial_count] END)})})
			```





