table 'Custom SQL Query (dlh_nsec.objdb) (2)'


    column 'Subject'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            "Data Load below " & CONVERT(VARCHAR, [Parameters].[Parameter 1]) & "% Of Golden Data Range"
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'asup date'
        dataType: dateTime
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            CALCULATE(
    SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_265993911338422272]),
    ALLSELECTED('Custom SQL Query (dlh_nsec.objdb) (2)')
)
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Weekday'
        dataType: int64
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            WEEKDAY('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970496946177], 2)
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Min Of Fis Week'
        dataType: dateTime
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            VAR MinCalc =
    MINX(
        FILTER(
            'Custom SQL Query (dlh_nsec.objdb) (2)',
            'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_265993911338422272] <> BLANK()
        ),
        'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_265993911338422272]
    )
RETURN
    CALCULATE(
        MinCalc,
        VALUES('Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_WEEK])
    )
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Avg Data by Module'
        dataType: int64
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            CALCULATE(
    MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1857734887858565133]),
    VALUES('Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module])
)
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Max Fiscal Week Measure'
        dataType: int64
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            VAR MaxFiscalWeek =
    CALCULATE(
        MAX('Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_WEEK]),
        ALLSELECTED('Custom SQL Query (dlh_nsec.objdb) (2)')
    )
RETURN
    IF(
        'Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_WEEK] = MaxFiscalWeek,
        'Custom SQL Query (dlh_nsec.objdb) (2)'[Measure],
        BLANK()
    )
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Avg Date'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            DATESBETWEEN(
    'Custom SQL Query (dlh_nsec.objdb) (2)'[Date],
    DATE(2023, 2, 24),
    DATE(2023, 3, 17)
)
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Week Num'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            SWITCH(
    WEEKNUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_265993911338422272], 2) - 'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893971550072860],
    0, "Week 1",
    1, "Week 2",
    2, "Week 3",
    3, "Week 4",
    4, "Week 5",
    5, "Week 6"
)
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Golden Data Label'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            'Custom SQL Query (dlh_nsec.objdb) (2)'[Parameters].[Parameter 3] & " Data Values"
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Data Load Metrics'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            'Custom SQL Query (dlh_nsec.objdb) (2)'[Data Load Values]
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'help'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            CALCULATE(
    COUNTROWS('Custom SQL Query (dlh_nsec.objdb) (2)'),
    FILTER(
        'Custom SQL Query (dlh_nsec.objdb) (2)',
        'Custom SQL Query (dlh_nsec.objdb) (2)'[help] = "help"
    )
)
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Max\Avg'
        dataType: int64
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            IF(
    'Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module] = "System" && 'Parameters'[Parameter 3] = "Max",
    'Custom SQL Query (dlh_nsec.objdb) (2)'[Max_data],
    INT('Custom SQL Query (dlh_nsec.objdb) (2)'[AVG_DATA])
)
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'tooltip'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            IF(
    'Custom SQL Query (dlh_nsec.objdb) (2)'[Parameters].[Parameter 3] = "Max",
    "Max Sys Count for Selected Duration",
    IF(
        'Custom SQL Query (dlh_nsec.objdb) (2)'[Parameters].[Parameter 3] = "Avg",
        "Avg Sys Count for last 4 weeks",
        BLANK()
    )
)
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Fiscal Date'
        dataType: dateTime
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            SWITCH(
    TRUE(),
    'Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_DATE] = #31-AUG-2024#, #01-SEP-2024#,
    'Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_DATE] = #01-DEC-2024#, #30-NOV-2024#,
    'Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_DATE]
)
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Period'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            'Custom SQL Query (dlh_nsec.objdb) (2)'[Data Load Time]
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Avg Week'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            VAR MinFiscalWeek =
    CALCULATE(
        MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_WEEK]),
        FILTER(
            'Custom SQL Query (dlh_nsec.objdb) (2)',
            'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970521313284] = 'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893971490320410]
        ),
        VALUES('Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module])
    )
RETURN
    MinFiscalWeek
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'MaxFiscal Week'
        dataType: boolean
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            MAX(
    CALCULATE(
        MAX('Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_WEEK]),
        VALUES('Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module])
    )
)
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'Max Of Fis Week'
        dataType: dateTime
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            CALCULATE(
    MAX('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_265993911338422272]),
    VALUES('Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_WEEK])
)
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic
        
    column 'PUAT_Module'
        dataType: string
        summarizeBy: count
        sourceColumn: PUAT_Module

        
    column 'asup_month'
        dataType: string
        summarizeBy: count
        sourceColumn: asup_month

        
    column 'date'
        dataType: string
        summarizeBy: count
        sourceColumn: date

        
    column 'Measure'
        dataType: int64
        summarizeBy: sum
        sourceColumn: Measure

        
    column 'FISCAL_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: FISCAL_DATE

        
    column 'FISCAL_MONTH'
        dataType: string
        summarizeBy: count
        sourceColumn: FISCAL_MONTH

        
    column 'FISCAL_QTR'
        dataType: string
        summarizeBy: count
        sourceColumn: FISCAL_QTR

        
    column 'FISCAL_YEAR'
        dataType: string
        summarizeBy: count
        sourceColumn: FISCAL_YEAR

        
    column 'FISCAL_WEEK'
        dataType: string
        summarizeBy: count
        sourceColumn: FISCAL_WEEK

        
    column 'FT'
        dataType: string
        summarizeBy: count
        sourceColumn: FT

        
    column 'OBJ_SMF_TABLES'
        dataType: string
        summarizeBy: count
        sourceColumn: OBJ_SMF_TABLES

        
    column 'AVG_DATA'
        dataType: string
        summarizeBy: count
        sourceColumn: AVG_DATA

        
    column 'Max_data'
        dataType: string
        summarizeBy: count
        sourceColumn: Max_data

        

    measure '% Prev Week Diff' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', 1-(LOOKUP(SUM([Measure]),-4)/SUM([Measure])))
			```

    measure 'dip flag' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', [Calculation_1704893970529177607]>[Parameters].[Parameter 1])
			```

    measure 'Avg Data?' = ```
			/* Original TWB: SUM([Measure])=SUM([Calculation_1704893970521313284]) */ SUM([Measure])=SUM([Calculation_1704893970521313284])
			```

    measure 'Golden Flag' = ```
			/* Original TWB: SUM([Measure])=SUM([Calculation_1704893970521313284]) */ SUM([Measure])=SUM([Calculation_1704893970521313284])
			```

    measure '% Diff' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF ATTR([PUAT_Module])!='System' THEN
-(1-(SUM([Measure])/MIN([Calculation_1704893970521313284]))) END)
			```

    measure 'diff flag' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', if [Calculation_1704893970529177607]=0 THEN 'Gold'
ELSEIF -([Calculation_1704893970529177607])>([Parameters].[Parameter 2]/100) THEN 'Flag'
ELSEIF  -([Calculation_1704893970529177607])<([Parameters].[Parameter 2]/100) THEN 'Normal' END)
			```

    measure 'unicode' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF [Calculation_1704893970530209800]='Flag' THEN '⚠' END)
			```

    measure 'size' = ```
			/* Original TWB: MIN(1) */ MIN(1)
			```

    measure 'flag diff' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', if [Calculation_1704893970529177607]<-([Parameters].[Parameter 2]/100) AND [Calculation_1704893970529177607]!=0 THEN [Calculation_1704893970529177607] END)
			```

    measure 'Table Measure' = ```
			/* Original TWB: SUM([Measure]) */ SUM([Measure])
			```

    measure 'up' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF ATTR([PUAT_Module])!='System' AND
SUM([Measure])>MIN([Calculation_1704893970521313284]) THEN '⬆' END)
			```

    measure 'axis' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', 1)
			```

    measure 'Module_Week Measure' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', { FIXED [PUAT_Module],[FISCAL_WEEK]:SUM([Measure])})
			```

    measure 'Diff vs Golden data' = ```
			/* Original TWB: MIN([Calculation_1704893970521313284])-SUM([Measure]) */ MIN([Calculation_1704893970521313284])-SUM([Measure])
			```

    measure 'Week-min' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', { FIXED MONTH([Calculation_265993911338422272]):MIN(DATEPART('week',[Calculation_265993911338422272]))})
			```

    measure 'Measure by Week' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', { FIXED [PUAT_Module],[Calculation_1704893971550199837]:SUM([Measure])})
			```

    measure 'dif b/w g&amp;m' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', 1-SUM([Measure])/MIN([Calculation_1704893970521313284]))
			```

    measure 'color legend' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF  [down (copy)_1857734887864430610]='⬇' THEN '0-'+STR([Parameters].[Parameter 4])+'dip'
ELSEIF [flag down  (copy)_1857734887864967187]='⬇' THEN '>'+STR([Parameters].[Parameter 4])+ 'dip'
ELSEIF [up (copy)_1857734887863640081]='⬆' THEN 'No dip '
ELSEIF [Calculation_1704893970529177607]>=0 AND [Calculation_1704893970529177607]<0.05 THEN '0-5%'
ELSEIF [Calculation_1704893970529177607]>=0.05 AND [Calculation_1704893970529177607]<0.1 THEN '5-10%'
ELSEIF [Calculation_1704893970529177607]>=0.1 AND [Calculation_1704893970529177607]<0.15 THEN '10-15%'
ELSEIF [Calculation_1704893970529177607]>=0.15 AND [Calculation_1704893970529177607]<0.2 THEN '15-20%'
ELSEIF [Calculation_1704893970529177607]>=0.2 AND [Calculation_1704893970529177607]<0.25 THEN '20-25%'
ELSEIF [Calculation_1704893970529177607]>=0.25 AND [Calculation_1704893970529177607]<0.3 THEN '25-30%'
ELSEIF [Calculation_1704893970529177607]>=0.3 THEN '>35%'
ELSEIF [Calculation_1704893970529177607]<0 AND [Calculation_1704893970529177607]>-0.05 THEN '-(0-5)%'
ELSEIF [Calculation_1704893970529177607]<=-0.05 AND [Calculation_1704893970529177607]>-0.1 THEN '-(5-10)%'
ELSEIF [Calculation_1704893970529177607]<=-0.1 AND [Calculation_1704893970529177607]>-0.15 THEN '-(10-15)%'
ELSEIF [Calculation_1704893970529177607]<=-0.15 AND [Calculation_1704893970529177607]>-0.2 THEN '-(15-20)%'
ELSEIF [Calculation_1704893970529177607]<=-0.2 AND [Calculation_1704893970529177607]>-0.25 THEN '-(20-25)%'
ELSEIF [Calculation_1704893970529177607]<=-0.25 AND [Calculation_1704893970529177607]>-0.3 THEN '-(25-30)%'
ELSEIF [Calculation_1704893970529177607]<=-0.3 THEN '< -35%'

 END)
			```

    measure 'System Diff' = ```
			/* Original TWB: SUM(IF [PUAT_Module]='System' THEN
[Measure] END)
-
MIN(IF [PUAT_Module]='System' THEN
[Calculation_1857734887858565133] END) */ SUM(IF [PUAT_Module]='System' THEN
[Measure] END)
-
MIN(IF [PUAT_Module]='System' THEN
[Calculation_1857734887858565133] END)
			```

    measure 'Golden diff system' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', if  ATTR([PUAT_Module])='System' AND
MIN([Calculation_1857734887858565133])-SUM([Measure])<-[Parameters].[Parameter 4]
 THEN -(MIN([Calculation_1857734887858565133])-SUM([Measure])) END)
			```

    measure 'Golden diff' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', if [Calculation_1704893970529177607]>=0.15 THEN [Calculation_1704893970529177607] END)
			```

    measure 'Normal diff system' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF ATTR([PUAT_Module])='System' AND
MIN([Calculation_1857734887858565133])-SUM([Measure])<[Parameters].[Parameter 4] AND
MIN([Calculation_1857734887858565133])-SUM([Measure])>=-[Parameters].[Parameter 4] THEN
MIN([Calculation_1857734887858565133])-SUM([Measure])
 END)
			```

    measure 'flag down ' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF ATTR([PUAT_Module])!='System' AND
SUM([Measure])<SUM([Calculation_1704893970521313284]) 
AND [Calculation_1704893970529177607]<-0.05
THEN '⬇' END)
			```

    measure 'down system' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF ATTR([PUAT_Module])='System' AND
MIN([Calculation_1857734887858565133])-SUM([Measure])>=0 AND
MIN([Calculation_1857734887858565133])-SUM([Measure])<=[Parameters].[Parameter 4] 
THEN '⬇' END)
			```

    measure 'Normal diff' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', if [Calculation_1704893970529177607]>=-([Parameters].[Parameter 2]/100) AND
[Calculation_1704893970529177607]<0.15
AND

[Calculation_1704893970529177607]!=0 THEN [Calculation_1704893970529177607] END)
			```

    measure 'flag diff system' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', if ATTR([PUAT_Module])='System' AND
MIN([Calculation_1857734887858565133])-SUM([Measure])>[Parameters].[Parameter 4] THEN 
MIN([Calculation_1857734887858565133])-SUM([Measure])
 END)
			```

    measure 'flag down system' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF ATTR([PUAT_Module])='System' AND
MIN([Calculation_1857734887858565133])-SUM([Measure])>[Parameters].[Parameter 4] 
THEN '⬇' END)
			```

    measure 'unicode system' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF  ATTR([PUAT_Module])='System' AND
MIN([Calculation_1857734887858565133])-SUM([Measure])>[Parameters].[Parameter 4]

 THEN '⚠' END)
			```

    measure 'up-System' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF ATTR([PUAT_Module])='System' AND
MIN([Calculation_1857734887858565133])-SUM([Measure])<0 
THEN '⬆' END)
			```

    measure 'down' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF ATTR([PUAT_Module])!='System' AND
SUM([Measure])<SUM([Calculation_1704893970521313284]) 
AND [Calculation_1704893970529177607]>-0.05
THEN '⬇' END)
			```





