table 'Custom SQL Query (dlh_nsec.objdb) (2)'


    column 'Subject'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: "Data Load below "+STR([Parameters].[Parameter 1])+"% Of Golden Data Range" */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'asup date'
        dataType: dateTime
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: [Calculation_265993911338422272] */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'Weekday'
        dataType: int64
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: DATEPART('weekday',[Calculation_1704893970496946177]) */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Min Of Fis Week'
        dataType: dateTime
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: { FIXED [FISCAL_WEEK]:MIN([Calculation_265993911338422272])} */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'Avg Data by Module'
        dataType: int64
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: { FIXED [PUAT_Module]:MIN([Calculation_1857734887858565133])} */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Max Fiscal Week Measure'
        dataType: int64
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: IF [FISCAL_WEEK]={MAX([FISCAL_WEEK])} THEN [Measure] END */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Avg Date'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: "from Feb 24 to Mar 17" */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'Week Num'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: CASE DATEPART('week',[Calculation_265993911338422272]) WHEN [Calculation_1704893971550072860] THEN "Week 1" 
WHEN [Calculation_1704893971550072860]+1 THEN "Week 2" 
WHEN [Calculation_1704893971550072860]+2 THEN "Week 3" 
WHEN [Calculation_1704893971550072860]+3 THEN "Week 4" 
WHEN [Calculation_1704893971550072860]+4 THEN "Week 5" 
WHEN [Calculation_1704893971550072860]+5 THEN "Week 6" END */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'Golden Data Label'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: [Parameters].[Parameter 3]+' Data Values' */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'Data Load Metrics'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: 'Data Load Values' */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'help'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: 'help' */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'Max\Avg'
        dataType: int64
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: IF [PUAT_Module]='System' AND [Parameters].[Parameter 3]='Max' THEN [Max_data]
ELSE INT([AVG_DATA]) END */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'tooltip'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: IF [Parameters].[Parameter 3]='Max' THEN 'Max Sys Count for Selected Duration'
ELSEIF [Parameters].[Parameter 3]='Avg' THEN 'Avg Sys Count for last 4 weeks' END */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'Fiscal Date'
        dataType: dateTime
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: IF [FISCAL_DATE]=#31-AUG-2024# THEN #01-SEP-2024#
ELSEIF [FISCAL_DATE]=#01-DEC-2024# THEN #30-NOV-2024#
ELSE [FISCAL_DATE] END */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'Period'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: 'Data Load Time' */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'Avg Week'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: { FIXED [PUAT_Module]:MIN(if [Calculation_1704893970521313284]=[Calculation_1704893971490320410] THEN [FISCAL_WEEK] END)} */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'MaxFiscal Week'
        dataType: boolean
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: [FISCAL_WEEK]={FIXED [PUAT_Module]: MAX([FISCAL_WEEK])} */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'Max Of Fis Week'
        dataType: dateTime
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: { FIXED [FISCAL_WEEK]:MAX([Calculation_265993911338422272])} */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'PUAT_Module'
        dataType: string
        summarizeBy: count
        sourceColumn: PUAT_Module

        annotation SummarizationSetBy = User

        
    column 'asup_month'
        dataType: string
        summarizeBy: count
        sourceColumn: asup_month

        annotation SummarizationSetBy = User

        
    column 'date'
        dataType: string
        summarizeBy: count
        sourceColumn: date

        annotation SummarizationSetBy = User

        
    column 'Measure'
        dataType: int64
        summarizeBy: sum
        sourceColumn: Measure

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'FISCAL_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: FISCAL_DATE

        annotation SummarizationSetBy = Automatic

        
    column 'FISCAL_MONTH'
        dataType: string
        summarizeBy: count
        sourceColumn: FISCAL_MONTH

        annotation SummarizationSetBy = User

        
    column 'FISCAL_QTR'
        dataType: string
        summarizeBy: count
        sourceColumn: FISCAL_QTR

        annotation SummarizationSetBy = User

        
    column 'FISCAL_YEAR'
        dataType: string
        summarizeBy: count
        sourceColumn: FISCAL_YEAR

        annotation SummarizationSetBy = User

        
    column 'FISCAL_WEEK'
        dataType: string
        summarizeBy: count
        sourceColumn: FISCAL_WEEK

        annotation SummarizationSetBy = User

        
    column 'FT'
        dataType: string
        summarizeBy: count
        sourceColumn: FT

        annotation SummarizationSetBy = User

        
    column 'OBJ_SMF_TABLES'
        dataType: string
        summarizeBy: count
        sourceColumn: OBJ_SMF_TABLES

        annotation SummarizationSetBy = User

        
    column 'AVG_DATA'
        dataType: string
        summarizeBy: count
        sourceColumn: AVG_DATA

        annotation SummarizationSetBy = User

        
    column 'Max_data'
        dataType: string
        summarizeBy: count
        sourceColumn: Max_data

        annotation SummarizationSetBy = User

        

    measure '% Prev Week Diff' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', 1-(LOOKUP(SUM([Measure]),-4)/SUM([Measure])))
			```

    measure 'dip flag' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', [Calculation_1704893970529177607]>[Parameters].[Parameter 1])
			```

    measure 'Avg Data?' = ```
			/* Original TWB: SUM([Measure])=SUM([Calculation_1704893970521313284]) */ SUM([Measure])=SUM([Calculation_1704893970521313284])
			```

    measure 'Golden Flag' = ```
			/* Original TWB: SUM([Measure])=SUM([Calculation_1704893970521313284]) */ SUM([Measure])=SUM([Calculation_1704893970521313284])
			```

    measure '% Diff' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF ATTR([PUAT_Module])!='System' THEN
-(1-(SUM([Measure])/MIN([Calculation_1704893970521313284]))) END)
			```

    measure 'diff flag' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', if [Calculation_1704893970529177607]=0 THEN 'Gold'
ELSEIF -([Calculation_1704893970529177607])>([Parameters].[Parameter 2]/100) THEN 'Flag'
ELSEIF  -([Calculation_1704893970529177607])<([Parameters].[Parameter 2]/100) THEN 'Normal' END)
			```

    measure 'unicode' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF [Calculation_1704893970530209800]='Flag' THEN '⚠' END)
			```

    measure 'size' = ```
			/* Original TWB: MIN(1) */ MIN(1)
			```

    measure 'flag diff' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', if [Calculation_1704893970529177607]<-([Parameters].[Parameter 2]/100) AND [Calculation_1704893970529177607]!=0 THEN [Calculation_1704893970529177607] END)
			```

    measure 'Table Measure' = ```
			/* Original TWB: SUM([Measure]) */ SUM([Measure])
			```

    measure 'up' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF ATTR([PUAT_Module])!='System' AND
SUM([Measure])>MIN([Calculation_1704893970521313284]) THEN '⬆' END)
			```

    measure 'axis' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', 1)
			```

    measure 'Module_Week Measure' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', { FIXED [PUAT_Module],[FISCAL_WEEK]:SUM([Measure])})
			```

    measure 'Diff vs Golden data' = ```
			/* Original TWB: MIN([Calculation_1704893970521313284])-SUM([Measure]) */ MIN([Calculation_1704893970521313284])-SUM([Measure])
			```

    measure 'Week-min' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', { FIXED MONTH([Calculation_265993911338422272]):MIN(DATEPART('week',[Calculation_265993911338422272]))})
			```

    measure 'Measure by Week' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', { FIXED [PUAT_Module],[Calculation_1704893971550199837]:SUM([Measure])})
			```

    measure 'dif b/w g&amp;m' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', 1-SUM([Measure])/MIN([Calculation_1704893970521313284]))
			```

    measure 'color legend' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF  [down (copy)_1857734887864430610]='⬇' THEN '0-'+STR([Parameters].[Parameter 4])+'dip'
ELSEIF [flag down  (copy)_1857734887864967187]='⬇' THEN '>'+STR([Parameters].[Parameter 4])+ 'dip'
ELSEIF [up (copy)_1857734887863640081]='⬆' THEN 'No dip '
ELSEIF [Calculation_1704893970529177607]>=0 AND [Calculation_1704893970529177607]<0.05 THEN '0-5%'
ELSEIF [Calculation_1704893970529177607]>=0.05 AND [Calculation_1704893970529177607]<0.1 THEN '5-10%'
ELSEIF [Calculation_1704893970529177607]>=0.1 AND [Calculation_1704893970529177607]<0.15 THEN '10-15%'
ELSEIF [Calculation_1704893970529177607]>=0.15 AND [Calculation_1704893970529177607]<0.2 THEN '15-20%'
ELSEIF [Calculation_1704893970529177607]>=0.2 AND [Calculation_1704893970529177607]<0.25 THEN '20-25%'
ELSEIF [Calculation_1704893970529177607]>=0.25 AND [Calculation_1704893970529177607]<0.3 THEN '25-30%'
ELSEIF [Calculation_1704893970529177607]>=0.3 THEN '>35%'
ELSEIF [Calculation_1704893970529177607]<0 AND [Calculation_1704893970529177607]>-0.05 THEN '-(0-5)%'
ELSEIF [Calculation_1704893970529177607]<=-0.05 AND [Calculation_1704893970529177607]>-0.1 THEN '-(5-10)%'
ELSEIF [Calculation_1704893970529177607]<=-0.1 AND [Calculation_1704893970529177607]>-0.15 THEN '-(10-15)%'
ELSEIF [Calculation_1704893970529177607]<=-0.15 AND [Calculation_1704893970529177607]>-0.2 THEN '-(15-20)%'
ELSEIF [Calculation_1704893970529177607]<=-0.2 AND [Calculation_1704893970529177607]>-0.25 THEN '-(20-25)%'
ELSEIF [Calculation_1704893970529177607]<=-0.25 AND [Calculation_1704893970529177607]>-0.3 THEN '-(25-30)%'
ELSEIF [Calculation_1704893970529177607]<=-0.3 THEN '< -35%'

 END)
			```

    measure 'System Diff' = ```
			/* Original TWB: SUM(IF [PUAT_Module]='System' THEN
[Measure] END)
-
MIN(IF [PUAT_Module]='System' THEN
[Calculation_1857734887858565133] END) */ SUM(IF [PUAT_Module]='System' THEN
[Measure] END)
-
MIN(IF [PUAT_Module]='System' THEN
[Calculation_1857734887858565133] END)
			```

    measure 'Golden diff system' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', if  ATTR([PUAT_Module])='System' AND
MIN([Calculation_1857734887858565133])-SUM([Measure])<-[Parameters].[Parameter 4]
 THEN -(MIN([Calculation_1857734887858565133])-SUM([Measure])) END)
			```

    measure 'Golden diff' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', if [Calculation_1704893970529177607]>=0.15 THEN [Calculation_1704893970529177607] END)
			```

    measure 'Normal diff system' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF ATTR([PUAT_Module])='System' AND
MIN([Calculation_1857734887858565133])-SUM([Measure])<[Parameters].[Parameter 4] AND
MIN([Calculation_1857734887858565133])-SUM([Measure])>=-[Parameters].[Parameter 4] THEN
MIN([Calculation_1857734887858565133])-SUM([Measure])
 END)
			```

    measure 'flag down ' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF ATTR([PUAT_Module])!='System' AND
SUM([Measure])<SUM([Calculation_1704893970521313284]) 
AND [Calculation_1704893970529177607]<-0.05
THEN '⬇' END)
			```

    measure 'down system' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF ATTR([PUAT_Module])='System' AND
MIN([Calculation_1857734887858565133])-SUM([Measure])>=0 AND
MIN([Calculation_1857734887858565133])-SUM([Measure])<=[Parameters].[Parameter 4] 
THEN '⬇' END)
			```

    measure 'Normal diff' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', if [Calculation_1704893970529177607]>=-([Parameters].[Parameter 2]/100) AND
[Calculation_1704893970529177607]<0.15
AND

[Calculation_1704893970529177607]!=0 THEN [Calculation_1704893970529177607] END)
			```

    measure 'flag diff system' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', if ATTR([PUAT_Module])='System' AND
MIN([Calculation_1857734887858565133])-SUM([Measure])>[Parameters].[Parameter 4] THEN 
MIN([Calculation_1857734887858565133])-SUM([Measure])
 END)
			```

    measure 'flag down system' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF ATTR([PUAT_Module])='System' AND
MIN([Calculation_1857734887858565133])-SUM([Measure])>[Parameters].[Parameter 4] 
THEN '⬇' END)
			```

    measure 'unicode system' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF  ATTR([PUAT_Module])='System' AND
MIN([Calculation_1857734887858565133])-SUM([Measure])>[Parameters].[Parameter 4]

 THEN '⚠' END)
			```

    measure 'up-System' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF ATTR([PUAT_Module])='System' AND
MIN([Calculation_1857734887858565133])-SUM([Measure])<0 
THEN '⬆' END)
			```

    measure 'down' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb) (2)', IF ATTR([PUAT_Module])!='System' AND
SUM([Measure])<SUM([Calculation_1704893970521313284]) 
AND [Calculation_1704893970529177607]>-0.05
THEN '⬇' END)
			```





    annotation PBI_ResultType = Table
