table 'Custom SQL Query (dlh_nsec.objdb)'


    column 'weekday' = ```
            ISOWEEKDAY('Custom SQL Query (dlh_nsec.objdb)'[FISCAL_DATE])
    ```
        dataType: int64
        summarizeBy: sum

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'max Week Flag' = ```
            'Custom SQL Query (dlh_nsec.objdb)'[Calculation_1420604241837174785] = 'Custom SQL Query (dlh_nsec.objdb)'[Weekly count (copy)_1420604241838956546]
    ```
        dataType: boolean
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Week Start Date' = ```
            VAR MinFiscalDate =
    MINX(
        FILTER(
            'Custom SQL Query (dlh_nsec.objdb)',
            ALLEXCEPT('Custom SQL Query (dlh_nsec.objdb)', 'Custom SQL Query (dlh_nsec.objdb)'[FISCAL_WEEK])
        ),
        'Custom SQL Query (dlh_nsec.objdb)'[FISCAL_DATE]
    )
RETURN
    CALCULATE(
        MinFiscalDate,
        VALUES('Custom SQL Query (dlh_nsec.objdb)'[FISCAL_WEEK])
    )
    ```
        dataType: dateTime
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'diff flag' = ```
            IF(
    'Custom SQL Query (dlh_nsec.objdb)'[Calculation_1420604241840762884] = 0,
    "Gold",
    IF(
        'Custom SQL Query (dlh_nsec.objdb)'[Calculation_1420604241840762884] > ('Parameters'[Parameter 1] / 100),
        "Flag",
        "Normal"
    )
)
    ```
        dataType: string
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'help' = ```
            'Help'
    ```
        dataType: string
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Golden Date' = ```
            IF(
    'Custom SQL Query (dlh_nsec.objdb)'[Calculation_1420604241839083523],
    'Custom SQL Query (dlh_nsec.objdb)'[FISCAL_DATE],
    BLANK()
)
    ```
        dataType: dateTime
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Subject' = ```
            "Data Load below " & FORMAT(LOOKUPVALUE('Custom SQL Query (dlh_nsec.objdb)'[Parameters], 'Custom SQL Query (dlh_nsec.objdb)'[Parameters], "Parameter 1"), "0%") & "% Of Golden Data Range"
    ```
        dataType: string
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Avg Range' = ```
            INT('Custom SQL Query (dlh_nsec.objdb)'[AVG_DATA])
    ```
        dataType: int64
        summarizeBy: sum

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Week End Date' = ```
            CALCULATE(
    MAX('Custom SQL Query (dlh_nsec.objdb)'[FISCAL_DATE]),
    VALUES('Custom SQL Query (dlh_nsec.objdb)'[FISCAL_WEEK])
)
    ```
        dataType: dateTime
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Tab_module'
        dataType: string
        summarizeBy: none
        sourceColumn: Tab_module

        annotation SummarizationSetBy = Automatic

        
    column 'asup_date'
        dataType: string
        summarizeBy: none
        sourceColumn: asup_date

        annotation SummarizationSetBy = Automatic

        
    column 'dt'
        dataType: string
        summarizeBy: none
        sourceColumn: dt

        annotation SummarizationSetBy = Automatic

        
    column 'serial_count'
        dataType: int64
        summarizeBy: sum
        sourceColumn: serial_count

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'FISCAL_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: FISCAL_DATE

        annotation SummarizationSetBy = Automatic

        
    column 'FISCAL_MONTH'
        dataType: string
        summarizeBy: none
        sourceColumn: FISCAL_MONTH

        annotation SummarizationSetBy = Automatic

        
    column 'FISCAL_QTR'
        dataType: string
        summarizeBy: none
        sourceColumn: FISCAL_QTR

        annotation SummarizationSetBy = Automatic

        
    column 'FISCAL_YEAR'
        dataType: string
        summarizeBy: none
        sourceColumn: FISCAL_YEAR

        annotation SummarizationSetBy = Automatic

        
    column 'FISCAL_WEEK'
        dataType: string
        summarizeBy: none
        sourceColumn: FISCAL_WEEK

        annotation SummarizationSetBy = Automatic

        
    column 'FT'
        dataType: string
        summarizeBy: none
        sourceColumn: FT

        annotation SummarizationSetBy = Automatic

        
    column 'OBJ_SMF_TABLES'
        dataType: string
        summarizeBy: none
        sourceColumn: OBJ_SMF_TABLES

        annotation SummarizationSetBy = Automatic

        
    column 'AVG_DATA'
        dataType: string
        summarizeBy: none
        sourceColumn: AVG_DATA

        annotation SummarizationSetBy = Automatic

        

    measure 'Weekly count' = ```
            CALCULATE(
    SUM(
        IF(
            'Custom SQL Query (dlh_nsec.objdb)'[Calculation_1420604241832890368] = 6
            || 'Custom SQL Query (dlh_nsec.objdb)'[Calculation_1420604241832890368] = 7,
            'Custom SQL Query (dlh_nsec.objdb)'[serial_count],
            BLANK()
        )
    ),
    VALUES('Custom SQL Query (dlh_nsec.objdb)'[FISCAL_WEEK])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure '% diff' = ```
            1 - 'Custom SQL Query (dlh_nsec.objdb)'[Calculation_1420604241837174785] / 'Custom SQL Query (dlh_nsec.objdb)'[Weekly count (copy)_1420604241838956546]
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Body' = ```
            "Date of Load " &
MIN('Custom SQL Query (dlh_nsec.objdb)'[Calculation_1420604242555215877]) &
"
System Count: " &
SUM('Custom SQL Query (dlh_nsec.objdb)'[serial_count]) &
"
Golden Data Value: " &
MAX('Custom SQL Query (dlh_nsec.objdb)'[Weekly count (copy)_1420604241838956546]) &
"

Regards,
PUAT Data Load"
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure '1500 flag' = ```
            IF(
    MIN('Custom SQL Query (dlh_nsec.objdb)'[Calculation_1857734887845101576]) - SUM('Custom SQL Query (dlh_nsec.objdb)'[serial_count]) > 1500,
    "Flag",
    "Normal"
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Measure vs Golden' = ```
            MIN('Custom SQL Query (dlh_nsec.objdb)'[Calculation_1857734887806193665]) - SUM('Custom SQL Query (dlh_nsec.objdb)'[serial_count])
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Diffrence' = ```
            MIN('Custom SQL Query (dlh_nsec.objdb)'[Calculation_1857734887845101576]) - SUM('Custom SQL Query (dlh_nsec.objdb)'[serial_count])
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Max\Avg' = ```
            IF(
    'Custom SQL Query (dlh_nsec.objdb)'[Parameters].[Parameter 3] = 'Max',
    'Custom SQL Query (dlh_nsec.objdb)'[Weekly count (copy)_1420604241838956546],
    IF(
        'Custom SQL Query (dlh_nsec.objdb)'[Parameters].[Parameter 3] = 'Avg',
        'Custom SQL Query (dlh_nsec.objdb)'[Calculation_1857734887806193665],
        BLANK()
    )
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Diffrence flag' = ```
            VAR MinCalc = MINX('Custom SQL Query (dlh_nsec.objdb)', 'Custom SQL Query (dlh_nsec.objdb)'[Calculation_1857734887845101576])
VAR SumSerialCount = SUM('Custom SQL Query (dlh_nsec.objdb)'[serial_count])
RETURN
    IF (
        MinCalc - SumSerialCount > 1500,
        "Flag",
        IF (
            MinCalc - SumSerialCount >= 0 && MinCalc - SumSerialCount <= 1500,
            "Normal",
            "Spike"
        )
    )
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Max Weekly count' = ```
            CALCULATE(
    MAX('Custom SQL Query (dlh_nsec.objdb)'[serial_count]),
    FILTER(
        'Custom SQL Query (dlh_nsec.objdb)',
        'Custom SQL Query (dlh_nsec.objdb)'[Calculation_1420604241832890368] = 6 || 'Custom SQL Query (dlh_nsec.objdb)'[Calculation_1420604241832890368] = 7
    ),
    VALUES('Custom SQL Query (dlh_nsec.objdb)'[FISCAL_WEEK])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'Custom SQL Query (dlh_nsec.objdb)' = m
        mode: import
        source = 
            	let
					Source = Dremio.Database(
					[
					ServerAddress="dlh-prd.corp.netapp.com:31011",
					DatabaseName="DREMIO",
					Authentication="auth-user-pass",
					Username="hshaik@netapp.com",
					CreateNavigationProperties=true
					],
					[
					HierarchicalNavigation=true,
					Query="select * from `dlh_nsec.objdb`"
					]),
					#"Navigation" = Source{[Name="dlh_nsec.objdb"]}[Data]
				in
					#"Navigation"
        



    annotation PBI_ResultType = Table
