table 'Custom SQL Query (dlh_nsec.objdb) (2)'


    column 'Subject' = ```
            "Data Load below " & CONVERT(VARCHAR, [Parameters].[Parameter 1]) & "% Of Golden Data Range"
    ```
        dataType: string
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'asup date' = ```
            CALCULATE(
    SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_265993911338422272]),
    ALLSELECTED('Custom SQL Query (dlh_nsec.objdb) (2)')
)
    ```
        dataType: dateTime
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Weekday' = ```
            WEEKDAY('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970496946177], 2)
    ```
        dataType: int64
        summarizeBy: sum

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Min Of Fis Week' = ```
            CALCULATE(
    MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_265993911338422272]),
    VALUES('Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_WEEK])
)
    ```
        dataType: dateTime
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Avg Data by Module' = ```
            CALCULATE(
    MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1857734887858565133]),
    VALUES('Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module])
)
    ```
        dataType: int64
        summarizeBy: sum

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Max Fiscal Week Measure' = ```
            VAR MaxFiscalWeek =
    CALCULATE(
        MAX('Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_WEEK]),
        ALLSELECTED('Custom SQL Query (dlh_nsec.objdb) (2)')
    )
RETURN
    IF(
        'Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_WEEK] = MaxFiscalWeek,
        'Custom SQL Query (dlh_nsec.objdb) (2)'[Measure],
        BLANK()
    )
    ```
        dataType: int64
        summarizeBy: sum

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Avg Date' = ```
            DATESBETWEEN(
    'Custom SQL Query (dlh_nsec.objdb) (2)'[Date],
    DATE(2023, 2, 24),
    DATE(2023, 3, 17)
)
    ```
        dataType: string
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Week Num' = ```
            SWITCH(
    WEEKNUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_265993911338422272], 2) - 'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893971550072860],
    0, "Week 1",
    1, "Week 2",
    2, "Week 3",
    3, "Week 4",
    4, "Week 5",
    5, "Week 6"
)
    ```
        dataType: string
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Golden Data Label' = ```
            'Custom SQL Query (dlh_nsec.objdb) (2)'[Parameters].[Parameter 3] & " Data Values"
    ```
        dataType: string
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Data Load Metrics' = ```
            'Custom SQL Query (dlh_nsec.objdb) (2)'[Data Load Values]
    ```
        dataType: string
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'help' = ```
            "help"
    ```
        dataType: string
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Max\Avg' = ```
            IF(
    'Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module] = "System" && 'Parameters'[Parameter 3] = "Max",
    'Custom SQL Query (dlh_nsec.objdb) (2)'[Max_data],
    INT('Custom SQL Query (dlh_nsec.objdb) (2)'[AVG_DATA])
)
    ```
        dataType: int64
        summarizeBy: sum

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'tooltip' = ```
            IF(
    'Custom SQL Query (dlh_nsec.objdb) (2)'[Parameters].[Parameter 3] = "Max",
    "Max Sys Count for Selected Duration",
    IF(
        'Custom SQL Query (dlh_nsec.objdb) (2)'[Parameters].[Parameter 3] = "Avg",
        "Avg Sys Count for last 4 weeks",
        BLANK()
    )
)
    ```
        dataType: string
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Fiscal Date' = ```
            SWITCH(
    TRUE(),
    'Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_DATE] = #31-AUG-2024#, #01-SEP-2024#,
    'Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_DATE] = #01-DEC-2024#, #30-NOV-2024#,
    'Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_DATE]
)
    ```
        dataType: dateTime
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Period' = ```
            'Custom SQL Query (dlh_nsec.objdb) (2)'[Data Load Time]
    ```
        dataType: string
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Avg Week' = ```
            VAR MinFiscalWeek =
    CALCULATE(
        MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_WEEK]),
        FILTER(
            'Custom SQL Query (dlh_nsec.objdb) (2)',
            'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970521313284] = 'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893971490320410]
        ),
        VALUES('Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module])
    )
RETURN
    MinFiscalWeek
    ```
        dataType: string
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'MaxFiscal Week' = ```
            MAX(
    CALCULATE(
        MAX('Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_WEEK]),
        VALUES('Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module])
    )
)
    ```
        dataType: boolean
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Max Of Fis Week' = ```
            CALCULATE(
    MAX('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_265993911338422272]),
    VALUES('Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_WEEK])
)
    ```
        dataType: dateTime
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'PUAT_Module'
        dataType: string
        summarizeBy: none
        sourceColumn: PUAT_Module

        annotation SummarizationSetBy = Automatic

        
    column 'asup_month'
        dataType: string
        summarizeBy: none
        sourceColumn: asup_month

        annotation SummarizationSetBy = Automatic

        
    column 'date'
        dataType: string
        summarizeBy: none
        sourceColumn: date

        annotation SummarizationSetBy = Automatic

        
    column 'Measure'
        dataType: int64
        summarizeBy: sum
        sourceColumn: Measure

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'FISCAL_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: FISCAL_DATE

        annotation SummarizationSetBy = Automatic

        
    column 'FISCAL_MONTH'
        dataType: string
        summarizeBy: none
        sourceColumn: FISCAL_MONTH

        annotation SummarizationSetBy = Automatic

        
    column 'FISCAL_QTR'
        dataType: string
        summarizeBy: none
        sourceColumn: FISCAL_QTR

        annotation SummarizationSetBy = Automatic

        
    column 'FISCAL_YEAR'
        dataType: string
        summarizeBy: none
        sourceColumn: FISCAL_YEAR

        annotation SummarizationSetBy = Automatic

        
    column 'FISCAL_WEEK'
        dataType: string
        summarizeBy: none
        sourceColumn: FISCAL_WEEK

        annotation SummarizationSetBy = Automatic

        
    column 'FT'
        dataType: string
        summarizeBy: none
        sourceColumn: FT

        annotation SummarizationSetBy = Automatic

        
    column 'OBJ_SMF_TABLES'
        dataType: string
        summarizeBy: none
        sourceColumn: OBJ_SMF_TABLES

        annotation SummarizationSetBy = Automatic

        
    column 'AVG_DATA'
        dataType: string
        summarizeBy: none
        sourceColumn: AVG_DATA

        annotation SummarizationSetBy = Automatic

        
    column 'Max_data'
        dataType: string
        summarizeBy: none
        sourceColumn: Max_data

        annotation SummarizationSetBy = Automatic

        

    measure '% Prev Week Diff' = ```
            1 - (
    CALCULATE(
        SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]),
        FILTER(
            'Custom SQL Query (dlh_nsec.objdb) (2)',
            COUNTROWS(VALUES('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure])) = -4
        )
    ) / SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'dip flag' = ```
            IF('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607] > 'Custom SQL Query (dlh_nsec.objdb) (2)'[Parameters].[Parameter 1], TRUE(), FALSE())
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Avg Data?' = ```
            SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]) = SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970521313284])
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Golden Flag' = ```
            SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]) = SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970521313284])
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure '% Diff' = ```
            IF (
    'Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module] <> "System",
    -(1 - (SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]) / MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970521313284]))),
    BLANK()
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'diff flag' = ```
            VAR Parameter2Value = 'Parameters'[Parameter 2] / 100
RETURN
    IF(
        'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607] = 0,
        "Gold",
        IF(
            -('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607]) > Parameter2Value,
            "Flag",
            IF(
                -('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607]) < Parameter2Value,
                "Normal",
                BLANK()
            )
        )
    )
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'unicode' = ```
            IF(
    'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970530209800] = "Flag",
    "⚠",
    BLANK()
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'size' = ```
            MIN(1)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'flag diff' = ```
            IF(
    'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607] < -('Parameters'[Parameter 2] / 100)
        && 'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607] != 0,
    'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607],
    BLANK()
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Table Measure' = ```
            SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure])
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'up' = ```
            IF (
    'Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module] <> "System"
        && SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]) > CALCULATE(
            MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970521313284]),
            ALLSELECTED('Custom SQL Query (dlh_nsec.objdb) (2)')
        ),
    "⬆",
    BLANK()
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'axis' = ```
            1
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Module_Week Measure' = ```
            CALCULATE(
    SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]),
    VALUES('Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module]),
    VALUES('Custom SQL Query (dlh_nsec.objdb) (2)'[FISCAL_WEEK])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Diff vs Golden data' = ```
            MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970521313284]) - SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure])
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Week-min' = ```
            VAR MinWeekNum = MINX(
    CALCULATETABLE(
        DISTINCT('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_265993911338422272]),
        REMOVEFILTERS('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_265993911338422272])
    ),
    WEEKNUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_265993911338422272], 2)
)
RETURN
    CALCULATE(
        MinWeekNum,
        DATESBETWEEN(
            'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_265993911338422272],
            STARTOFMONTH('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_265993911338422272]),
            ENDOFMONTH('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_265993911338422272])
        )
    )
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Measure by Week' = ```
            CALCULATE(
    SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]),
    VALUES('Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module]),
    VALUES('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893971550199837])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'dif b/w g&amp;m' = ```
            1 - SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]) / MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970521313284])
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'color legend' = ```
            IF(
    'Custom SQL Query (dlh_nsec.objdb) (2)'[down (copy)_1857734887864430610] = "⬇",
    "0-" + FORMAT('Custom SQL Query (dlh_nsec.objdb) (2)'[Parameters].[Parameter 4], "0") + "dip",
    IF(
        'Custom SQL Query (dlh_nsec.objdb) (2)'[flag down  (copy)_1857734887864967187] = "⬇",
        ">" + FORMAT('Custom SQL Query (dlh_nsec.objdb) (2)'[Parameters].[Parameter 4], "0") + "dip",
        IF(
            'Custom SQL Query (dlh_nsec.objdb) (2)'[up (copy)_1857734887863640081] = "⬆",
            "No dip ",
            IF(
                'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607] >= 0 && 'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607] < 0.05,
                "0-5%",
                IF(
                    'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607] >= 0.05 && 'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607] < 0.1,
                    "5-10%",
                    IF(
                        'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607] >= 0.1 && 'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607] < 0.15,
                        "10-15%",
                        IF(
                            'Custom SQL Query (dlh_nsec.objdb) (
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'System Diff' = ```
            SUM(
    IF(
        'Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module] = "System",
        'Custom SQL Query (dlh_nsec.objdb) (2)'[Measure],
        BLANK()
    )
) -
MIN(
    IF(
        'Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module] = "System",
        'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1857734887858565133],
        BLANK()
    )
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Golden diff system' = ```
            IF(
    'Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module] = "System"
        && MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1857734887858565133]) - SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]) < -[Parameters].[Parameter 4],
    -(MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1857734887858565133]) - SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure])),
    BLANK()
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Golden diff' = ```
            IF(
    'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607] >= 0.15,
    'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607],
    BLANK()
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Normal diff system' = ```
            IF(
    'Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module] = "System"
        && MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1857734887858565133]) - SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]) < [Parameters].[Parameter 4]
        && MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1857734887858565133]) - SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]) >= -[Parameters].[Parameter 4],
    MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1857734887858565133]) - SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]),
    BLANK()
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'flag down ' = ```
            IF (
    'Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module] <> "System"
    && SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]) < SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970521313284])
    && 'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607] < -0.05,
    "⬇",
    BLANK()
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'down system' = ```
            IF (
    'Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module] = "System"
        && MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1857734887858565133]) - SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]) >= 0
        && MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1857734887858565133]) - SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]) <= [Parameters].[Parameter 4],
    "⬇",
    BLANK()
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Normal diff' = ```
            IF(
    'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607] >= -('Parameters'[Parameter 2] / 100)
    && 'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607] < 0.15
    && 'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607] != 0,
    'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607],
    BLANK()
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'flag diff system' = ```
            IF (
    'Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module] = "System"
        && MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1857734887858565133]) - SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]) > [Parameters].[Parameter 4],
    MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1857734887858565133]) - SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]),
    BLANK()
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'flag down system' = ```
            IF (
    'Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module] = "System"
        && MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1857734887858565133]) - SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]) > [Parameters].[Parameter 4],
    "⬇",
    BLANK()
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'unicode system' = ```
            IF (
    'Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module] = "System"
        && MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1857734887858565133]) - SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]) > [Parameters].[Parameter 4],
    "⚠",
    BLANK()
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'up-System' = ```
            IF (
    'Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module] = "System"
        && MIN('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1857734887858565133]) - SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]) < 0,
    "⬆",
    BLANK()
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'down' = ```
            IF (
    'Custom SQL Query (dlh_nsec.objdb) (2)'[PUAT_Module] <> "System"
    && SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Measure]) < SUM('Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970521313284])
    && 'Custom SQL Query (dlh_nsec.objdb) (2)'[Calculation_1704893970529177607] > -0.05,
    "⬇",
    BLANK()
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'Custom SQL Query (dlh_nsec.objdb) (2)' = m
        mode: import
        source = 
            	let
					Source = Dremio.Database(
					[
					ServerAddress="dlh-prd.corp.netapp.com:31011",
					DatabaseName="DREMIO",
					Authentication="auth-user-pass",
					Username="hshaik@netapp.com",
					CreateNavigationProperties=true
					], [
					HierarchicalNavigation=true
					]),
					dlh_nsec_objdb = Source{[Schema="dlh_nsec.objdb",Kind="Schema"]}[Data]
				in
					dlh_nsec_objdb
        



    annotation PBI_ResultType = Table
