table 'Custom SQL Query (dlh_nsec.objdb)'


    column 'weekday'
        dataType: int64
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: ISOWEEKDAY([FISCAL_DATE]) */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'max Week Flag'
        dataType: boolean
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: [Calculation_1420604241837174785]=[Weekly count (copy)_1420604241838956546] */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'Week Start Date'
        dataType: dateTime
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: { FIXED [FISCAL_WEEK]:MIN([FISCAL_DATE])} */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'diff flag'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: if [Calculation_1420604241840762884]=0 THEN 'Gold'
ELSEIF ([Calculation_1420604241840762884])>([Parameters].[Parameter 1]/100) THEN 'Flag'
ELSEIF  ([Calculation_1420604241840762884])<([Parameters].[Parameter 1]/100) THEN 'Normal' END */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'help'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: 'Help' */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'Golden Date'
        dataType: dateTime
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: IF [Calculation_1420604241839083523]=TRUE then [FISCAL_DATE] END */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'Subject'
        dataType: string
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: "Data Load below "+STR([Parameters].[Parameter 1])+"% Of Golden Data Range" */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'Avg Range'
        dataType: int64
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: INT([AVG_DATA]) */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Week End Date'
        dataType: dateTime
        summarizeBy: none
        type: calculated
        sourceColumn = ```
            
            /* ERROR: Could not convert Tableau formula: { FIXED [FISCAL_WEEK]:MAX([FISCAL_DATE])} */
/* Error details: [WinError 10061] No connection could be made because the target machine actively refused it */
ERROR("Conversion failed")
            
            ```

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        
    column 'Tab_module'
        dataType: string
        summarizeBy: count
        sourceColumn: Tab_module

        annotation SummarizationSetBy = User

        
    column 'asup_date'
        dataType: string
        summarizeBy: count
        sourceColumn: asup_date

        annotation SummarizationSetBy = User

        
    column 'dt'
        dataType: string
        summarizeBy: count
        sourceColumn: dt

        annotation SummarizationSetBy = User

        
    column 'serial_count'
        dataType: int64
        summarizeBy: sum
        sourceColumn: serial_count

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'FISCAL_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: FISCAL_DATE

        annotation SummarizationSetBy = Automatic

        
    column 'FISCAL_MONTH'
        dataType: string
        summarizeBy: count
        sourceColumn: FISCAL_MONTH

        annotation SummarizationSetBy = User

        
    column 'FISCAL_QTR'
        dataType: string
        summarizeBy: count
        sourceColumn: FISCAL_QTR

        annotation SummarizationSetBy = User

        
    column 'FISCAL_YEAR'
        dataType: string
        summarizeBy: count
        sourceColumn: FISCAL_YEAR

        annotation SummarizationSetBy = User

        
    column 'FISCAL_WEEK'
        dataType: string
        summarizeBy: count
        sourceColumn: FISCAL_WEEK

        annotation SummarizationSetBy = User

        
    column 'FT'
        dataType: string
        summarizeBy: count
        sourceColumn: FT

        annotation SummarizationSetBy = User

        
    column 'OBJ_SMF_TABLES'
        dataType: string
        summarizeBy: count
        sourceColumn: OBJ_SMF_TABLES

        annotation SummarizationSetBy = User

        
    column 'AVG_DATA'
        dataType: string
        summarizeBy: count
        sourceColumn: AVG_DATA

        annotation SummarizationSetBy = User

        

    measure 'Weekly count' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb)', { FIXED [FISCAL_WEEK]:SUM(IF [Calculation_1420604241832890368]=6 or [Calculation_1420604241832890368]=7 THEN [serial_count] END)})
			```

    measure '% diff' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb)', 1-[Calculation_1420604241837174785]/[Weekly count (copy)_1420604241838956546])
			```

    measure 'Body' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb)', "Date of Load "+STR(MIN([Calculation_1420604242555215877]))+"
"+
"System Count: "+STR(SUM(serial_count))+"

"

+"Golden Data Value: "+STR(MAX([Weekly count (copy)_1420604241838956546]))+"


"+
"
Regards,
PUAT Data Load")
			```

    measure '1500 flag' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb)', IF MIN([Calculation_1857734887845101576])-SUM([serial_count])>1500 THEN 'Flag'
ELSE 'Normal'
END)
			```

    measure 'Measure vs Golden' = ```
			/* Original TWB: MIN([Calculation_1857734887806193665])-SUM([serial_count]) */ MIN([Calculation_1857734887806193665])-SUM([serial_count])
			```

    measure 'Diffrence' = ```
			/* Original TWB: MIN([Calculation_1857734887845101576])-SUM([serial_count]) */ MIN([Calculation_1857734887845101576])-SUM([serial_count])
			```

    measure 'Max\Avg' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb)', IF [Parameters].[Parameter 3]='Max' THEN [Weekly count (copy)_1420604241838956546]
ELSEIF [Parameters].[Parameter 3]='Avg' THEN [Calculation_1857734887806193665] END)
			```

    measure 'Diffrence flag' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb)', IF  MIN([Calculation_1857734887845101576])-SUM([serial_count])>1500 THEN 'Flag'
ELSEIF MIN([Calculation_1857734887845101576])-SUM([serial_count])>=0 AND MIN([Calculation_1857734887845101576])-SUM([serial_count])<=1500 THEN 'Normal'
ELSEIF MIN([Calculation_1857734887845101576])-SUM([serial_count])<0 THEN 'Spike' END)
			```

    measure 'Max Weekly count' = ```
			SUMX('Custom SQL Query (dlh_nsec.objdb)', {MAX({ FIXED [FISCAL_WEEK]:SUM(IF [Calculation_1420604241832890368]=6 or [Calculation_1420604241832890368]=7 THEN [serial_count] END)})})
			```





    annotation PBI_ResultType = Table
