table 'Sheet1 (Ticket_tracker)'


    column 'Table Name'
        dataType: string
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        
    column 'Date'
        dataType: datetime
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        
    column 'Date2'
        dataType: string
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        
    column 'raised date'
        dataType: datetime
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        
    column '% dips(compared to golden data)'
        dataType: double
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        
    column 'ticket number'
        dataType: string
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        
    column 'ticket owner'
        dataType: string
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        
    column 'status'
        dataType: string
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        
    column 'followups'
        dataType: string
        summarizeBy: none

        annotation SummarizationSetBy = Automatic

        



    partition 'Sheet1' = m
        mode: import
        source = 
            	let
					Source = Excel.Workbook(File.Contents("Data/Tickets/Ticket_tracker.xlsx"), null, true),
					Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
					#"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Table Name", type text}, {"Date", type datetime}, {"Date2", type text}, {"raised date", type datetime}, {"% dips(compared to golden data)", type number}, {"ticket number", type text}, {"ticket owner", type text}, {"status", type text}, {"followups", type text}})
				in
					#"Changed Type"
        



    annotation PBI_ResultType = Table
