table 'Sheet1 (Ticket_tracker)'


    column 'Table Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Table Name

        annotation SummarizationSetBy = Automatic

        
    column 'Date'
        dataType: datetime
        summarizeBy: none
        sourceColumn: Date

        annotation SummarizationSetBy = Automatic

        
    column 'Date2'
        dataType: string
        summarizeBy: none
        sourceColumn: Date2

        annotation SummarizationSetBy = Automatic

        
    column 'raised date'
        dataType: datetime
        summarizeBy: none
        sourceColumn: raised date

        annotation SummarizationSetBy = Automatic

        
    column '% dips(compared to golden data)'
        dataType: double
        summarizeBy: sum
        sourceColumn: % dips(compared to golden data)

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'ticket number'
        dataType: string
        summarizeBy: none
        sourceColumn: ticket number

        annotation SummarizationSetBy = Automatic

        
    column 'ticket owner'
        dataType: string
        summarizeBy: none
        sourceColumn: ticket owner

        annotation SummarizationSetBy = Automatic

        
    column 'status'
        dataType: string
        summarizeBy: none
        sourceColumn: status

        annotation SummarizationSetBy = Automatic

        
    column 'followups'
        dataType: string
        summarizeBy: none
        sourceColumn: followups

        annotation SummarizationSetBy = Automatic

        



    partition 'Sheet1 (Ticket_tracker)' = m
        mode: import
        source = 
            	let
					Source = Excel.Workbook(File.Contents("Data/Tickets/Ticket_tracker.xlsx"), null, true),
					Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
					#"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {})
				in
					#"Changed Type"
        



    annotation PBI_ResultType = Table
