table 'D_OFS_WORK_SKILLS'


    column 'PID'
        dataType: string
        summarizeBy: none
        sourceColumn: PID

        annotation SummarizationSetBy = Automatic

        
    column 'WORK_SKILL_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: WORK_SKILL_ID

        annotation SummarizationSetBy = Automatic

        
    column 'RATIO'
        dataType: string
        summarizeBy: none
        sourceColumn: RATIO

        annotation SummarizationSetBy = Automatic

        
    column 'PROVIDER_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: PROVIDER_ID

        annotation SummarizationSetBy = Automatic

        
    column 'SYS_UPDATE_TS'
        dataType: string
        summarizeBy: none
        sourceColumn: SYS_UPDATE_TS

        annotation SummarizationSetBy = Automatic

        



    partition 'D_OFS_WORK_SKILLS' = m
        mode: import
        source = 
            	let
					Source = Sql.Database("", "", [Query = "Select PID, WORK_SKILL_ID, RATIO, PROVIDER_ID, SYS_UPDATE_TS, PID, WORK_SKILL_ID, RATIO, PROVIDER_ID, SYS_UPDATE_TS"]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"PID", type text}, {"WORK_SKILL_ID", type text}, {"RATIO", type text}, {"PROVIDER_ID", type text}, {"SYS_UPDATE_TS", type text}, {"PID", type text}, {"WORK_SKILL_ID", type text}, {"RATIO", type text}, {"PROVIDER_ID", type text}, {"SYS_UPDATE_TS", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table