table 'D_OFS_ACTIVITY_WORK_SKILL'


    column 'AID'
        dataType: string
        summarizeBy: none
        sourceColumn: AID

        annotation SummarizationSetBy = Automatic

        
    column 'SYS_UPDATE_TS'
        dataType: string
        summarizeBy: none
        sourceColumn: SYS_UPDATE_TS

        annotation SummarizationSetBy = Automatic

        
    column 'WORK_SKILL_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: WORK_SKILL_ID

        annotation SummarizationSetBy = Automatic

        
    column 'REQUIRED_LEVEL'
        dataType: string
        summarizeBy: none
        sourceColumn: REQUIRED_LEVEL

        annotation SummarizationSetBy = Automatic

        
    column 'PREFERABLE_LEVEL'
        dataType: string
        summarizeBy: none
        sourceColumn: PREFERABLE_LEVEL

        annotation SummarizationSetBy = Automatic

        



    partition 'D_OFS_ACTIVITY_WORK_SKILL' = m
        mode: import
        source = 
            	let
					Source = Sql.Database("localhost", "Shared OFS Reporting", [Query = "SELECT * FROM D_OFS_ACTIVITY_WORK_SKILL"]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"AID", type text}, {"SYS_UPDATE_TS", type text}, {"WORK_SKILL_ID", type text}, {"REQUIRED_LEVEL", type text}, {"PREFERABLE_LEVEL", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table