table 'D_OFS_DOM_SERVICE_REQUEST'


    column 'REQUEST_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: REQUEST_ID

        annotation SummarizationSetBy = Automatic

        
    column 'REQUEST_DATE'
        dataType: string
        summarizeBy: none
        sourceColumn: REQUEST_DATE

        annotation SummarizationSetBy = Automatic

        
    column 'REQUEST_PID'
        dataType: string
        summarizeBy: none
        sourceColumn: REQUEST_PID

        annotation SummarizationSetBy = Automatic

        
    column 'REQUEST_AID'
        dataType: string
        summarizeBy: none
        sourceColumn: REQUEST_AID

        annotation SummarizationSetBy = Automatic

        
    column 'REQUEST_INVID'
        dataType: string
        summarizeBy: none
        sourceColumn: REQUEST_INVID

        annotation SummarizationSetBy = Automatic

        
    column 'PROPERTY_10'
        dataType: string
        summarizeBy: none
        sourceColumn: PROPERTY_10

        annotation SummarizationSetBy = Automatic

        
    column 'PROPERTY_11'
        dataType: string
        summarizeBy: none
        sourceColumn: PROPERTY_11

        annotation SummarizationSetBy = Automatic

        
    column 'PROPERTY_380'
        dataType: string
        summarizeBy: none
        sourceColumn: PROPERTY_380

        annotation SummarizationSetBy = Automatic

        
    column 'CREATED_DATE'
        dataType: string
        summarizeBy: none
        sourceColumn: CREATED_DATE

        annotation SummarizationSetBy = Automatic

        
    column 'SUBJECT'
        dataType: string
        summarizeBy: none
        sourceColumn: SUBJECT

        annotation SummarizationSetBy = Automatic

        
    column 'TEXT'
        dataType: string
        summarizeBy: none
        sourceColumn: TEXT

        annotation SummarizationSetBy = Automatic

        
    column 'TYPE_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: TYPE_ID

        annotation SummarizationSetBy = Automatic

        
    column 'USER_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: USER_ID

        annotation SummarizationSetBy = Automatic

        
    column 'VEHICLE_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: VEHICLE_ID

        annotation SummarizationSetBy = Automatic

        
    column 'SYS_UPDATE_TS'
        dataType: string
        summarizeBy: none
        sourceColumn: SYS_UPDATE_TS

        annotation SummarizationSetBy = Automatic

        



    partition 'D_OFS_DOM_SERVICE_REQUEST' = m
        mode: import
        source = 
            	let
					Source = Sql.Database("", "", [Query = "Select REQUEST_ID, REQUEST_DATE, REQUEST_PID, REQUEST_AID, REQUEST_INVID, PROPERTY_10, PROPERTY_11, PROPERTY_380, CREATED_DATE, SUBJECT, TEXT, TYPE_ID, USER_ID, VEHICLE_ID, SYS_UPDATE_TS, REQUEST_ID, REQUEST_DATE, REQUEST_PID, REQUEST_AID, REQUEST_INVID, PROPERTY_10, PROPERTY_11, PROPERTY_380, CREATED_DATE, SUBJECT, TEXT, TYPE_ID, USER_ID, VEHICLE_ID, SYS_UPDATE_TS"]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"REQUEST_ID", type text}, {"REQUEST_DATE", type text}, {"REQUEST_PID", type text}, {"REQUEST_AID", type text}, {"REQUEST_INVID", type text}, {"PROPERTY_10", type text}, {"PROPERTY_11", type text}, {"PROPERTY_380", type text}, {"CREATED_DATE", type text}, {"SUBJECT", type text}, {"TEXT", type text}, {"TYPE_ID", type text}, {"USER_ID", type text}, {"VEHICLE_ID", type text}, {"SYS_UPDATE_TS", type text}, {"REQUEST_ID", type text}, {"REQUEST_DATE", type text}, {"REQUEST_PID", type text}, {"REQUEST_AID", type text}, {"REQUEST_INVID", type text}, {"PROPERTY_10", type text}, {"PROPERTY_11", type text}, {"PROPERTY_380", type text}, {"CREATED_DATE", type text}, {"SUBJECT", type text}, {"TEXT", type text}, {"TYPE_ID", type text}, {"USER_ID", type text}, {"VEHICLE_ID", type text}, {"SYS_UPDATE_TS", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table