table 'D_OFS_DOM_MESSAGE_TEXT'


    column 'MESSAGE_MQID'
        dataType: string
        summarizeBy: none
        sourceColumn: MESSAGE_MQID

        annotation SummarizationSetBy = Automatic

        
    column 'MESSAGE_SUBJECT'
        dataType: string
        summarizeBy: none
        sourceColumn: MESSAGE_SUBJECT

        annotation SummarizationSetBy = Automatic

        
    column 'MESSAGE_TEXT'
        dataType: string
        summarizeBy: none
        sourceColumn: MESSAGE_TEXT

        annotation SummarizationSetBy = Automatic

        
    column 'SYS_UPDATE_TS'
        dataType: string
        summarizeBy: none
        sourceColumn: SYS_UPDATE_TS

        annotation SummarizationSetBy = Automatic

        
    column 'MESSAGE_MQID'
        dataType: string
        summarizeBy: none
        sourceColumn: MESSAGE_MQID

        annotation SummarizationSetBy = Automatic

        
    column 'MESSAGE_SUBJECT'
        dataType: string
        summarizeBy: none
        sourceColumn: MESSAGE_SUBJECT

        annotation SummarizationSetBy = Automatic

        
    column 'MESSAGE_TEXT'
        dataType: string
        summarizeBy: none
        sourceColumn: MESSAGE_TEXT

        annotation SummarizationSetBy = Automatic

        
    column 'SYS_UPDATE_TS'
        dataType: string
        summarizeBy: none
        sourceColumn: SYS_UPDATE_TS

        annotation SummarizationSetBy = Automatic

        



    partition 'D_OFS_DOM_MESSAGE_TEXT' = m
        mode: import
        source = 
            	let
					Source = Sql.Database("", "", [Query = "Select MESSAGE_MQID, MESSAGE_SUBJECT, MESSAGE_TEXT, SYS_UPDATE_TS, MESSAGE_MQID, MESSAGE_SUBJECT, MESSAGE_TEXT, SYS_UPDATE_TS"]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"MESSAGE_MQID", type text}, {"MESSAGE_SUBJECT", type text}, {"MESSAGE_TEXT", type text}, {"SYS_UPDATE_TS", type text}, {"MESSAGE_MQID", type text}, {"MESSAGE_SUBJECT", type text}, {"MESSAGE_TEXT", type text}, {"SYS_UPDATE_TS", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table