table 'Custom SQL Query'


    column 'weekday' = ```
            ISOWEEKDAY('Custom SQL Query'[FISCAL_DATE])
    ```
        dataType: int64
        summarizeBy: sum

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'max Week Flag' = ```
            [Weekly count] = [Weekly count]
    ```
        dataType: boolean
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Week Start Date' = ```
            VAR MinFiscalDate = MINX(FILTER('Custom SQL Query', 'Custom SQL Query'[FISCAL_WEEK] = MAX('Custom SQL Query'[FISCAL_WEEK])), 'Custom SQL Query'[FISCAL_DATE]) RETURN MinFiscalDate
    ```
        dataType: dateTime
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'diff flag' = ```
            SWITCH(TRUE(), 'Custom SQL Query'[% diff] = 0, "Gold", 'Custom SQL Query'[% diff] > ([Parameters].[Parameter 1] / 100), "Flag", 'Custom SQL Query'[% diff] < ([Parameters].[Parameter 1] / 100), "Normal")
    ```
        dataType: string
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'help' = ```
            "Help"
    ```
        dataType: string
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Golden Date' = ```
            IF 'Custom SQL Query'[max Week Flag] = TRUE() THEN 'Custom SQL Query'[FISCAL_DATE] END
    ```
        dataType: dateTime
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Subject' = ```
            "Data Load below " & CONCATENATE(" ", STR([Parameters].[Parameter 1]), "% Of Golden Data Range")
    ```
        dataType: string
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Avg Range' = ```
            INT('Custom SQL Query'[AVG_DATA])
    ```
        dataType: int64
        summarizeBy: sum

        isDataTypeInferred: true
        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Week End Date' = ```
            CALCULATE(MAX('Custom SQL Query'[FISCAL_DATE]), ALLSELECTED('Custom SQL Query'[FISCAL_WEEK]))
    ```
        dataType: dateTime
        summarizeBy: none

        isDataTypeInferred: true
        annotation SummarizationSetBy = Automatic

        
    column 'Tab_module'
        dataType: string
        summarizeBy: none
        sourceColumn: Tab_module

        annotation SummarizationSetBy = Automatic

        
    column 'asup_date'
        dataType: string
        summarizeBy: none
        sourceColumn: asup_date

        annotation SummarizationSetBy = Automatic

        
    column 'dt'
        dataType: string
        summarizeBy: none
        sourceColumn: dt

        annotation SummarizationSetBy = Automatic

        
    column 'serial_count'
        dataType: int64
        summarizeBy: sum
        sourceColumn: serial_count

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'FISCAL_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: FISCAL_DATE

        annotation SummarizationSetBy = Automatic

        
    column 'FISCAL_MONTH'
        dataType: string
        summarizeBy: none
        sourceColumn: FISCAL_MONTH

        annotation SummarizationSetBy = Automatic

        
    column 'FISCAL_QTR'
        dataType: string
        summarizeBy: none
        sourceColumn: FISCAL_QTR

        annotation SummarizationSetBy = Automatic

        
    column 'FISCAL_YEAR'
        dataType: string
        summarizeBy: none
        sourceColumn: FISCAL_YEAR

        annotation SummarizationSetBy = Automatic

        
    column 'FISCAL_WEEK'
        dataType: string
        summarizeBy: none
        sourceColumn: FISCAL_WEEK

        annotation SummarizationSetBy = Automatic

        
    column 'FT'
        dataType: string
        summarizeBy: none
        sourceColumn: FT

        annotation SummarizationSetBy = Automatic

        
    column 'OBJ_SMF_TABLES'
        dataType: string
        summarizeBy: none
        sourceColumn: OBJ_SMF_TABLES

        annotation SummarizationSetBy = Automatic

        
    column 'AVG_DATA'
        dataType: string
        summarizeBy: none
        sourceColumn: AVG_DATA

        annotation SummarizationSetBy = Automatic

        
    column 'asup_month'
        dataType: string
        summarizeBy: none

        dataCategory: Uncategorized
        annotation SummarizationSetBy = Automatic

        
    column 'PUAT_Module'
        dataType: string
        summarizeBy: none

        dataCategory: Uncategorized
        annotation SummarizationSetBy = Automatic

        

    measure 'Weekly count' = ```
            SUM(SWITCH(TRUE(), 'Custom SQL Query'[weekday] = 6 || 'Custom SQL Query'[weekday] = 7, 'Custom SQL Query'[serial_count]))
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure '% diff' = ```
            1 - 'Custom SQL Query'[serial_count] / SUM(SWITCH(TRUE(), 'Custom SQL Query'[weekday] = 6 || 'Custom SQL Query'[weekday] = 7, 'Custom SQL Query'[serial_count]))
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Body' = ```
            "Date of Load " & CONCATENATE(MIN([Week Start Date]), " System Count: ", CONCATENATE(SUM('Custom SQL Query'[serial_count]), " Golden Data Value: ", CONCATENATE(MAX('Custom SQL Query'[Weekly count (copy)_1420604241838956546]), " Regards, PUAT Data Load"))
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure '1500 flag' = ```
            SWITCH(TRUE(), MIN('Custom SQL Query'[Calculation_1857734887845101576]) - SUM('Custom SQL Query'[serial_count]) > 1500, "Flag", "Normal")
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Measure vs Golden' = ```
            MIN(INT('Custom SQL Query'[AVG_DATA])) - SUM('Custom SQL Query'[serial_count])
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Diffrence' = ```
            MIN(CALCULATE(MIN('Custom SQL Query'[Calculation_1857734887845101576]))) - SUM('Custom SQL Query'[serial_count])
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Max\Avg' = ```
            SWITCH(TRUE(), 'Parameters'[Parameter 3] = "Max", 'Custom SQL Query'[Weekly count (copy)_1420604241838956546], 'Parameters'[Parameter 3] = "Avg", [Avg Range])
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Diffrence flag' = ```
            SWITCH(TRUE(), MIN('Custom SQL Query'[Max\Avg]) - SUM('Custom SQL Query'[serial_count]) > 1500, "Flag", MIN('Custom SQL Query'[Max\Avg]) - SUM('Custom SQL Query'[serial_count]) > = 0 && MIN('Custom SQL Query'[Max\Avg]) - SUM('Custom SQL Query'[serial_count]) < = 1500, "Normal", MIN('Custom SQL Query'[Max\Avg]) - SUM('Custom SQL Query'[serial_count]) < 0, "Spike")
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'Max Weekly count' = ```
            MAX(CALCULATE(SUM(SWITCH(TRUE(), 'Custom SQL Query'[weekday] = 6 || 'Custom SQL Query'[weekday] = 7, 'Custom SQL Query'[serial_count])), ALLEXCEPT('Custom SQL Query', 'Custom SQL Query'[FISCAL_WEEK])))
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'Custom SQL Query' = m
        mode: import
        source = 
            	let Source = Dremio.Database("dlh - prd.corp.netapp.com:31011", [HierarchicalNavigation = true]), dbo_DREMIO = Source{[Name = "DREMIO",Kind = "Database"]}[Data], dlh_nsec_objdb = dbo_DREMIO{[Name = "dlh_nsec.objdb",Kind = "Schema"]}[Data], #"Changed Type" = Table.TransformColumnTypes(dlh_nsec_objdb,{{"COLUMN_NAME", type text}, {"DATA_TYPE", type text}, {"TYPE_NAME", type text}, {"COLUMN_SIZE", Int64.Type}, {"BUFFER_LENGTH", Int64.Type}, {"DECIMAL_DIGITS", Int64.Type}, {"NUM_PREC_RADIX", Int64.Type}, {"NULLABLE", Int64.Type}, {"REMARKS", type text}, {"COLUMN_DEF", type text}, {"SQL_DATA_TYPE", Int64.Type}, {"SQL_DATETIME_SUB", Int64.Type}, {"CHAR_OCTET_LENGTH", Int64.Type}, {"ORDINAL_POSITION", Int64.Type}, {"IS_NULLABLE", type text}, {"SCOPE_CATALOG", type text}, {"SCOPE_SCHEMA", type text}, {"SCOPE_TABLE", type text}, {"SOURCE_DATA_TYPE", type text}}), #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([SCOPE_TABLE] < > null)) in #"Filtered Rows"
        



    annotation PBI_ResultType = Table
