table 'Data'


    column 'Regional Manager'
        dataType: string
        summarizeBy: none
        sourceColumn: Regional Manager

        annotation SummarizationSetBy = Automatic

        
    column 'Region'
        dataType: string
        summarizeBy: none
        sourceColumn: Region

        annotation SummarizationSetBy = Automatic

        
    column 'Area'
        dataType: string
        summarizeBy: none
        sourceColumn: Area

        annotation SummarizationSetBy = Automatic

        
    column 'Country'
        dataType: string
        summarizeBy: none
        sourceColumn: Country

        annotation SummarizationSetBy = Automatic

        
    column 'Region1'
        dataType: string
        summarizeBy: none
        sourceColumn: Region1

        annotation SummarizationSetBy = Automatic

        
    column 'Order ID'
        dataType: string
        summarizeBy: none
        sourceColumn: Order ID

        annotation SummarizationSetBy = Automatic

        
    column 'Returned'
        dataType: string
        summarizeBy: none
        sourceColumn: Returned

        annotation SummarizationSetBy = Automatic

        



    partition 'Data' = m
        mode: import
        source = 
            let
				Source = Value.NativeQuery(Cognos,
				"SELECT ""Regional Manager"",
				""Region"",
				""Area"",
				""Country"",
				""Region1"",
				""Order ID"",
				""Returned"" FROM Data"),
				#"Changed Types" = Table.TransformColumnTypes(Source,
				{{"Regional Manager",
				type text},
				{"Region",
				type text},
				{"Area",
				type text},
				{"Country",
				type text},
				{"Region1",
				type text},
				{"Order ID",
				type text},
				{"Returned",
				type text}})
			in
				#"Changed Types"
        



    annotation PBI_ResultType = Table