table MATERIAL_CHARGES


    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'CHARGED_DATE'
        dataType: string
        summarizeBy: none
        sourceColumn: CHARGED_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'JOB_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: JOB_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'QUANTITY'
        dataType: string
        summarizeBy: none
        sourceColumn: QUANTITY

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TRANSACTION_VALUE'
        dataType: string
        summarizeBy: none
        sourceColumn: TRANSACTION_VALUE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ADJUSTMENT_DESC'
        dataType: string
        summarizeBy: none
        sourceColumn: ADJUSTMENT_DESC

        

        annotation SummarizationSetBy = Automatic

        
    column 'ADJUSTMENT_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: ADJUSTMENT_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'TIME_ENTERED'
        dataType: string
        summarizeBy: none
        sourceColumn: TIME_ENTERED

        

        annotation SummarizationSetBy = Automatic

        



    partition 'MATERIAL_CHARGES' = m
        mode: import
        source = 
            
let
    Source = Excel.Workbook(File.Contents("C:\Users\PowerBIUser\Documents\sample_data.xlsx"), null, true),
    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SITE_NUMBER", type text}, {"ITEM_NUMBER", type text}, {"CHARGED_DATE", type text}, {"JOB_NUMBER", type text}, {"QUANTITY", type text}, {"UNIT_PRICE", type text}, {"TRANSACTION_VALUE", type text}, {"ADJUSTMENT_DESC", type text}, {"ADJUSTMENT_TYPE", type text}, {"TIME_ENTERED", type text}})
in
    #"Changed Type"

        



    annotation PBI_ResultType = Table