table '{{source_name}}'

    {{#if is_hidden}}
    isHidden
    {{/if}}

    {{#each columns}}
    column '{{source_name}}'
        dataType: {{datatype}}
        {{#if format_string}}
        formatString: {{format_string}}
        {{/if}}
        {{#if summarize_by}}
        summarizeBy: {{summarize_by}}
        {{/if}}
        {{#if is_calculated}}
        type: calculated
        {{/if}}
        {{#if source_column}}
        {{#if is_calculated}}
        sourceColumn = ```
            
            {{{source_column}}}
            
            ```
        {{else}}
        sourceColumn: {{{source_column}}}
        {{/if}}
        {{/if}}

        {{#if is_hidden}}
        isHidden
        {{/if}}
        {{#if data_category}}
        dataCategory: {{data_category}}
        {{/if}}
        {{#if is_data_type_inferred}}
        isDataTypeInferred: {{is_data_type_inferred}}
        {{/if}}
        {{#if annotations.SummarizationSetBy}}
        annotation SummarizationSetBy = {{annotations.SummarizationSetBy}}
        {{else}}
        annotation SummarizationSetBy = Automatic
        {{/if}}

        {{#if annotations.PBI_FormatHint}}
        annotation PBI_FormatHint = {"isGeneralNumber":true}
        {{/if}}
        
    {{/each}}

    {{#each measures}}
    measure '{{source_name}}' = ```
			{{{expression}}}
			```
        {{#if format_string}}
        formatString: {{format_string}}
        {{/if}}

        {{#if is_hidden}}
        isHidden
        {{/if}}
    {{/each}}

    {{#each hierarchies}}
    hierarchy {{name}}

        {{#if is_hidden}}
        isHidden
        {{/if}}
        {{#each levels}}
        level {{name}}
            column: {{column_name}}
            {{#if ordinal}}
            ordinal: {{ordinal}}
            {{/if}}
        {{/each}}
    {{/each}}

    {{#each partitions}}
    partition '{{name}}' = {{source_type}}
        mode: import
        source = ```
            {{expression}}
        ```

    {{/each}}

    {{#if has_widget_serialization}}
    annotation TableWidgetSerialization =
        {
          "VisualType": {{visual_type}},
          "Columns": {{column_settings}}
        }
    {{/if}}

    annotation PBI_ResultType = Table
