table 'sample_sales_data'

	column '_row_id'
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: _row_id

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = identifier
		annotation CognosRegularAggregate = count

	column 'Order_ID'
		dataType: int64
		summarizeBy: none
		sourceColumn: Order_ID
		formatString: General Number

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = identifier
		annotation CognosRegularAggregate = countDistinct

	column 'Order_Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Order_Date
		formatString: Short Date

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation CognosUsage = identifier
		annotation CognosRegularAggregate = countDistinct

	column 'Region'
		dataType: string
		summarizeBy: none
		sourceColumn: Region

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation CognosUsage = identifier
		annotation CognosRegularAggregate = countDistinct

	column 'Product_Category'
		dataType: string
		summarizeBy: none
		sourceColumn: Product_Category

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation CognosUsage = identifier
		annotation CognosRegularAggregate = countDistinct

	column 'Product_Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Product_Name

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation CognosUsage = attribute
		annotation CognosRegularAggregate = countDistinct

	column 'Sales'
		dataType: decimal
		summarizeBy: sum
		sourceColumn: Sales
		formatString: General Number

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = fact
		annotation CognosRegularAggregate = total

	column 'Quantity'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Quantity
		formatString: General Number

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = fact
		annotation CognosRegularAggregate = total

	column 'Discount'
		dataType: decimal
		summarizeBy: sum
		sourceColumn: Discount
		formatString: General Number

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = fact
		annotation CognosRegularAggregate = total

	column 'Profit'
		dataType: decimal
		summarizeBy: sum
		sourceColumn: Profit
		formatString: General Number

		isDataTypeInferred: True
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation CognosUsage = fact
		annotation CognosRegularAggregate = total

	partition 'sample_sales_data-partition' = m
		mode: import
		source = 
			let
				Source = Excel.Workbook(File.Contents("sample_sales_data.xlsx"), null, true),
				Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				#"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])
			in
				#"Promoted Headers"

	annotation PBI_ResultType = Table
