table 'Data'


    column 'ID'
        dataType: int64
        summarizeBy: none
        sourceColumn: ID
        formatString: 0

        annotation SummarizationSetBy = User

        
    column 'Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Name

        annotation SummarizationSetBy = User

        
    column 'Value'
        dataType: int64
        summarizeBy: none
        sourceColumn: Value
        formatString: 0

        annotation SummarizationSetBy = User

        



    partition 'Data-partition' = m
        mode: import
        source = 
            let
				Source = Value.NativeQuery(Cognos,
				"SELECT ID,
				Name,
				Value FROM Data"),
				#"Changed Types" = Table.TransformColumnTypes(Source,
				{{"ID",
				Int64.Type},
				{"Name",
				type text},
				{"Value",
				Int64.Type}})
			in
				#"Changed Types"
        



    annotation PBI_ResultType = Table