table 'Data'


    column 'ID'
        dataType: int64
        summarizeBy: none
        sourceColumn: ID
        formatString: 0

        annotation SummarizationSetBy = User

        
    column 'Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Name

        annotation SummarizationSetBy = User

        
    column 'Value'
        dataType: int64
        summarizeBy: none
        sourceColumn: Value
        formatString: 0

        annotation SummarizationSetBy = User

        



    partition 'Data-partition' = m
        mode: import
        source = 
            let
    Source = Value.NativeQuery(Cognos, "SELECT ID, Name, Value FROM Data"), RenamedColumns = Table.RenameColumns(Source, {{"ID", "ID"}, {"Name", "Name"}, {"Value", "Value"}}), ChangedTypes = Table.TransformColumnTypes(RenamedColumns, {{"ID", Int64.Type}, {"Name", type text}, {"Value", Int64.Type}})
in    ChangedTypes
        



    annotation PBI_ResultType = Table