table 'Data'


    column 'ID'
        dataType: int64
        summarizeBy: none
        sourceColumn: ID
        formatString: 0

        annotation SummarizationSetBy = User

        
    column 'Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Name

        annotation SummarizationSetBy = User

        
    column 'Value'
        dataType: int64
        summarizeBy: none
        sourceColumn: Value
        formatString: 0

        annotation SummarizationSetBy = User

        



    partition 'Data-partition' = m
        mode: import
        source = 
            let / / Source step to connect to the data source Source = Cognos, / / Ensure correct data types for optimal performance and query folding #"Changed Type" = Table.TransformColumnTypes(Source, { {"ID", Int64.Type}, {"Name", Text.Type}, {"Value", Int64.Type} }) in #"Changed Type"
        



    annotation PBI_ResultType = Table