table 'Report_with_Calculations'


    column 'Region'
        dataType: string
        summarizeBy: none
        sourceColumn: Region

        annotation SummarizationSetBy = Automatic

        
    column 'No of Unique Orders' = ```
            No of Unique Orders
    ```
        dataType: int64
        summarizeBy: sum

        annotation SummarizationSetBy = User

        
    column 'Orders Returned (Multiple Returns per Order)' = ```
            Orders Returned (Multiple Returns per Order)
    ```
        dataType: decimal
        summarizeBy: sum

        annotation SummarizationSetBy = User

        



    partition 'Report_with_Calculations' = m
        mode: import
        source = 
            let
				Source = / * Connect to data source based on context * /,
				#"Renamed Columns" = Table.RenameColumns(Source,
				{{"OldRegion",
				"Region"},
				{"OldUniqueOrders",
				"No of Unique Orders"},
				{"OldOrdersReturned",
				"Orders Returned (Multiple Returns per Order)"}}),
				#"Changed Types" = Table.TransformColumnTypes(#"Renamed Columns",
				{{"Region",
				type text},
				{"No of Unique Orders",
				type text},
				{"Orders Returned (Multiple Returns per Order)",
				type number}})
			in
				#"Changed Types"
        



    annotation PBI_ResultType = Table