table ITEM_ROOT_EXTENDED_DESCRIPTION


    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'ROOT_DESCRIPTION'
        dataType: string
        summarizeBy: none
        sourceColumn: ROOT_DESCRIPTION

        

        annotation SummarizationSetBy = Automatic

        
    column 'TOTAL_NUMBER_SEGMENTS'
        dataType: int64
        summarizeBy: none
        sourceColumn: TOTAL_NUMBER_SEGMENTS

        

        annotation SummarizationSetBy = Automatic

        
    column 'NUMBER_SEGMENTS_SELECTED'
        dataType: int64
        summarizeBy: none
        sourceColumn: NUMBER_SEGMENTS_SELECTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'LINE_NUMBER1'
        dataType: string
        summarizeBy: none
        sourceColumn: LINE_NUMBER1

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION1'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION1

        

        annotation SummarizationSetBy = Automatic

        
    column 'TYPE1'
        dataType: string
        summarizeBy: none
        sourceColumn: TYPE1

        

        annotation SummarizationSetBy = Automatic

        
    column 'LINE_NUMBER2'
        dataType: string
        summarizeBy: none
        sourceColumn: LINE_NUMBER2

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION2'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION2

        

        annotation SummarizationSetBy = Automatic

        
    column 'TYPE2'
        dataType: string
        summarizeBy: none
        sourceColumn: TYPE2

        

        annotation SummarizationSetBy = Automatic

        
    column 'LINE_NUMBER3'
        dataType: string
        summarizeBy: none
        sourceColumn: LINE_NUMBER3

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION3'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION3

        

        annotation SummarizationSetBy = Automatic

        
    column 'TYPE3'
        dataType: string
        summarizeBy: none
        sourceColumn: TYPE3

        

        annotation SummarizationSetBy = Automatic

        
    column 'LINE_NUMBER4'
        dataType: string
        summarizeBy: none
        sourceColumn: LINE_NUMBER4

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION4'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION4

        

        annotation SummarizationSetBy = Automatic

        
    column 'TYPE4'
        dataType: string
        summarizeBy: none
        sourceColumn: TYPE4

        

        annotation SummarizationSetBy = Automatic

        
    column 'LINE_NUMBER5'
        dataType: string
        summarizeBy: none
        sourceColumn: LINE_NUMBER5

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION5'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION5

        

        annotation SummarizationSetBy = Automatic

        
    column 'TYPE5'
        dataType: string
        summarizeBy: none
        sourceColumn: TYPE5

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE

        

        annotation SummarizationSetBy = Automatic

        



    partition 'ITEM_ROOT_EXTENDED_DESCRIPTION' = m
        mode: import
        source = 
            
let
    Source = Excel.Workbook(File.Contents("C:\Users\PowerBIUser\Documents\sample_data.xlsx"), null, true),
    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ITEM_NUMBER", type text}, {"ROOT_DESCRIPTION", type text}, {"TOTAL_NUMBER_SEGMENTS", type text}, {"NUMBER_SEGMENTS_SELECTED", type text}, {"LINE_NUMBER1", type text}, {"DESCRIPTION1", type text}, {"TYPE1", type text}, {"LINE_NUMBER2", type text}, {"DESCRIPTION2", type text}, {"TYPE2", type text}, {"LINE_NUMBER3", type text}, {"DESCRIPTION3", type text}, {"TYPE3", type text}, {"LINE_NUMBER4", type text}, {"DESCRIPTION4", type text}, {"TYPE4", type text}, {"LINE_NUMBER5", type text}, {"DESCRIPTION5", type text}, {"TYPE5", type text}, {"STOP", type text}, {"SITE", type text}, {"ITEM_NUMBER", type text}, {"ROOT_DESCRIPTION", type text}, {"TOTAL_NUMBER_SEGMENTS", type text}, {"NUMBER_SEGMENTS_SELECTED", type text}, {"LINE_NUMBER1", type text}, {"DESCRIPTION1", type text}, {"TYPE1", type text}, {"LINE_NUMBER2", type text}, {"DESCRIPTION2", type text}, {"TYPE2", type text}, {"LINE_NUMBER3", type text}, {"DESCRIPTION3", type text}, {"TYPE3", type text}, {"LINE_NUMBER4", type text}, {"DESCRIPTION4", type text}, {"TYPE4", type text}, {"LINE_NUMBER5", type text}, {"DESCRIPTION5", type text}, {"TYPE5", type text}, {"STOP", type text}, {"SITE", type text}})
in
    #"Changed Type"

        



    annotation PBI_ResultType = Table