table MANUFACTURER


    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'MFG_PART_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: MFG_PART_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'MODEL_PART_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: MODEL_PART_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'ACTIVITY_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: ACTIVITY_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'MFG_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: MFG_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_CREATED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_CREATED

        

        annotation SummarizationSetBy = Automatic

        
    column 'MFG_NAME'
        dataType: string
        summarizeBy: none
        sourceColumn: MFG_NAME

        

        annotation SummarizationSetBy = Automatic

        
    column 'COMPRESSED_PART_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: COMPRESSED_PART_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'FOSSIL_OR_NUCLEAR'
        dataType: string
        summarizeBy: none
        sourceColumn: FOSSIL_OR_NUCLEAR

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE

        

        annotation SummarizationSetBy = Automatic

        

    measure 'MANUFACTURER - Count by DATE_CREATED' = ```
            CALCULATE(
    COUNTROWS('MANUFACTURER'),
    USERELATIONSHIP('CentralDateTable'[Date], 'MANUFACTURER'[DATE_CREATED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'MANUFACTURER' = m
        mode: import
        source = 
            
let
    Source = Excel.Workbook(File.Contents("C:\Users\PowerBIUser\Documents\sample_data.xlsx"), null, true),
    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ITEM_NUMBER", type text}, {"MFG_PART_NUMBER", type text}, {"MODEL_PART_IND", type text}, {"ACTIVITY_CODE", type text}, {"MFG_CODE", type text}, {"DATE_CREATED", type text}, {"MFG_NAME", type text}, {"COMPRESSED_PART_NUMBER", type text}, {"FOSSIL_OR_NUCLEAR", type text}, {"STOP", type text}, {"SITE", type text}, {"ITEM_NUMBER", type text}, {"MFG_PART_NUMBER", type text}, {"MODEL_PART_IND", type text}, {"ACTIVITY_CODE", type text}, {"MFG_CODE", type text}, {"DATE_CREATED", type text}, {"MFG_NAME", type text}, {"COMPRESSED_PART_NUMBER", type text}, {"FOSSIL_OR_NUCLEAR", type text}, {"STOP", type text}, {"SITE", type text}})
in
    #"Changed Type"

        



    annotation PBI_ResultType = Table