table MODEL_WORK_ORDER


    column 'STATION_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: STATION_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'MODEL_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: MODEL_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'MODEL_WO_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: MODEL_WO_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'MARK_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: MARK_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'JOB_DESC'
        dataType: string
        summarizeBy: none
        sourceColumn: JOB_DESC

        

        annotation SummarizationSetBy = Automatic

        
    column 'MODEL_MANHOURS_TOTAL'
        dataType: int64
        summarizeBy: none
        sourceColumn: MODEL_MANHOURS_TOTAL

        

        annotation SummarizationSetBy = Automatic

        
    column 'MODEL_JOB_DURATION'
        dataType: int64
        summarizeBy: none
        sourceColumn: MODEL_JOB_DURATION

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNKNOWN1'
        dataType: string
        summarizeBy: none
        sourceColumn: UNKNOWN1

        

        annotation SummarizationSetBy = Automatic

        
    column 'R_OR_I'
        dataType: string
        summarizeBy: none
        sourceColumn: R_OR_I

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNKNOWN2'
        dataType: int64
        summarizeBy: none
        sourceColumn: UNKNOWN2

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        
    column 'FREQUENCY_VALUE'
        dataType: string
        summarizeBy: none
        sourceColumn: FREQUENCY_VALUE

        

        annotation SummarizationSetBy = Automatic

        
    column 'FREQUENCY_UNITS'
        dataType: string
        summarizeBy: none
        sourceColumn: FREQUENCY_UNITS

        

        annotation SummarizationSetBy = Automatic

        
    column 'DEFER_VALUE'
        dataType: string
        summarizeBy: none
        sourceColumn: DEFER_VALUE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DEFER_UNITS'
        dataType: string
        summarizeBy: none
        sourceColumn: DEFER_UNITS

        

        annotation SummarizationSetBy = Automatic

        
    column 'RECENT_DATE_DUE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: RECENT_DATE_DUE

        

        annotation SummarizationSetBy = Automatic

        
    column 'RECENT_DATE_OVERDUE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: RECENT_DATE_OVERDUE

        

        annotation SummarizationSetBy = Automatic

        
    column 'NEXT_PRELIM_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: NEXT_PRELIM_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'NEXT_DATE_DUE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: NEXT_DATE_DUE

        

        annotation SummarizationSetBy = Automatic

        
    column 'COMMENTS'
        dataType: string
        summarizeBy: none
        sourceColumn: COMMENTS

        

        annotation SummarizationSetBy = Automatic

        
    column 'MOST_RECENT_WO'
        dataType: string
        summarizeBy: none
        sourceColumn: MOST_RECENT_WO

        

        annotation SummarizationSetBy = Automatic

        
    column 'MARK_NUMBER_COMPRESSED'
        dataType: string
        summarizeBy: none
        sourceColumn: MARK_NUMBER_COMPRESSED

        

        annotation SummarizationSetBy = Automatic

        
    column 'GROUP_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: GROUP_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'CLASS_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: CLASS_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'SUBCLASS_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: SUBCLASS_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'MOST_RECENT_WO2'
        dataType: string
        summarizeBy: none
        sourceColumn: MOST_RECENT_WO2

        

        annotation SummarizationSetBy = Automatic

        
    column 'MOST_RECENT_WO3'
        dataType: string
        summarizeBy: none
        sourceColumn: MOST_RECENT_WO3

        

        annotation SummarizationSetBy = Automatic

        
    column 'OUTAGE_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: OUTAGE_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'LAST_COMPLETED_WO'
        dataType: string
        summarizeBy: none
        sourceColumn: LAST_COMPLETED_WO

        

        annotation SummarizationSetBy = Automatic

        

    measure 'MODEL_WORK_ORDER - Count by NEXT_DATE_DUE' = ```
            CALCULATE(
    COUNTROWS('MODEL_WORK_ORDER'),
    USERELATIONSHIP('CentralDateTable'[Date], 'MODEL_WORK_ORDER'[NEXT_DATE_DUE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'MODEL_WORK_ORDER - Count by NEXT_PRELIM_DATE' = ```
            CALCULATE(
    COUNTROWS('MODEL_WORK_ORDER'),
    USERELATIONSHIP('CentralDateTable'[Date], 'MODEL_WORK_ORDER'[NEXT_PRELIM_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'MODEL_WORK_ORDER - Count by RECENT_DATE_DUE' = ```
            CALCULATE(
    COUNTROWS('MODEL_WORK_ORDER'),
    USERELATIONSHIP('CentralDateTable'[Date], 'MODEL_WORK_ORDER'[RECENT_DATE_DUE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'MODEL_WORK_ORDER - Count by RECENT_DATE_OVERDUE' = ```
            CALCULATE(
    COUNTROWS('MODEL_WORK_ORDER'),
    USERELATIONSHIP('CentralDateTable'[Date], 'MODEL_WORK_ORDER'[RECENT_DATE_OVERDUE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'MODEL_WORK_ORDER' = m
        mode: import
        source = 
            
let
    Source = Excel.Workbook(File.Contents("C:\Users\PowerBIUser\Documents\sample_data.xlsx"), null, true),
    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"STATION_NUMBER", type text}, {"MODEL_TYPE", type text}, {"MODEL_WO_NUMBER", type text}, {"MARK_NUMBER", type text}, {"JOB_DESC", type text}, {"MODEL_MANHOURS_TOTAL", type text}, {"MODEL_JOB_DURATION", type text}, {"UNKNOWN1", type text}, {"R_OR_I", type text}, {"UNKNOWN2", type text}, {"STOP", type text}, {"FREQUENCY_VALUE", type text}, {"FREQUENCY_UNITS", type text}, {"DEFER_VALUE", type text}, {"DEFER_UNITS", type text}, {"RECENT_DATE_DUE", type text}, {"RECENT_DATE_OVERDUE", type text}, {"NEXT_PRELIM_DATE", type text}, {"NEXT_DATE_DUE", type text}, {"COMMENTS", type text}, {"MOST_RECENT_WO", type text}, {"MARK_NUMBER_COMPRESSED", type text}, {"GROUP_CODE", type text}, {"CLASS_CODE", type text}, {"SUBCLASS_CODE", type text}, {"MOST_RECENT_WO2", type text}, {"MOST_RECENT_WO3", type text}, {"OUTAGE_TYPE", type text}, {"LAST_COMPLETED_WO", type text}, {"STATION_NUMBER", type text}, {"MODEL_TYPE", type text}, {"MODEL_WO_NUMBER", type text}, {"MARK_NUMBER", type text}, {"JOB_DESC", type text}, {"MODEL_MANHOURS_TOTAL", type text}, {"MODEL_JOB_DURATION", type text}, {"UNKNOWN1", type text}, {"R_OR_I", type text}, {"UNKNOWN2", type text}, {"STOP", type text}, {"FREQUENCY_VALUE", type text}, {"FREQUENCY_UNITS", type text}, {"DEFER_VALUE", type text}, {"DEFER_UNITS", type text}, {"RECENT_DATE_DUE", type text}, {"RECENT_DATE_OVERDUE", type text}, {"NEXT_PRELIM_DATE", type text}, {"NEXT_DATE_DUE", type text}, {"COMMENTS", type text}, {"MOST_RECENT_WO", type text}, {"MARK_NUMBER_COMPRESSED", type text}, {"GROUP_CODE", type text}, {"CLASS_CODE", type text}, {"SUBCLASS_CODE", type text}, {"MOST_RECENT_WO2", type text}, {"MOST_RECENT_WO3", type text}, {"OUTAGE_TYPE", type text}, {"LAST_COMPLETED_WO", type text}})
in
    #"Changed Type"

        



    annotation PBI_ResultType = Table