table PURCHASE_ORDER_DESCRIPTIONS


    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'RELEASE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: RELEASE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_LINE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_LINE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'TOTAL_NUMBER_SEGMENTS'
        dataType: int64
        summarizeBy: none
        sourceColumn: TOTAL_NUMBER_SEGMENTS

        

        annotation SummarizationSetBy = Automatic

        
    column 'NUMBER_SEGMENTS_SELECTED'
        dataType: int64
        summarizeBy: none
        sourceColumn: NUMBER_SEGMENTS_SELECTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'LINE_NUMBER1'
        dataType: string
        summarizeBy: none
        sourceColumn: LINE_NUMBER1

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION1'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION1

        

        annotation SummarizationSetBy = Automatic

        
    column 'LINE_NUMBER2'
        dataType: string
        summarizeBy: none
        sourceColumn: LINE_NUMBER2

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION2'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION2

        

        annotation SummarizationSetBy = Automatic

        
    column 'LINE_NUMBER3'
        dataType: string
        summarizeBy: none
        sourceColumn: LINE_NUMBER3

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION3'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION3

        

        annotation SummarizationSetBy = Automatic

        
    column 'LINE_NUMBER4'
        dataType: string
        summarizeBy: none
        sourceColumn: LINE_NUMBER4

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION4'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION4

        

        annotation SummarizationSetBy = Automatic

        
    column 'LINE_NUMBER5'
        dataType: string
        summarizeBy: none
        sourceColumn: LINE_NUMBER5

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION5'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION5

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        



    partition 'PURCHASE_ORDER_DESCRIPTIONS' = m
        mode: import
        source = 
            
let
    Source = Excel.Workbook(File.Contents("C:\Users\PowerBIUser\Documents\sample_data.xlsx"), null, true),
    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ITEM_NUMBER", type text}, {"SITE_NUMBER", type text}, {"PO_NUMBER", type text}, {"RELEASE_NUMBER", type text}, {"PO_LINE_NUMBER", type text}, {"TOTAL_NUMBER_SEGMENTS", type text}, {"NUMBER_SEGMENTS_SELECTED", type text}, {"LINE_NUMBER1", type text}, {"DESCRIPTION1", type text}, {"LINE_NUMBER2", type text}, {"DESCRIPTION2", type text}, {"LINE_NUMBER3", type text}, {"DESCRIPTION3", type text}, {"LINE_NUMBER4", type text}, {"DESCRIPTION4", type text}, {"LINE_NUMBER5", type text}, {"DESCRIPTION5", type text}, {"STOP", type text}, {"ITEM_NUMBER", type text}, {"SITE_NUMBER", type text}, {"PO_NUMBER", type text}, {"RELEASE_NUMBER", type text}, {"PO_LINE_NUMBER", type text}, {"TOTAL_NUMBER_SEGMENTS", type text}, {"NUMBER_SEGMENTS_SELECTED", type text}, {"LINE_NUMBER1", type text}, {"DESCRIPTION1", type text}, {"LINE_NUMBER2", type text}, {"DESCRIPTION2", type text}, {"LINE_NUMBER3", type text}, {"DESCRIPTION3", type text}, {"LINE_NUMBER4", type text}, {"DESCRIPTION4", type text}, {"LINE_NUMBER5", type text}, {"DESCRIPTION5", type text}, {"STOP", type text}})
in
    #"Changed Type"

        



    annotation PBI_ResultType = Table