table REQUISITION_EXTRACT


    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'REQ'
        dataType: string
        summarizeBy: none
        sourceColumn: REQ

        

        annotation SummarizationSetBy = Automatic

        
    column 'STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'STATS_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: STATS_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_PRICE'
        dataType: int64
        summarizeBy: none
        sourceColumn: UNIT_PRICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'BU_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: BU_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'JOB_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: JOB_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_OF_MEASURE'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_OF_MEASURE

        

        annotation SummarizationSetBy = Automatic

        
    column 'PRICE_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: PRICE_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY_REQUESTED'
        dataType: int64
        summarizeBy: none
        sourceColumn: QTY_REQUESTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'REQUIRED_DATE'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: REQUIRED_DATE

        

        annotation SummarizationSetBy = Automatic

        
    column 'DATE_ENTERED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DATE_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_INSPECTOR'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_INSPECTOR

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_LEVEL'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_LEVEL

        

        annotation SummarizationSetBy = Automatic

        
    column 'REQUESTOR'
        dataType: string
        summarizeBy: none
        sourceColumn: REQUESTOR

        

        annotation SummarizationSetBy = Automatic

        
    column 'EXPEDITE'
        dataType: string
        summarizeBy: none
        sourceColumn: EXPEDITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'APPROVED_BY'
        dataType: string
        summarizeBy: none
        sourceColumn: APPROVED_BY

        

        annotation SummarizationSetBy = Automatic

        
    column 'APPROVED_LIMIT'
        dataType: string
        summarizeBy: none
        sourceColumn: APPROVED_LIMIT

        

        annotation SummarizationSetBy = Automatic

        
    column 'MAX_AMOUNT'
        dataType: int64
        summarizeBy: none
        sourceColumn: MAX_AMOUNT

        

        annotation SummarizationSetBy = Automatic

        
    column 'ATTACHMENT_IND'
        dataType: string
        summarizeBy: none
        sourceColumn: ATTACHMENT_IND

        

        annotation SummarizationSetBy = Automatic

        
    column 'ROOT_DATE_ENTERED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: ROOT_DATE_ENTERED

        

        annotation SummarizationSetBy = Automatic

        
    column 'ROOT_DATE_REQUESTED'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: ROOT_DATE_REQUESTED

        

        annotation SummarizationSetBy = Automatic

        
    column 'SERVICE'
        dataType: string
        summarizeBy: none
        sourceColumn: SERVICE

        

        annotation SummarizationSetBy = Automatic

        
    column 'SHIP_TO_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: SHIP_TO_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'SUGGESTED_VENDOR'
        dataType: string
        summarizeBy: none
        sourceColumn: SUGGESTED_VENDOR

        

        annotation SummarizationSetBy = Automatic

        
    column 'ROOT_DATE_STATUS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: ROOT_DATE_STATUS

        

        annotation SummarizationSetBy = Automatic

        
    column 'COMMODITY_CODE'
        dataType: string
        summarizeBy: none
        sourceColumn: COMMODITY_CODE

        

        annotation SummarizationSetBy = Automatic

        
    column 'QA_CERT_REQUIREMENTS'
        dataType: string
        summarizeBy: none
        sourceColumn: QA_CERT_REQUIREMENTS

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        

    measure 'REQUISITION_EXTRACT - Count by DATE_ENTERED' = ```
            CALCULATE(
    COUNTROWS('REQUISITION_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'REQUISITION_EXTRACT'[DATE_ENTERED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'REQUISITION_EXTRACT - Count by REQUIRED_DATE' = ```
            CALCULATE(
    COUNTROWS('REQUISITION_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'REQUISITION_EXTRACT'[REQUIRED_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'REQUISITION_EXTRACT - Count by ROOT_DATE_ENTERED' = ```
            CALCULATE(
    COUNTROWS('REQUISITION_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'REQUISITION_EXTRACT'[ROOT_DATE_ENTERED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'REQUISITION_EXTRACT - Count by ROOT_DATE_REQUESTED' = ```
            CALCULATE(
    COUNTROWS('REQUISITION_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'REQUISITION_EXTRACT'[ROOT_DATE_REQUESTED])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'REQUISITION_EXTRACT - Count by ROOT_DATE_STATUS' = ```
            CALCULATE(
    COUNTROWS('REQUISITION_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'REQUISITION_EXTRACT'[ROOT_DATE_STATUS])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    measure 'REQUISITION_EXTRACT - Count by STATS_DATE' = ```
            CALCULATE(
    COUNTROWS('REQUISITION_EXTRACT'),
    USERELATIONSHIP('CentralDateTable'[Date], 'REQUISITION_EXTRACT'[STATS_DATE])
)
    ```


        annotation PBI_FormatHint = {"isGeneralNumber":true}
        


    partition 'REQUISITION_EXTRACT' = m
        mode: import
        source = 
            
let
    Source = Excel.Workbook(File.Contents("C:\Users\PowerBIUser\Documents\sample_data.xlsx"), null, true),
    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SITE_NUMBER", type text}, {"REQ", type text}, {"STATUS", type text}, {"STATS_DATE", type text}, {"ITEM_NUMBER", type text}, {"UNIT_PRICE", type text}, {"BU_NUMBER", type text}, {"JOB_NUMBER", type text}, {"UNIT_OF_MEASURE", type text}, {"PRICE_CODE", type text}, {"QTY_REQUESTED", type text}, {"REQUIRED_DATE", type text}, {"DATE_ENTERED", type text}, {"QA_CODE", type text}, {"QA_INSPECTOR", type text}, {"QA_LEVEL", type text}, {"REQUESTOR", type text}, {"EXPEDITE", type text}, {"APPROVED_BY", type text}, {"APPROVED_LIMIT", type text}, {"MAX_AMOUNT", type text}, {"ATTACHMENT_IND", type text}, {"ROOT_DATE_ENTERED", type text}, {"ROOT_DATE_REQUESTED", type text}, {"SERVICE", type text}, {"SHIP_TO_CODE", type text}, {"SUGGESTED_VENDOR", type text}, {"ROOT_DATE_STATUS", type text}, {"COMMODITY_CODE", type text}, {"QA_CERT_REQUIREMENTS", type text}, {"STOP", type text}, {"SITE_NUMBER", type text}, {"REQ", type text}, {"STATUS", type text}, {"STATS_DATE", type text}, {"ITEM_NUMBER", type text}, {"UNIT_PRICE", type text}, {"BU_NUMBER", type text}, {"JOB_NUMBER", type text}, {"UNIT_OF_MEASURE", type text}, {"PRICE_CODE", type text}, {"QTY_REQUESTED", type text}, {"REQUIRED_DATE", type text}, {"DATE_ENTERED", type text}, {"QA_CODE", type text}, {"QA_INSPECTOR", type text}, {"QA_LEVEL", type text}, {"REQUESTOR", type text}, {"EXPEDITE", type text}, {"APPROVED_BY", type text}, {"APPROVED_LIMIT", type text}, {"MAX_AMOUNT", type text}, {"ATTACHMENT_IND", type text}, {"ROOT_DATE_ENTERED", type text}, {"ROOT_DATE_REQUESTED", type text}, {"SERVICE", type text}, {"SHIP_TO_CODE", type text}, {"SUGGESTED_VENDOR", type text}, {"ROOT_DATE_STATUS", type text}, {"COMMODITY_CODE", type text}, {"QA_CERT_REQUIREMENTS", type text}, {"STOP", type text}})
in
    #"Changed Type"

        



    annotation PBI_ResultType = Table