table SITES


    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_NAME'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NAME

        

        annotation SummarizationSetBy = Automatic

        



    partition 'SITES' = m
        mode: import
        source = 
            
let
    Source = Excel.Workbook(File.Contents("C:\Users\PowerBIUser\Documents\sample_data.xlsx"), null, true),
    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SITE_NUMBER", type text}, {"SITE_NAME", type text}, {"SITE_NUMBER", type text}, {"SITE_NAME", type text}})
in
    #"Changed Type"

        



    annotation PBI_ResultType = Table