table STORAGE_LOCATION


    column 'ITEM_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'SITE_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE_NUMBER

        

        annotation SummarizationSetBy = Automatic

        
    column 'SEGMENTS'
        dataType: int64
        summarizeBy: none
        sourceColumn: SEGMENTS

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION1'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION1

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_1'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_1

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION2'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION2

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_2'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_2

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION3'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION3

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_3'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_3

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION4'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION4

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_4'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_4

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION5'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION5

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_5'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_5

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION6'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION6

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_6'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_6

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION7'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION7

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_7'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_7

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION8'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION8

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_8'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_8

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION9'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION9

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_9'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_9

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOCATION10'
        dataType: string
        summarizeBy: none
        sourceColumn: LOCATION10

        

        annotation SummarizationSetBy = Automatic

        
    column 'LOC_NUMBER_10'
        dataType: string
        summarizeBy: none
        sourceColumn: LOC_NUMBER_10

        

        annotation SummarizationSetBy = Automatic

        
    column 'STOP'
        dataType: string
        summarizeBy: none
        sourceColumn: STOP

        

        annotation SummarizationSetBy = Automatic

        



    partition 'STORAGE_LOCATION' = m
        mode: import
        source = 
            
let
    Source = Excel.Workbook(File.Contents("C:\Users\PowerBIUser\Documents\sample_data.xlsx"), null, true),
    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ITEM_NUMBER", type text}, {"SITE_NUMBER", type text}, {"SEGMENTS", type text}, {"LOCATION1", type text}, {"LOC_NUMBER_1", type text}, {"LOCATION2", type text}, {"LOC_NUMBER_2", type text}, {"LOCATION3", type text}, {"LOC_NUMBER_3", type text}, {"LOCATION4", type text}, {"LOC_NUMBER_4", type text}, {"LOCATION5", type text}, {"LOC_NUMBER_5", type text}, {"LOCATION6", type text}, {"LOC_NUMBER_6", type text}, {"LOCATION7", type text}, {"LOC_NUMBER_7", type text}, {"LOCATION8", type text}, {"LOC_NUMBER_8", type text}, {"LOCATION9", type text}, {"LOC_NUMBER_9", type text}, {"LOCATION10", type text}, {"LOC_NUMBER_10", type text}, {"STOP", type text}, {"ITEM_NUMBER", type text}, {"SITE_NUMBER", type text}, {"SEGMENTS", type text}, {"LOCATION1", type text}, {"LOC_NUMBER_1", type text}, {"LOCATION2", type text}, {"LOC_NUMBER_2", type text}, {"LOCATION3", type text}, {"LOC_NUMBER_3", type text}, {"LOCATION4", type text}, {"LOC_NUMBER_4", type text}, {"LOCATION5", type text}, {"LOC_NUMBER_5", type text}, {"LOCATION6", type text}, {"LOC_NUMBER_6", type text}, {"LOCATION7", type text}, {"LOC_NUMBER_7", type text}, {"LOCATION8", type text}, {"LOC_NUMBER_8", type text}, {"LOCATION9", type text}, {"LOC_NUMBER_9", type text}, {"LOCATION10", type text}, {"LOC_NUMBER_10", type text}, {"STOP", type text}})
in
    #"Changed Type"

        



    annotation PBI_ResultType = Table