table WO_MATERIALS


    column 'SITE'
        dataType: string
        summarizeBy: none
        sourceColumn: SITE

        

        annotation SummarizationSetBy = Automatic

        
    column 'WORKORDER'
        dataType: string
        summarizeBy: none
        sourceColumn: WORKORDER

        

        annotation SummarizationSetBy = Automatic

        
    column 'REC_TYP'
        dataType: string
        summarizeBy: none
        sourceColumn: REC_TYP

        

        annotation SummarizationSetBy = Automatic

        
    column 'ITEM_NUM'
        dataType: string
        summarizeBy: none
        sourceColumn: ITEM_NUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'PO_NUM'
        dataType: string
        summarizeBy: none
        sourceColumn: PO_NUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'SERIAL_NUM'
        dataType: string
        summarizeBy: none
        sourceColumn: SERIAL_NUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'MODEL_NUM'
        dataType: string
        summarizeBy: none
        sourceColumn: MODEL_NUM

        

        annotation SummarizationSetBy = Automatic

        
    column 'UNIT_MEAS'
        dataType: string
        summarizeBy: none
        sourceColumn: UNIT_MEAS

        

        annotation SummarizationSetBy = Automatic

        
    column 'QTY'
        dataType: string
        summarizeBy: none
        sourceColumn: QTY

        

        annotation SummarizationSetBy = Automatic

        
    column 'DESCRIPTION'
        dataType: string
        summarizeBy: none
        sourceColumn: DESCRIPTION

        

        annotation SummarizationSetBy = Automatic

        
    column 'MODEL_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: MODEL_TYPE

        

        annotation SummarizationSetBy = Automatic

        
    column 'MARK_NUMBER'
        dataType: string
        summarizeBy: none
        sourceColumn: MARK_NUMBER

        

        annotation SummarizationSetBy = Automatic

        



    partition 'WO_MATERIALS' = m
        mode: import
        source = 
            
let
    Source = Excel.Workbook(File.Contents("C:\Users\PowerBIUser\Documents\sample_data.xlsx"), null, true),
    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SITE", type text}, {"WORKORDER", type text}, {"REC_TYP", type text}, {"ITEM_NUM", type text}, {"PO_NUM", type text}, {"SERIAL_NUM", type text}, {"MODEL_NUM", type text}, {"UNIT_MEAS", type text}, {"QTY", type text}, {"DESCRIPTION", type text}, {"MODEL_TYPE", type text}, {"MARK_NUMBER", type text}, {"SITE", type text}, {"WORKORDER", type text}, {"REC_TYP", type text}, {"ITEM_NUM", type text}, {"PO_NUM", type text}, {"SERIAL_NUM", type text}, {"MODEL_NUM", type text}, {"UNIT_MEAS", type text}, {"QTY", type text}, {"DESCRIPTION", type text}, {"MODEL_TYPE", type text}, {"MARK_NUMBER", type text}})
in
    #"Changed Type"

        



    annotation PBI_ResultType = Table