Report: IssueReturnDetail_UC015_for_PONumberQuery

Cognos Query: 
select distinct "MATERIAL_CHARGES"."SITE_NUMBER" "SITE_NUMBER", "MATERIAL_CHARGES"."ITEM_NUMBER" "ITEM_NUMBER", "MATERIAL_CHARGES"."CHARGED_DATE" "CHARGED_DATE", "MATERIAL_CHARGES"."TIME_ENTERED" "TIME_ENTERED", "MATERIAL_CHARGES"."TRANSACTION_VALUE" "TRANSACTION_VALUE", "MATERIAL_CHARGES"."PO_NUMBER" "PO_NUMBER1", "MATERIAL_CHARGES"."JOB_NUMBER" "JOB_NUMBER", "MATERIAL_CHARGES"."ISSUE_TICKET_NUMBER" "ISSUE_TICKET_NUMBER", "MATERIAL_CHARGES"."UNIT_PRICE" "UNIT_PRICE", "MATERIAL_CHARGES"."QUANTITY" "QUANTITY", "MATERIAL_CHARGES"."TRANSACTION_TYPE" "TRANSACTION_TYPE", "PURCHASE_ORDER_LINE"."SITE_NUMBER" "SITE_NUMBER1", "PURCHASE_ORDER_LINE"."PO_NUMBER" "PO_NUMBER", "PURCHASE_ORDER_LINE"."RELEASE_NUMBER" "RELEASE_NUMBER", "PURCHASE_ORDER_LINE"."PO_LINE_NUMBER" "PO_LINE_NUMBER", "MATERIAL_CHARGES"."ROOT_DESCRIPTION" "ROOT_DESCRIPTION", "MATERIAL_CHARGES"."ITT_KEY_NO" "ITT_KEY_NO", "MATERIAL_CHARGES"."MATERIAL_CLASS" "MATERIAL_CLASS", "MATERIAL_CHARGES"."TRANSFER_NUMBER" "TRANSFER_NUMBER", "ITEM_SITE_EXTRACT"."UNIT_OF_MEASURE" "UNIT_OF_MEASURE", case  when "MATERIAL_CHARGES"."UNIT_PRICE">0 then "MATERIAL_CHARGES"."UNIT_PRICE"*"MATERIAL_CHARGES"."QUANTITY" else "MATERIAL_CHARGES"."TRANSACTION_VALUE" end  "TotalCost"
 from ("MATWPT"."ITEM_SITE_EXTRACT" "ITEM_SITE_EXTRACT" INNER JOIN "MATWPT"."MATERIAL_CHARGES" "MATERIAL_CHARGES" on "ITEM_SITE_EXTRACT"."SITE_NUMBER"="MATERIAL_CHARGES"."SITE_NUMBER" and "ITEM_SITE_EXTRACT"."ITEM_NUMBER"="MATERIAL_CHARGES"."ITEM_NUMBER") LEFT OUTER JOIN "MATWPT"."PURCHASE_ORDER_LINE" "PURCHASE_ORDER_LINE" on "ITEM_SITE_EXTRACT"."SITE_NUMBER"="PURCHASE_ORDER_LINE"."SITE_NUMBER" and "ITEM_SITE_EXTRACT"."ITEM_NUMBER"="PURCHASE_ORDER_LINE"."ITEM_NUMBER"
 where "MATERIAL_CHARGES"."SITE_NUMBER"=CAST( :PQ5 AS VARCHAR( 2 CHAR ) ) and "MATERIAL_CHARGES"."ITEM_NUMBER"=CAST( :PQ2 AS VARCHAR( 8 CHAR ) ) and "MATERIAL_CHARGES"."CHARGED_DATE"=CAST( ( :PQ1 ) AS TIMESTAMP ) and "MATERIAL_CHARGES"."TIME_ENTERED"=CAST( :PQ6 AS VARCHAR( 8 CHAR ) ) and "PURCHASE_ORDER_LINE"."PO_NUMBER"=CAST( :PQ4 AS VARCHAR( 8 CHAR ) ) and "PURCHASE_ORDER_LINE"."PO_LINE_NUMBER"=CAST( :PQ3 AS VARCHAR( 3 CHAR ) )
 

Report: IssueReturnInquiry_UC006_by_PO_Number
 
 Cognos Queries:
select "PURCHASE_ORDER_LINE"."SITE_NUMBER" "SITE_NUMBER", "PURCHASE_ORDER_LINE"."PO_NUMBER" "PO_NUMBER", "PURCHASE_ORDER_LINE"."RELEASE_NUMBER" "RELEASE_NUMBER", "PURCHASE_ORDER_LINE"."PO_LINE_NUMBER" "PO_LINE_NUMBER", "PURCHASE_ORDER_LINE"."ITEM_NUMBER" "ITEM_NUMBER", "MATERIAL_CHARGES"."CHARGED_DATE" "CHARGED_DATE", "MATERIAL_CHARGES"."TIME_ENTERED" "TIME_ENTERED", "MATERIAL_CHARGES"."ISSUE_TICKET_NUMBER" "ISSUE_TICKET_NUMBER", "MATERIAL_CHARGES"."QUANTITY" "QUANTITY", "MATERIAL_CHARGES"."JOB_NUMBER" "JOB_NUMBER", "MATERIAL_CHARGES"."TRANSACTION_TYPE" "TRANSACTION_TYPE", "MATERIAL_CHARGES"."UNIT_PRICE" "UNIT_PRICE", "MATERIAL_CHARGES"."ADJUSTMENT_TYPE" "ADJUSTMENT_TYPE", "MATERIAL_CHARGES"."ITT_KEY_NO" "ITT_KEY_NO", "MATERIAL_CHARGES"."TRANSFER_NUMBER" "TRANSFER_NUMBER", "MATERIAL_CHARGES"."MATERIAL_CLASS" "MATERIAL_CLASS"
 from "MATWPT"."PURCHASE_ORDER_LINE" "PURCHASE_ORDER_LINE" LEFT OUTER JOIN "MATWPT"."MATERIAL_CHARGES" "MATERIAL_CHARGES" on "PURCHASE_ORDER_LINE"."SITE_NUMBER"="MATERIAL_CHARGES"."SITE_NUMBER" and "PURCHASE_ORDER_LINE"."ITEM_NUMBER"="MATERIAL_CHARGES"."ITEM_NUMBER"
 where "PURCHASE_ORDER_LINE"."SITE_NUMBER"=CAST( :PQ2 AS CHAR( 2 CHAR ) ) and "PURCHASE_ORDER_LINE"."PO_NUMBER"=upper ('123') and "PURCHASE_ORDER_LINE"."PO_LINE_NUMBER"=CAST( :PQ1 AS VARCHAR( 3 CHAR ) ) and "MATERIAL_CHARGES"."ADJUSTMENT_TYPE" is null
 order by "CHARGED_DATE" asc nulls last
 
 Prompt in Cognos:
 
select "SITES"."SITE_NUMBER" "SITE_NUMBER", "SITES"."SITE_NAME" "SITE_NAME"
 from "MATWPT"."SITES" "SITES"
 order by "SITE_NUMBER" asc nulls last, "SITE_NAME" asc nulls last
 
Report: WPT_InquiryAboutWorkOrder_UC021
 
 Cognos Queries:
 
select "WORK_ORDERS"."WORK_ORDER_SITE" "WORK_ORDER_SITE", "WORK_ORDERS"."WORK_ORDER_NUMBER" "WORK_ORDER_NUMBER", "WORK_ORDERS"."WORK_ORDER_DESC" "WORK_ORDER_DESC", "WORK_ORDERS"."W_O_TYPE" "W_O_TYPE", "WORK_ORDERS"."W_O_STATUS" "W_O_STATUS", "WORK_ORDERS"."MARK_NUMBER" "MARK_NUMBER", "WORK_ORDERS"."MARK_NUMBER_COMPRESSED" "MARK_NUMBER_COMPRESSED", "WORK_ORDERS"."WORK_COMPLETED" "WORK_COMPLETED"
 from "MATWPT"."WORK_ORDERS" "WORK_ORDERS"
 where "WORK_ORDERS"."WORK_ORDER_SITE"=CAST( :PQ1 AS VARCHAR( 2 CHAR ) ) and "WORK_ORDERS"."WORK_ORDER_SITE"=CAST( :PQ1 AS VARCHAR( 2 CHAR ) ) and "WORK_ORDERS"."WORK_ORDER_SITE"=CAST( :PQ1 AS VARCHAR( 2 CHAR ) )
 order by "WORK_COMPLETED" desc nulls last
 
 Prompt Query:
 
select distinct "SITES"."SITE_NAME" "SITE_NAME", "SITES"."SITE_NUMBER" "SITE_NUMBER", "WORK_ORDERS"."WORK_ORDER_SITE" "Data_Item"
 from "MATWPT"."SITES" "SITES", "MATWPT"."WORK_ORDERS" "WORK_ORDERS"
 where "SITES"."SITE_NUMBER"="WORK_ORDERS"."WORK_ORDER_SITE"
 order by "SITE_NAME" asc nulls last
 

Report: WPT_PlannedDocuments_PlannedWorkOrder_UC039

Cognos Query:

select distinct "WO_DOCUMENTS"."SITE" "SITE", "WO_DOCUMENTS"."WORKORDER" "WORKORDER", "WORK_ORDERS"."MARK_NUMBER" "MARK_NUMBER", "WORK_ORDERS"."WORK_ORDER_DESC" "WORK_ORDER_DESC", "WO_DOCUMENTS"."TYPE" "TYPE", "WO_DOCUMENTS"."DOCUMENT_NUM" "DOCUMENT_NUM", "WO_DOCUMENTS"."REC_TYP" "REC_TYP", "WO_DOCUMENTS"."CLASS" "CLASS8", case  when "WO_DOCUMENTS"."CLASS" is null  or "WO_DOCUMENTS"."TYPE" is null  then  null  else "WO_DOCUMENTS"."CLASS" || "WO_DOCUMENTS"."TYPE" end  "displayDocType"
 from "MATWPT"."WORK_ORDERS" "WORK_ORDERS" LEFT OUTER JOIN "MATWPT"."WO_DOCUMENTS" "WO_DOCUMENTS" on "WORK_ORDERS"."WORK_ORDER_SITE"="WO_DOCUMENTS"."SITE" and "WORK_ORDERS"."WORK_ORDER_NUMBER"="WO_DOCUMENTS"."WORKORDER"
 where "WO_DOCUMENTS"."SITE"=CAST( :PQ1 AS VARCHAR( 2 CHAR ) ) and "WO_DOCUMENTS"."WORKORDER"=CAST( :PQ2 AS VARCHAR( 6 CHAR ) )

 
 

 
 
 
 