table 'Agency'


    column 'AgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: AgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyUserID'
        dataType: string
        summarizeBy: none
        sourceColumn: AgencyUserID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyName'
        dataType: string
        summarizeBy: none
        sourceColumn: AgencyName

        annotation SummarizationSetBy = Automatic

        
    column 'Address1'
        dataType: string
        summarizeBy: none
        sourceColumn: Address1

        annotation SummarizationSetBy = Automatic

        
    column 'Address2'
        dataType: string
        summarizeBy: none
        sourceColumn: Address2

        annotation SummarizationSetBy = Automatic

        
    column 'City'
        dataType: string
        summarizeBy: none
        sourceColumn: City

        annotation SummarizationSetBy = Automatic

        
    column 'State'
        dataType: string
        summarizeBy: none
        sourceColumn: State

        annotation SummarizationSetBy = Automatic

        
    column 'Zip'
        dataType: string
        summarizeBy: none
        sourceColumn: Zip

        annotation SummarizationSetBy = Automatic

        
    column 'Phone'
        dataType: string
        summarizeBy: none
        sourceColumn: Phone

        annotation SummarizationSetBy = Automatic

        
    column 'Fax'
        dataType: string
        summarizeBy: none
        sourceColumn: Fax

        annotation SummarizationSetBy = Automatic

        
    column 'ContactName'
        dataType: string
        summarizeBy: none
        sourceColumn: ContactName

        annotation SummarizationSetBy = Automatic

        
    column 'Email'
        dataType: string
        summarizeBy: none
        sourceColumn: Email

        annotation SummarizationSetBy = Automatic

        
    column 'DistributionAgencyID'
        dataType: int64
        summarizeBy: none
        sourceColumn: DistributionAgencyID

        annotation SummarizationSetBy = Automatic

        
    column 'DivisionID'
        dataType: int64
        summarizeBy: none
        sourceColumn: DivisionID

        annotation SummarizationSetBy = Automatic

        
    column 'AgencyType'
        dataType: string
        summarizeBy: none
        sourceColumn: AgencyType

        annotation SummarizationSetBy = Automatic

        
    column 'IsActive'
        dataType: string
        summarizeBy: none
        sourceColumn: IsActive

        annotation SummarizationSetBy = Automatic

        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'datecreated'
        dataType: string
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
    column 'LastUpdated'
        dataType: string
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        
    column 'Season'
        dataType: string
        summarizeBy: none
        sourceColumn: Season

        annotation SummarizationSetBy = Automatic

        
    column 'Date Submitted'
        dataType: string
        summarizeBy: none
        sourceColumn: Date Submitted

        annotation SummarizationSetBy = Automatic

        
    column 'FuelType'
        dataType: string
        summarizeBy: none
        sourceColumn: FuelType

        annotation SummarizationSetBy = Automatic

        
    column 'PaidByEnergyShare'
        dataType: string
        summarizeBy: none
        sourceColumn: PaidByEnergyShare

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableYear'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableYear

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicableMonth'
        dataType: int64
        summarizeBy: none
        sourceColumn: ApplicableMonth

        annotation SummarizationSetBy = Automatic

        
    column 'Type'
        dataType: string
        summarizeBy: none
        sourceColumn: Type

        annotation SummarizationSetBy = Automatic

        
    column 'Applicant Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Applicant Name

        annotation SummarizationSetBy = Automatic

        
    column 'EditLink'
        dataType: string
        summarizeBy: none
        sourceColumn: EditLink

        annotation SummarizationSetBy = Automatic

        
    column 'AmountDueVeteranVoucher'
        dataType: string
        summarizeBy: none
        sourceColumn: AmountDueVeteranVoucher

        annotation SummarizationSetBy = Automatic

        
    column 'AmountDueDisabilityVoucher'
        dataType: string
        summarizeBy: none
        sourceColumn: AmountDueDisabilityVoucher

        annotation SummarizationSetBy = Automatic

        
    column 'TotalVeteranVoucher'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalVeteranVoucher

        annotation SummarizationSetBy = Automatic

        
    column 'TotalDisabilityVoucher'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalDisabilityVoucher

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantAddress'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantAddress

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantCity'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantCity

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantState'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantState

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantZip'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantZip

        annotation SummarizationSetBy = Automatic

        
    column 'ApplicantPhone'
        dataType: string
        summarizeBy: none
        sourceColumn: ApplicantPhone

        annotation SummarizationSetBy = Automatic

        
    column 'DepositGuarantee'
        dataType: string
        summarizeBy: none
        sourceColumn: DepositGuarantee

        annotation SummarizationSetBy = Automatic

        
    column 'IsOver60'
        dataType: string
        summarizeBy: none
        sourceColumn: IsOver60

        annotation SummarizationSetBy = Automatic

        
    column 'IsMedical'
        dataType: string
        summarizeBy: none
        sourceColumn: IsMedical

        annotation SummarizationSetBy = Automatic

        
    column 'NumberOfCust'
        dataType: int64
        summarizeBy: none
        sourceColumn: NumberOfCust

        annotation SummarizationSetBy = Automatic

        
    column 'TotalUnder5'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalUnder5

        annotation SummarizationSetBy = Automatic

        
    column 'TotalOver60'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalOver60

        annotation SummarizationSetBy = Automatic

        
    column 'TotalDisabled'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalDisabled

        annotation SummarizationSetBy = Automatic

        
    column 'TotalVeteran'
        dataType: int64
        summarizeBy: none
        sourceColumn: TotalVeteran

        annotation SummarizationSetBy = Automatic

        
    column 'IsInterestedInWeatherization'
        dataType: string
        summarizeBy: none
        sourceColumn: IsInterestedInWeatherization

        annotation SummarizationSetBy = Automatic

        
    column 'DominionAccountNumber'
        dataType: string
        summarizeBy: none
        sourceColumn: DominionAccountNumber

        annotation SummarizationSetBy = Automatic

        
    column 'BusinessType'
        dataType: string
        summarizeBy: none
        sourceColumn: BusinessType

        annotation SummarizationSetBy = Automatic

        
    column 'CustomBusinessType'
        dataType: string
        summarizeBy: none
        sourceColumn: CustomBusinessType

        annotation SummarizationSetBy = Automatic

        



    partition 'Agency' = m
        mode: import
        source = 
            	let
					Source = Sql.Database("", "", [Query = "Select * from [Shared_Energy_Share].tblAgency"]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"AgencyID", Int64.Type}, {"AgencyUserID", type text}, {"AgencyName", type text}, {"Address1", type text}, {"Address2", type text}, {"City", type text}, {"State", type text}, {"Zip", type text}, {"Phone", type text}, {"Fax", type text}, {"ContactName", type text}, {"Email", type text}, {"DistributionAgencyID", Int64.Type}, {"DivisionID", Int64.Type}, {"AgencyType", type text}, {"IsActive", type text}, {"CreatedBy", type text}, {"datecreated", type text}, {"UpdatedBy", type text}, {"LastUpdated", type text}, {"Season", type text}, {"Date Submitted", type text}, {"FuelType", type text}, {"PaidByEnergyShare", type text}, {"ApplicableYear", Int64.Type}, {"ApplicableMonth", Int64.Type}, {"Type", type text}, {"Applicant Name", type text}, {"EditLink", type text}, {"AmountDueVeteranVoucher", type text}, {"AmountDueDisabilityVoucher", type text}, {"TotalVeteranVoucher", Int64.Type}, {"TotalDisabilityVoucher", Int64.Type}, {"ApplicantAddress", type text}, {"ApplicantCity", type text}, {"ApplicantState", type text}, {"ApplicantZip", type text}, {"ApplicantPhone", type text}, {"DepositGuarantee", type text}, {"IsOver60", type text}, {"IsMedical", type text}, {"NumberOfCust", Int64.Type}, {"TotalUnder5", Int64.Type}, {"TotalOver60", Int64.Type}, {"TotalDisabled", Int64.Type}, {"TotalVeteran", Int64.Type}, {"IsInterestedInWeatherization", type text}, {"DominionAccountNumber", type text}, {"BusinessType", type text}, {"CustomBusinessType", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table