table 'BILLABLE ELECTRIC'


    column 'ID_PREM'
        dataType: string
        summarizeBy: none
        sourceColumn: ID_PREM

        annotation SummarizationSetBy = Automatic

        
    column 'ID_SPT'
        dataType: string
        summarizeBy: none
        sourceColumn: ID_SPT

        annotation SummarizationSetBy = Automatic

        
    column 'TS_BILL_UNIT'
        dataType: string
        summarizeBy: none
        sourceColumn: TS_BILL_UNIT

        annotation SummarizationSetBy = Automatic

        
    column 'ID_BA'
        dataType: string
        summarizeBy: none
        sourceColumn: ID_BA

        annotation SummarizationSetBy = Automatic

        
    column 'CD_BILLED'
        dataType: string
        summarizeBy: none
        sourceColumn: CD_BILLED

        annotation SummarizationSetBy = Automatic

        
    column 'QY_DAYS_USED'
        dataType: string
        summarizeBy: none
        sourceColumn: QY_DAYS_USED

        annotation SummarizationSetBy = Automatic

        
    column 'DT_BILL_END'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DT_BILL_END

        annotation SummarizationSetBy = Automatic

        
    column 'CD_REBATE_RSN'
        dataType: string
        summarizeBy: none
        sourceColumn: CD_REBATE_RSN

        annotation SummarizationSetBy = Automatic

        
    column 'DT_BU_STAT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DT_BU_STAT

        annotation SummarizationSetBy = Automatic

        
    column 'CD_RDG_SRCE'
        dataType: string
        summarizeBy: none
        sourceColumn: CD_RDG_SRCE

        annotation SummarizationSetBy = Automatic

        
    column 'CD_RDG_INFO'
        dataType: string
        summarizeBy: none
        sourceColumn: CD_RDG_INFO

        annotation SummarizationSetBy = Automatic

        
    column 'CD_RDG_RSN'
        dataType: string
        summarizeBy: none
        sourceColumn: CD_RDG_RSN

        annotation SummarizationSetBy = Automatic

        
    column 'QY_TOT_UNIT'
        dataType: string
        summarizeBy: none
        sourceColumn: QY_TOT_UNIT

        annotation SummarizationSetBy = Automatic

        
    column 'CD_SEASON'
        dataType: string
        summarizeBy: none
        sourceColumn: CD_SEASON

        annotation SummarizationSetBy = Automatic

        
    column 'FL_PRORT'
        dataType: string
        summarizeBy: none
        sourceColumn: FL_PRORT

        annotation SummarizationSetBy = Automatic

        



    partition 'BILLABLE ELECTRIC' = m
        mode: import
        source = 
            	let
					Source = Sql.Database("", "", [Query = "Select ID_PREM, ID_SPT, TS_BILL_UNIT, ID_BA, CD_BILLED, QY_DAYS_USED, DT_BILL_END, CD_REBATE_RSN, DT_BU_STAT, CD_RDG_SRCE, CD_RDG_INFO, CD_RDG_RSN, QY_TOT_UNIT, CD_SEASON, FL_PRORT, ID_PREM, ID_SPT, TS_BILL_UNIT, ID_BA, CD_BILLED, QY_DAYS_USED, DT_BILL_END, CD_REBATE_RSN, DT_BU_STAT, CD_RDG_SRCE, CD_RDG_INFO, CD_RDG_RSN, QY_TOT_UNIT, CD_SEASON, FL_PRORT from [BILLABLE ELECTRIC]"]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"ID_PREM", type text}, {"ID_SPT", type text}, {"TS_BILL_UNIT", type text}, {"ID_BA", type text}, {"CD_BILLED", type text}, {"QY_DAYS_USED", type text}, {"DT_BILL_END", type datetime}, {"CD_REBATE_RSN", type text}, {"DT_BU_STAT", type datetime}, {"CD_RDG_SRCE", type text}, {"CD_RDG_INFO", type text}, {"CD_RDG_RSN", type text}, {"QY_TOT_UNIT", type text}, {"CD_SEASON", type text}, {"FL_PRORT", type text}, {"ID_PREM", type text}, {"ID_SPT", type text}, {"TS_BILL_UNIT", type text}, {"ID_BA", type text}, {"CD_BILLED", type text}, {"QY_DAYS_USED", type text}, {"DT_BILL_END", type datetime}, {"CD_REBATE_RSN", type text}, {"DT_BU_STAT", type datetime}, {"CD_RDG_SRCE", type text}, {"CD_RDG_INFO", type text}, {"CD_RDG_RSN", type text}, {"QY_TOT_UNIT", type text}, {"CD_SEASON", type text}, {"FL_PRORT", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table