table 'CU04TB70'


    column 'ID_MTR'
        dataType: string
        summarizeBy: none
        sourceColumn: ID_MTR

        annotation SummarizationSetBy = Automatic

        
    column 'CD_MTR_MFG'
        dataType: string
        summarizeBy: none
        sourceColumn: CD_MTR_MFG

        annotation SummarizationSetBy = Automatic

        
    column 'CD_SVC_TYP'
        dataType: string
        summarizeBy: none
        sourceColumn: CD_SVC_TYP

        annotation SummarizationSetBy = Automatic

        
    column 'DT_MTR_SET'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DT_MTR_SET

        annotation SummarizationSetBy = Automatic

        
    column 'ID_PREM'
        dataType: string
        summarizeBy: none
        sourceColumn: ID_PREM

        annotation SummarizationSetBy = Automatic

        
    column 'ID_SPT'
        dataType: string
        summarizeBy: none
        sourceColumn: ID_SPT

        annotation SummarizationSetBy = Automatic

        
    column 'DT_MTR_REMV'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DT_MTR_REMV

        annotation SummarizationSetBy = Automatic

        
    column 'QY_MTR_REMV_INDX'
        dataType: string
        summarizeBy: none
        sourceColumn: QY_MTR_REMV_INDX

        annotation SummarizationSetBy = Automatic

        
    column 'CD_MTR_REMV_RSN'
        dataType: string
        summarizeBy: none
        sourceColumn: CD_MTR_REMV_RSN

        annotation SummarizationSetBy = Automatic

        



    partition 'CU04TB70' = m
        mode: import
        source = 
            	let
					Source = Sql.Database("", "", [Query = "Select ID_MTR, CD_MTR_MFG, CD_SVC_TYP, DT_MTR_SET, ID_PREM, ID_SPT, DT_MTR_REMV, QY_MTR_REMV_INDX, CD_MTR_REMV_RSN, ID_MTR, CD_MTR_MFG, CD_SVC_TYP, DT_MTR_SET, ID_PREM, ID_SPT, DT_MTR_REMV, QY_MTR_REMV_INDX, CD_MTR_REMV_RSN from CU04TB70"]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"ID_MTR", type text}, {"CD_MTR_MFG", type text}, {"CD_SVC_TYP", type text}, {"DT_MTR_SET", type datetime}, {"ID_PREM", type text}, {"ID_SPT", type text}, {"DT_MTR_REMV", type datetime}, {"QY_MTR_REMV_INDX", type text}, {"CD_MTR_REMV_RSN", type text}, {"ID_MTR", type text}, {"CD_MTR_MFG", type text}, {"CD_SVC_TYP", type text}, {"DT_MTR_SET", type datetime}, {"ID_PREM", type text}, {"ID_SPT", type text}, {"DT_MTR_REMV", type datetime}, {"QY_MTR_REMV_INDX", type text}, {"CD_MTR_REMV_RSN", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table