table 'D_OFS_DOMINION_QUEUE_DETAIL'


    column 'QUEUE_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: QUEUE_ID

        annotation SummarizationSetBy = Automatic

        
    column 'QUEUE_DATE'
        dataType: string
        summarizeBy: none
        sourceColumn: QUEUE_DATE

        annotation SummarizationSetBy = Automatic

        
    column 'NOT_AVAILABLE_FOR_ROUTING'
        dataType: string
        summarizeBy: none
        sourceColumn: NOT_AVAILABLE_FOR_ROUTING

        annotation SummarizationSetBy = Automatic

        
    column 'PERSONNEL_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: PERSONNEL_TYPE

        annotation SummarizationSetBy = Automatic

        
    column 'PHONE'
        dataType: string
        summarizeBy: none
        sourceColumn: PHONE

        annotation SummarizationSetBy = Automatic

        
    column 'QUEUE_REACTIVATION_TIME'
        dataType: string
        summarizeBy: none
        sourceColumn: QUEUE_REACTIVATION_TIME

        annotation SummarizationSetBy = Automatic

        
    column 'QUOTA_MANAGEMENT'
        dataType: string
        summarizeBy: none
        sourceColumn: QUOTA_MANAGEMENT

        annotation SummarizationSetBy = Automatic

        
    column 'RESOURCE_TYPE'
        dataType: string
        summarizeBy: none
        sourceColumn: RESOURCE_TYPE

        annotation SummarizationSetBy = Automatic

        
    column 'CALENDAR_END_TIME'
        dataType: string
        summarizeBy: none
        sourceColumn: CALENDAR_END_TIME

        annotation SummarizationSetBy = Automatic

        
    column 'CALENDAR_START_TIME'
        dataType: string
        summarizeBy: none
        sourceColumn: CALENDAR_START_TIME

        annotation SummarizationSetBy = Automatic

        
    column 'PROPERTY_12'
        dataType: string
        summarizeBy: none
        sourceColumn: PROPERTY_12

        annotation SummarizationSetBy = Automatic

        
    column 'PROPERTY_302'
        dataType: string
        summarizeBy: none
        sourceColumn: PROPERTY_302

        annotation SummarizationSetBy = Automatic

        
    column 'PROPERTY_375'
        dataType: string
        summarizeBy: none
        sourceColumn: PROPERTY_375

        annotation SummarizationSetBy = Automatic

        
    column 'PROPERTY_379'
        dataType: string
        summarizeBy: none
        sourceColumn: PROPERTY_379

        annotation SummarizationSetBy = Automatic

        
    column 'PROPERTY_381'
        dataType: string
        summarizeBy: none
        sourceColumn: PROPERTY_381

        annotation SummarizationSetBy = Automatic

        
    column 'PROPERTY_84'
        dataType: string
        summarizeBy: none
        sourceColumn: PROPERTY_84

        annotation SummarizationSetBy = Automatic

        
    column 'PROVIDER_EXT_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: PROVIDER_EXT_ID

        annotation SummarizationSetBy = Automatic

        
    column 'PROVIDER_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: PROVIDER_ID

        annotation SummarizationSetBy = Automatic

        
    column 'PROVIDER_POOL'
        dataType: string
        summarizeBy: none
        sourceColumn: PROVIDER_POOL

        annotation SummarizationSetBy = Automatic

        
    column 'PROVIDER_SOURCE'
        dataType: string
        summarizeBy: none
        sourceColumn: PROVIDER_SOURCE

        annotation SummarizationSetBy = Automatic

        
    column 'PROVIDER_TIMEZONE'
        dataType: string
        summarizeBy: none
        sourceColumn: PROVIDER_TIMEZONE

        annotation SummarizationSetBy = Automatic

        
    column 'QUEUE_ACTIVATE_TIME'
        dataType: string
        summarizeBy: none
        sourceColumn: QUEUE_ACTIVATE_TIME

        annotation SummarizationSetBy = Automatic

        
    column 'QUEUE_DEACTIVATE_TIME'
        dataType: string
        summarizeBy: none
        sourceColumn: QUEUE_DEACTIVATE_TIME

        annotation SummarizationSetBy = Automatic

        
    column 'SYS_UPDATE_TS'
        dataType: string
        summarizeBy: none
        sourceColumn: SYS_UPDATE_TS

        annotation SummarizationSetBy = Automatic

        



    partition 'D_OFS_DOMINION_QUEUE_DETAIL' = m
        mode: import
        source = 
            let Source = Sql.Database("", "", [Query = "Select QUEUE_ID, QUEUE_DATE, NOT_AVAILABLE_FOR_ROUTING, PERSONNEL_TYPE, PHONE, QUEUE_REACTIVATION_TIME, QUOTA_MANAGEMENT, RESOURCE_TYPE, CALENDAR_END_TIME, CALENDAR_START_TIME, PROPERTY_12, PROPERTY_302, PROPERTY_375, PROPERTY_379, PROPERTY_381, PROPERTY_84, PROVIDER_EXT_ID, PROVIDER_ID, PROVIDER_POOL, PROVIDER_SOURCE, PROVIDER_TIMEZONE, QUEUE_ACTIVATE_TIME, QUEUE_DEACTIVATE_TIME, SYS_UPDATE_TS, QUEUE_ID, QUEUE_DATE, NOT_AVAILABLE_FOR_ROUTING, PERSONNEL_TYPE, PHONE, QUEUE_REACTIVATION_TIME, QUOTA_MANAGEMENT, RESOURCE_TYPE, CALENDAR_END_TIME, CALENDAR_START_TIME, PROPERTY_12, PROPERTY_302, PROPERTY_375, PROPERTY_379, PROPERTY_381, PROPERTY_84, PROVIDER_EXT_ID, PROVIDER_ID, PROVIDER_POOL, PROVIDER_SOURCE, PROVIDER_TIMEZONE, QUEUE_ACTIVATE_TIME, QUEUE_DEACTIVATE_TIME, SYS_UPDATE_TS from D_OFS_DOMINION_QUEUE_DETAIL"]), #"Removed Errors" = Table.RemoveRowsWithErrors(Source), #"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"QUEUE_ID", type text}, {"QUEUE_DATE", type text}, {"NOT_AVAILABLE_FOR_ROUTING", type text}, {"PERSONNEL_TYPE", type text}, {"PHONE", type text}, {"QUEUE_REACTIVATION_TIME", type text}, {"QUOTA_MANAGEMENT", type text}, {"RESOURCE_TYPE", type text}, {"CALENDAR_END_TIME", type text}, {"CALENDAR_START_TIME", type text}, {"PROPERTY_12", type text}, {"PROPERTY_302", type text}, {"PROPERTY_375", type text}, {"PROPERTY_379", type text}, {"PROPERTY_381", type text}, {"PROPERTY_84", type text}, {"PROVIDER_EXT_ID", type text}, {"PROVIDER_ID", type text}, {"PROVIDER_POOL", type text}, {"PROVIDER_SOURCE", type text}, {"PROVIDER_TIMEZONE", type text}, {"QUEUE_ACTIVATE_TIME", type text}, {"QUEUE_DEACTIVATE_TIME", type text}, {"SYS_UPDATE_TS", type text}, {"QUEUE_ID", type text}, {"QUEUE_DATE", type text}, {"NOT_AVAILABLE_FOR_ROUTING", type text}, {"PERSONNEL_TYPE", type text
        



    annotation PBI_ResultType = Table