table 'D_OFS_DOMINION_GPS_TRACKS'


    column 'AID'
        dataType: string
        summarizeBy: none
        sourceColumn: AID

        annotation SummarizationSetBy = Automatic

        
    column 'QUEUE_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: QUEUE_ID

        annotation SummarizationSetBy = Automatic

        
    column 'LONGITUDE'
        dataType: string
        summarizeBy: none
        sourceColumn: LONGITUDE

        annotation SummarizationSetBy = Automatic

        
    column 'LATITUDE'
        dataType: string
        summarizeBy: none
        sourceColumn: LATITUDE

        annotation SummarizationSetBy = Automatic

        
    column 'DISTANCE'
        dataType: string
        summarizeBy: none
        sourceColumn: DISTANCE

        annotation SummarizationSetBy = Automatic

        
    column 'STATUS'
        dataType: string
        summarizeBy: none
        sourceColumn: STATUS

        annotation SummarizationSetBy = Automatic

        
    column 'IDLE'
        dataType: string
        summarizeBy: none
        sourceColumn: IDLE

        annotation SummarizationSetBy = Automatic

        
    column 'TIME_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: TIME_ID

        annotation SummarizationSetBy = Automatic

        
    column 'SYS_UPDATE_TS'
        dataType: string
        summarizeBy: none
        sourceColumn: SYS_UPDATE_TS

        annotation SummarizationSetBy = Automatic

        



    partition 'D_OFS_DOMINION_GPS_TRACKS' = m
        mode: import
        source = 
            	let
					Source = Sql.Database("", "", [Query = "Select AID, QUEUE_ID, LONGITUDE, LATITUDE, DISTANCE, STATUS, IDLE, TIME_ID, SYS_UPDATE_TS, AID, QUEUE_ID, LONGITUDE, LATITUDE, DISTANCE, STATUS, IDLE, TIME_ID, SYS_UPDATE_TS from D_OFS_DOMINION_GPS_TRACKS"]),
					#"Removed Errors" = Table.RemoveRowsWithErrors(Source),
					#"Changed Types" = Table.TransformColumnTypes(#"Removed Errors", {{"AID", type text}, {"QUEUE_ID", type text}, {"LONGITUDE", type text}, {"LATITUDE", type text}, {"DISTANCE", type text}, {"STATUS", type text}, {"IDLE", type text}, {"TIME_ID", type text}, {"SYS_UPDATE_TS", type text}, {"AID", type text}, {"QUEUE_ID", type text}, {"LONGITUDE", type text}, {"LATITUDE", type text}, {"DISTANCE", type text}, {"STATUS", type text}, {"IDLE", type text}, {"TIME_ID", type text}, {"SYS_UPDATE_TS", type text}})
				in
					#"Changed Types"
        



    annotation PBI_ResultType = Table