table 'Sample Data'
	lineageTag: 12345678-1234-1234-1234-123456789012

	column 'ID'
		dataType: int64
		formatString: 0
		lineageTag: 12345678-1234-1234-1234-123456789013
		summarizeBy: none
		sourceColumn: ID

	column 'Name'
		dataType: string
		lineageTag: 12345678-1234-1234-1234-123456789014
		summarizeBy: none
		sourceColumn: Name

	column 'Value'
		dataType: double
		formatString: #,0.00
		lineageTag: 12345678-1234-1234-1234-123456789015
		summarizeBy: sum
		sourceColumn: Value

	partition 'Sample Data'
		mode: import
		source =
			let
				Source = Table.FromRows({
					{"ID", "Name", "Value"},
					{1, "Sample Item 1", 100.50},
					{2, "Sample Item 2", 200.75},
					{3, "Sample Item 3", 300.25}
				}),
				#"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}, {"Name", type text}, {"Value", type number}})
			in
				#"Changed Type"

