table 'DLR'


    column 'SLS_DSTRCT_CD'
        dataType: string
        summarizeBy: none

        dataCategory: Uncategorized
        annotation SummarizationSetBy = Automatic

        
    column 'id'
        dataType: string
        summarizeBy: none

        dataCategory: Uncategorized
        annotation SummarizationSetBy = Automatic

        
    column 'AFLT_CMPNY_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: AFLT_CMPNY_CD

        annotation SummarizationSetBy = Automatic

        
    column 'ASR_DLR_FLG'
        dataType: boolean
        summarizeBy: none
        sourceColumn: ASR_DLR_FLG

        annotation SummarizationSetBy = Automatic

        
    column 'CNTRY_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: CNTRY_NM

        annotation SummarizationSetBy = Automatic

        
    column 'CRTE_TS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: CRTE_TS

        annotation SummarizationSetBy = Automatic

        
    column 'CRTE_USR_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: CRTE_USR_ID

        annotation SummarizationSetBy = Automatic

        
    column 'CTOVR_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: CTOVR_DT

        annotation SummarizationSetBy = Automatic

        
    column 'CTOVR_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: CTOVR_IN

        annotation SummarizationSetBy = Automatic

        
    column 'CTOVR_RCV_THRSLD_TM'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: CTOVR_RCV_THRSLD_TM

        annotation SummarizationSetBy = Automatic

        
    column 'CTOVR_UPDT_TS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: CTOVR_UPDT_TS

        annotation SummarizationSetBy = Automatic

        
    column 'DFLT_VLU_CHNG_MASK_TX'
        dataType: string
        summarizeBy: none
        sourceColumn: DFLT_VLU_CHNG_MASK_TX

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_1ST_DVC_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_1ST_DVC_ID

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_1ST_SCRTY_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_1ST_SCRTY_ID

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_1ST_VNDR_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_1ST_VNDR_CD

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_2ND_DVC_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_2ND_DVC_ID

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_2ND_SCRTY_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_2ND_SCRTY_ID

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_2ND_VNDR_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_2ND_VNDR_CD

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_3RD_DVC_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_3RD_DVC_ID

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_3RD_SCRTY_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_3RD_SCRTY_ID

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_3RD_VNDR_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_3RD_VNDR_CD

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_4TH_DVC_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_4TH_DVC_ID

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_4TH_SCRTY_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_4TH_SCRTY_ID

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_4TH_VNDR_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_4TH_VNDR_CD

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_CLAS_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_CLAS_CD

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_DBA_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_DBA_NM

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: DLR_NB

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_NM

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_ONRSHP_TYP_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_ONRSHP_TYP_CD

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_PRNCPL_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_PRNCPL_NM

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_STS_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: DLR_STS_IN

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_SYSTM_PRVDR_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_SYSTM_PRVDR_ID

        annotation SummarizationSetBy = Automatic

        
    column 'DLR_TYP_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: DLR_TYP_CD

        annotation SummarizationSetBy = Automatic

        
    column 'DMS_CHIP_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: DMS_CHIP_ID

        annotation SummarizationSetBy = Automatic

        
    column 'DMS_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: DMS_ID

        annotation SummarizationSetBy = Automatic

        
    column 'DOM'
        dataType: string
        summarizeBy: none
        sourceColumn: DOM

        annotation SummarizationSetBy = Automatic

        
    column 'EXCTV_MGR_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: EXCTV_MGR_NM

        annotation SummarizationSetBy = Automatic

        
    column 'FLT_WRNTY_OWNR_TYP_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: FLT_WRNTY_OWNR_TYP_IN

        annotation SummarizationSetBy = Automatic

        
    column 'FLT_WRNTY_STN_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: FLT_WRNTY_STN_IN

        annotation SummarizationSetBy = Automatic

        
    column 'INTNET_SLS_MGR_FRST_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: INTNET_SLS_MGR_FRST_NM

        annotation SummarizationSetBy = Automatic

        
    column 'INTNET_SLS_MGR_LST_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: INTNET_SLS_MGR_LST_NM

        annotation SummarizationSetBy = Automatic

        
    column 'INTNET_SLS_MGR_MIDL_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: INTNET_SLS_MGR_MIDL_NM

        annotation SummarizationSetBy = Automatic

        
    column 'LNG_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: LNG_CD

        annotation SummarizationSetBy = Automatic

        
    column 'LST_FULL_PRT_RQST_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: LST_FULL_PRT_RQST_DT

        annotation SummarizationSetBy = Automatic

        
    column 'ML_ADRS_TX'
        dataType: string
        summarizeBy: none
        sourceColumn: ML_ADRS_TX

        annotation SummarizationSetBy = Automatic

        
    column 'ML_PSTL_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: ML_PSTL_CD

        annotation SummarizationSetBy = Automatic

        
    column 'ML_ST_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: ML_ST_CD

        annotation SummarizationSetBy = Automatic

        
    column 'MNRTY_DLR_EXCTV_MGR_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: MNRTY_DLR_EXCTV_MGR_IN

        annotation SummarizationSetBy = Automatic

        
    column 'MNRTY_DLR_PRNCPL_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: MNRTY_DLR_PRNCPL_IN

        annotation SummarizationSetBy = Automatic

        
    column 'MRKT_GD_CAR_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: MRKT_GD_CAR_NB

        annotation SummarizationSetBy = Automatic

        
    column 'MRKT_GD_TOTL_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: MRKT_GD_TOTL_NB

        annotation SummarizationSetBy = Automatic

        
    column 'MRKT_GD_TRCK_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: MRKT_GD_TRCK_NB

        annotation SummarizationSetBy = Automatic

        
    column 'NMAC_DLR_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: NMAC_DLR_NB

        annotation SummarizationSetBy = Automatic

        
    column 'NMAC_DSTRCT_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: NMAC_DSTRCT_CD

        annotation SummarizationSetBy = Automatic

        
    column 'NMAC_RGN_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: NMAC_RGN_CD

        annotation SummarizationSetBy = Automatic

        
    column 'ORGNL_PSTL_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: ORGNL_PSTL_CD

        annotation SummarizationSetBy = Automatic

        
    column 'PHYSCL_ADRS_TX'
        dataType: string
        summarizeBy: none
        sourceColumn: PHYSCL_ADRS_TX

        annotation SummarizationSetBy = Automatic

        
    column 'PHYSCL_CTY_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: PHYSCL_CTY_NM

        annotation SummarizationSetBy = Automatic

        
    column 'PHYSCL_PSTL_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: PHYSCL_PSTL_CD

        annotation SummarizationSetBy = Automatic

        
    column 'PHYSCL_ST_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: PHYSCL_ST_CD

        annotation SummarizationSetBy = Automatic

        
    column 'PRMRY_FAX_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: PRMRY_FAX_NB

        annotation SummarizationSetBy = Automatic

        
    column 'PRMRY_MRKT_ARA_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: PRMRY_MRKT_ARA_NM

        annotation SummarizationSetBy = Automatic

        
    column 'PRMRY_PHN_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: PRMRY_PHN_NB

        annotation SummarizationSetBy = Automatic

        
    column 'PRTS_ARA_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: PRTS_ARA_CD

        annotation SummarizationSetBy = Automatic

        
    column 'PRT_ACTVTY_CTOVR_PRD'
        dataType: string
        summarizeBy: none
        sourceColumn: PRT_ACTVTY_CTOVR_PRD

        annotation SummarizationSetBy = Automatic

        
    column 'PSTL_CD_FLG'
        dataType: boolean
        summarizeBy: none
        sourceColumn: PSTL_CD_FLG

        annotation SummarizationSetBy = Automatic

        
    column 'R2_CTOVR_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: R2_CTOVR_DT

        annotation SummarizationSetBy = Automatic

        
    column 'R2_CTOVR_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: R2_CTOVR_IN

        annotation SummarizationSetBy = Automatic

        
    column 'R2_CTOVR_RCV_THRSLD_TM'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: R2_CTOVR_RCV_THRSLD_TM

        annotation SummarizationSetBy = Automatic

        
    column 'R2_CTOVR_UPDT_TS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: R2_CTOVR_UPDT_TS

        annotation SummarizationSetBy = Automatic

        
    column 'RFRNC_DLR_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: RFRNC_DLR_NB

        annotation SummarizationSetBy = Automatic

        
    column 'RNTL_SRCHRG_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: RNTL_SRCHRG_AM

        annotation SummarizationSetBy = Automatic

        
    column 'SBLT_MAPNG_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: SBLT_MAPNG_IN

        annotation SummarizationSetBy = Automatic

        
    column 'SL_PONT_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: SL_PONT_CD

        annotation SummarizationSetBy = Automatic

        
    column 'SND_DMI_DATA_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: SND_DMI_DATA_IN

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_ARA_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: SVC_ARA_CD

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_PDC_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: SVC_PDC_CD

        annotation SummarizationSetBy = Automatic

        
    column 'TCHNCL_SVC_BLTN_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: TCHNCL_SVC_BLTN_IN

        annotation SummarizationSetBy = Automatic

        
    column 'TM_ZN_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: TM_ZN_CD

        annotation SummarizationSetBy = Automatic

        
    column 'TRMNTN_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: TRMNTN_DT

        annotation SummarizationSetBy = Automatic

        
    column 'UPDTD_TM'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: UPDTD_TM

        annotation SummarizationSetBy = Automatic

        
    column 'UPDT_TS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: UPDT_TS

        annotation SummarizationSetBy = Automatic

        
    column 'UPDT_USR_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: UPDT_USR_ID

        annotation SummarizationSetBy = Automatic

        
    column 'USD_VHCL_IVNTRY_FLG'
        dataType: boolean
        summarizeBy: none
        sourceColumn: USD_VHCL_IVNTRY_FLG

        annotation SummarizationSetBy = Automatic

        
    column 'VHCL_INVC_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: VHCL_INVC_IN

        annotation SummarizationSetBy = Automatic

        
    column 'VHCL_MK_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: VHCL_MK_CD

        annotation SummarizationSetBy = Automatic

        
    column 'WRNTY_LBR_RT'
        dataType: double
        summarizeBy: sum
        sourceColumn: WRNTY_LBR_RT

        annotation SummarizationSetBy = Automatic

        



    partition 'DLR' = m
        mode: import
        source = 
            let Source = Oracle.Database(Server = "10.78.194.25:1521 / OPDBSRW", [HierarchicalNavigation = true]), #"Naviguated to Schema" = Source{[Schema = "DBSRW_SYS",Kind = "Schema"]}[Data], #"Filtered Rows" = Table.SelectRows(#"Naviguated to Schema", each true) in #"Filtered Rows"
        



    annotation PBI_ResultType = Table
