table 'RPR_ORDR'


    column 'VIN_ID'
        dataType: string
        summarizeBy: none

        dataCategory: Uncategorized
        annotation SummarizationSetBy = Automatic

        
    column 'id'
        dataType: string
        summarizeBy: none

        dataCategory: Uncategorized
        annotation SummarizationSetBy = Automatic

        
    column 'ALTRNT_TRNPTN_TX'
        dataType: string
        summarizeBy: none
        sourceColumn: ALTRNT_TRNPTN_TX

        annotation SummarizationSetBy = Automatic

        
    column 'APNTMT_CNFMTN_CD'
        dataType: double
        summarizeBy: sum
        sourceColumn: APNTMT_CNFMTN_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_CSTMR_MSCLNS_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_CSTMR_MSCLNS_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_CSTMR_MSCLNS_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_CSTMR_MSCLNS_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_CSTMR_RPR_ORDR_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_CSTMR_RPR_ORDR_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_CSTMR_RPR_ORDR_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_CSTMR_RPR_ORDR_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_GOG_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_GOG_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_GOG_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_GOG_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_INTRNL_MSCLNS_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_INTRNL_MSCLNS_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_INTRNL_MSCLNS_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_INTRNL_MSCLNS_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_INTRNL_RPR_ORDR_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_INTRNL_RPR_ORDR_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_INTRNL_RPR_ORDR_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_INTRNL_RPR_ORDR_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_LBR_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_LBR_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_LBR_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_LBR_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_MSCLNS_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_MSCLNS_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_MSCLNS_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_MSCLNS_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_PRTS_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_PRTS_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_PRTS_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_PRTS_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_SBLT_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_SBLT_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_SBLT_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_SBLT_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TAX_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TAX_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_ACTL_LBR_HR_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_ACTL_LBR_HR_NB

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_CSTMR_GOG_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_CSTMR_GOG_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_CSTMR_GOG_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_CSTMR_GOG_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_CSTMR_LBR_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_CSTMR_LBR_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_CSTMR_LBR_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_CSTMR_LBR_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_CSTMR_PRTS_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_CSTMR_PRTS_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_CSTMR_PRTS_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_CSTMR_PRTS_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_CSTMR_SBLT_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_CSTMR_SBLT_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_CSTMR_SBLT_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_CSTMR_SBLT_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_INTRNL_GOG_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_INTRNL_GOG_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_INTRNL_GOG_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_INTRNL_GOG_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_INTRNL_LBR_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_INTRNL_LBR_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_INTRNL_LBR_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_INTRNL_LBR_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_INTRNL_PRTS_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_INTRNL_PRTS_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_INTRNL_PRTS_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_INTRNL_PRTS_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_INTRNL_SBLT_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_INTRNL_SBLT_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_INTRNL_SBLT_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_INTRNL_SBLT_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_INVCD_LBR_HR_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_INVCD_LBR_HR_NB

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_WRNTY_GOG_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_WRNTY_GOG_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_WRNTY_GOG_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_WRNTY_GOG_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_WRNTY_LBR_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_WRNTY_LBR_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_WRNTY_LBR_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_WRNTY_LBR_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_WRNTY_PRTS_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_WRNTY_PRTS_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_WRNTY_PRTS_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_WRNTY_PRTS_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_WRNTY_SBLT_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_WRNTY_SBLT_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_TOTL_WRNTY_SBLT_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_TOTL_WRNTY_SBLT_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_WRNTY_MSCLNS_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_WRNTY_MSCLNS_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_WRNTY_MSCLNS_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_WRNTY_MSCLNS_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_WRNTY_RPR_ORDR_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_WRNTY_RPR_ORDR_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CLCLTD_WRNTY_RPR_ORDR_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CLCLTD_WRNTY_RPR_ORDR_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'CMPNY_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: CMPNY_NM

        annotation SummarizationSetBy = Automatic

        
    column 'CRNCY_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: CRNCY_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CRTE_TS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: CRTE_TS

        annotation SummarizationSetBy = Automatic

        
    column 'CRTE_USR_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: CRTE_USR_ID

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_ADRS_LN_1_TX'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_ADRS_LN_1_TX

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_ADRS_LN_2_TX'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_ADRS_LN_2_TX

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_APNTMT_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: CSTMR_APNTMT_IN

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_BRTH_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: CSTMR_BRTH_DT

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_CELL_PHN_CNTRY_CD'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_CELL_PHN_CNTRY_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_CELL_PHN_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_CELL_PHN_NB

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_CNTCT_MTHD_TYP_CD'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_CNTCT_MTHD_TYP_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_CNTRY_CD'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_CNTRY_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_CTY_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_CTY_NM

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_DY_PHN_CNTRY_CD'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_DY_PHN_CNTRY_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_DY_PHN_EXTNSN_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_DY_PHN_EXTNSN_NB

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_DY_PHN_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_DY_PHN_NB

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_EML_ADRS_TX'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_EML_ADRS_TX

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_EVNG_PHN_CNTRY_CD'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_EVNG_PHN_CNTRY_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_EVNG_PHN_EXTNSN_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_EVNG_PHN_EXTNSN_NB

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_EVNG_PHN_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_EVNG_PHN_NB

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_FAX_PHN_CNTRY_CD'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_FAX_PHN_CNTRY_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_FAX_PHN_EXTNSN_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_FAX_PHN_EXTNSN_NB

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_FAX_PHN_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_FAX_PHN_NB

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_FRST_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_FRST_NM

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_GNDR_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_GNDR_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_LNG_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_LNG_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_LST_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_LST_NM

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_MIDL_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_MIDL_NM

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_PGR_ORGNZN_PHN_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_PGR_ORGNZN_PHN_NB

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_PGR_PRSN_PHN_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_PGR_PRSN_PHN_NB

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_PRSNEL_EML_ADRS_TX'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_PRSNEL_EML_ADRS_TX

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_PRVCY_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: CSTMR_PRVCY_IN

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_PSTL_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_PSTL_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_PYMNT_MTHD_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_PYMNT_MTHD_NM

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_RSDNC_ADRS_LN_1_TX'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_RSDNC_ADRS_LN_1_TX

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_RSDNC_ADRS_LN_2_TX'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_RSDNC_ADRS_LN_2_TX

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_RSDNC_CNTRY_CD'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_RSDNC_CNTRY_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_RSDNC_CNTY_CD'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_RSDNC_CNTY_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_RSDNC_CNTY_NM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CSTMR_RSDNC_CNTY_NM

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_RSDNC_CTY_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_RSDNC_CTY_NM

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_RSDNC_PSTL_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_RSDNC_PSTL_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_RSDNC_ST_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_RSDNC_ST_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_SFX_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_SFX_NM

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_SLUTN_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_SLUTN_NM

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_ST_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_ST_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_TTL_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_TTL_NM

        annotation SummarizationSetBy = Automatic

        
    column 'CSTMR_TYP_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: CSTMR_TYP_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'DESIRED_PKUP_DTTM'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DESIRED_PKUP_DTTM

        annotation SummarizationSetBy = Automatic

        
    column 'DMS_CSTMR_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: DMS_CSTMR_ID

        annotation SummarizationSetBy = Automatic

        
    column 'DPRTMT_TYP_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: DPRTMT_TYP_NM

        annotation SummarizationSetBy = Automatic

        
    column 'DROP_OFF_DTTM'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: DROP_OFF_DTTM

        annotation SummarizationSetBy = Automatic

        
    column 'ESTMTD_RPR_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: ESTMTD_RPR_AM

        annotation SummarizationSetBy = Automatic

        
    column 'FOREGIN_VHCL_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: FOREGIN_VHCL_IN

        annotation SummarizationSetBy = Automatic

        
    column 'FOREGIN_VHCL_IN_SVC_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: FOREGIN_VHCL_IN_SVC_DT

        annotation SummarizationSetBy = Automatic

        
    column 'FRGN_VHCL_PRCHS_CNTRY_CD'
        dataType: double
        summarizeBy: sum
        sourceColumn: FRGN_VHCL_PRCHS_CNTRY_CD

        annotation SummarizationSetBy = Automatic

        
    column 'GOG_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: GOG_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'GOG_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: GOG_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'HS_RCRD_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: HS_RCRD_IN

        annotation SummarizationSetBy = Automatic

        
    column 'LBR_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: LBR_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'LBR_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: LBR_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'LCNS_PLAT_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: LCNS_PLAT_NB

        annotation SummarizationSetBy = Automatic

        
    column 'LNR_AVLBL_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: LNR_AVLBL_IN

        annotation SummarizationSetBy = Automatic

        
    column 'LNR_RQSTD_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: LNR_RQSTD_IN

        annotation SummarizationSetBy = Automatic

        
    column 'MLG_UNT_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: MLG_UNT_ID

        annotation SummarizationSetBy = Automatic

        
    column 'MSCLNS_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: MSCLNS_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'MSCLNS_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: MSCLNS_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'OPRTN_SVC_CTGRY_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: OPRTN_SVC_CTGRY_CD

        annotation SummarizationSetBy = Automatic

        
    column 'PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'PRTS_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: PRTS_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'PRTS_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: PRTS_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'RENT_DLY_RT_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: RENT_DLY_RT_AM

        annotation SummarizationSetBy = Automatic

        
    column 'RFRNC_DLR_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: RFRNC_DLR_NB

        annotation SummarizationSetBy = Automatic

        
    column 'RNTL_EXPNS_CLAS_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: RNTL_EXPNS_CLAS_CD

        annotation SummarizationSetBy = Automatic

        
    column 'RNTL_EXPNS_TOTL_DY_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: RNTL_EXPNS_TOTL_DY_NB

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_CLOS_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: RPR_ORDR_CLOS_DT

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_CMNT_TX'
        dataType: string
        summarizeBy: none
        sourceColumn: RPR_ORDR_CMNT_TX

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_CRNT_STS_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: RPR_ORDR_CRNT_STS_DT

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_CRTE_TS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: RPR_ORDR_CRTE_TS

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_CSTMR_PAY_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: RPR_ORDR_CSTMR_PAY_AM

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_INTRNL_PAY_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: RPR_ORDR_INTRNL_PAY_AM

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_INTRNL_RMRK_TX'
        dataType: boolean
        summarizeBy: none
        sourceColumn: RPR_ORDR_INTRNL_RMRK_TX

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_INVC_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: RPR_ORDR_INVC_DT

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_KY'
        dataType: string
        summarizeBy: none
        sourceColumn: RPR_ORDR_KY

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_MARITZ_KY'
        dataType: string
        summarizeBy: none
        sourceColumn: RPR_ORDR_MARITZ_KY

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: RPR_ORDR_NB

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_OPN_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: RPR_ORDR_OPN_DT

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_PAY_TYP'
        dataType: string
        summarizeBy: none
        sourceColumn: RPR_ORDR_PAY_TYP

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_STS_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: RPR_ORDR_STS_CD

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_TAG_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: RPR_ORDR_TAG_NB

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_TYP_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: RPR_ORDR_TYP_CD

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_UPDT_TS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: RPR_ORDR_UPDT_TS

        annotation SummarizationSetBy = Automatic

        
    column 'RPR_ORDR_WRNTY_PAY_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: RPR_ORDR_WRNTY_PAY_AM

        annotation SummarizationSetBy = Automatic

        
    column 'RQSTD_CSLTNT_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: RQSTD_CSLTNT_NM

        annotation SummarizationSetBy = Automatic

        
    column 'SBLT_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: SBLT_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'SBLT_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: SBLT_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'SPCFD_ORGNZN_CMPNY_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: SPCFD_ORGNZN_CMPNY_NM

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_ADVSR_FRST_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: SVC_ADVSR_FRST_NM

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_ADVSR_LST_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: SVC_ADVSR_LST_NM

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_ADVSR_MIDL_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: SVC_ADVSR_MIDL_NM

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_ADVSR_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: SVC_ADVSR_NB

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_ADVSR_NM_SFX'
        dataType: string
        summarizeBy: none
        sourceColumn: SVC_ADVSR_NM_SFX

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_APNTMT_FL_CNTNT_TX'
        dataType: double
        summarizeBy: sum
        sourceColumn: SVC_APNTMT_FL_CNTNT_TX

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_APNTMT_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: SVC_APNTMT_ID

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_APNTMT_MADE_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: SVC_APNTMT_MADE_DT

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_APNTMT_SCHDLD_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: SVC_APNTMT_SCHDLD_DT

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_APNTMT_SRC_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: SVC_APNTMT_SRC_NM

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_APNTMT_TYP_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: SVC_APNTMT_TYP_NM

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_CNTRCT_ID'
        dataType: double
        summarizeBy: sum
        sourceColumn: SVC_CNTRCT_ID

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_DS'
        dataType: string
        summarizeBy: none
        sourceColumn: SVC_DS

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_IN_MLG_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: SVC_IN_MLG_NB

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_OUT_MLG_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: SVC_OUT_MLG_NB

        annotation SummarizationSetBy = Automatic

        
    column 'TAX_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TAX_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TCHNCN_NM_GRP_TX'
        dataType: string
        summarizeBy: none
        sourceColumn: TCHNCN_NM_GRP_TX

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_ACTL_LBR_HR_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_ACTL_LBR_HR_NB

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_CSTMR_GOG_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_CSTMR_GOG_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_CSTMR_GOG_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_CSTMR_GOG_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_CSTMR_LBR_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_CSTMR_LBR_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_CSTMR_LBR_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_CSTMR_LBR_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_CSTMR_MSCLNS_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_CSTMR_MSCLNS_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_CSTMR_MSCLNS_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_CSTMR_MSCLNS_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_CSTMR_PRTS_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_CSTMR_PRTS_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_CSTMR_PRTS_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_CSTMR_PRTS_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_CSTMR_RPR_ORDR_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_CSTMR_RPR_ORDR_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_CSTMR_RPR_ORDR_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_CSTMR_RPR_ORDR_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_CSTMR_SBLT_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_CSTMR_SBLT_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_CSTMR_SBLT_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_CSTMR_SBLT_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_INTRNL_GOG_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_INTRNL_GOG_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_INTRNL_GOG_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_INTRNL_GOG_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_INTRNL_LBR_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_INTRNL_LBR_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_INTRNL_LBR_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_INTRNL_LBR_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_INTRNL_MSCLNS_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_INTRNL_MSCLNS_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_INTRNL_MSCLNS_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_INTRNL_MSCLNS_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_INTRNL_PRTS_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_INTRNL_PRTS_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_INTRNL_PRTS_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_INTRNL_PRTS_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_INTRNL_RPR_ORDR_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_INTRNL_RPR_ORDR_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_INTRNL_RPR_ORDR_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_INTRNL_RPR_ORDR_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_INTRNL_SBLT_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_INTRNL_SBLT_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_INTRNL_SBLT_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_INTRNL_SBLT_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_INVCD_LBR_HR_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_INVCD_LBR_HR_NB

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_WRNTY_GOG_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_WRNTY_GOG_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_WRNTY_GOG_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_WRNTY_GOG_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_WRNTY_LBR_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_WRNTY_LBR_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_WRNTY_LBR_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_WRNTY_LBR_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_WRNTY_MSCLNS_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_WRNTY_MSCLNS_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_WRNTY_MSCLNS_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_WRNTY_MSCLNS_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_WRNTY_PRTS_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_WRNTY_PRTS_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_WRNTY_PRTS_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_WRNTY_PRTS_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_WRNTY_RPR_ORDR_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_WRNTY_RPR_ORDR_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_WRNTY_RPR_ORDR_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_WRNTY_RPR_ORDR_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_WRNTY_SBLT_CST_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_WRNTY_SBLT_CST_AM

        annotation SummarizationSetBy = Automatic

        
    column 'TOTL_WRNTY_SBLT_PRC_AM'
        dataType: double
        summarizeBy: sum
        sourceColumn: TOTL_WRNTY_SBLT_PRC_AM

        annotation SummarizationSetBy = Automatic

        
    column 'UPDT_TS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: UPDT_TS

        annotation SummarizationSetBy = Automatic

        
    column 'UPDT_USR_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: UPDT_USR_ID

        annotation SummarizationSetBy = Automatic

        
    column 'VHCL_PK_UP_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: VHCL_PK_UP_DT

        annotation SummarizationSetBy = Automatic

        



    partition 'RPR_ORDR' = m
        mode: import
        source = 
            let Source = Oracle.Database(Server = "10.78.194.25:1521 / OPDBSRW", [HierarchicalNavigation = true]), #"Naviguated to Schema" = Source{[Schema = "DBSRW_SYS",Kind = "Schema"]}[Data], #"Filtered Rows" = Table.SelectRows(#"Naviguated to Schema", each true) in #"Filtered Rows"
        



    annotation PBI_ResultType = Table
