table 'SLS_ARA'


    column 'SLS_ARA_CD'
        dataType: string
        summarizeBy: none

        dataCategory: Uncategorized
        annotation SummarizationSetBy = Automatic

        
    column 'id'
        dataType: string
        summarizeBy: none

        dataCategory: Uncategorized
        annotation SummarizationSetBy = Automatic

        
    column 'ARA_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: ARA_CD

        annotation SummarizationSetBy = Automatic

        
    column 'ARA_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: ARA_NM

        annotation SummarizationSetBy = Automatic

        
    column 'CRTE_TS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: CRTE_TS

        annotation SummarizationSetBy = Automatic

        
    column 'CRTE_USR_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: CRTE_USR_ID

        annotation SummarizationSetBy = Automatic

        
    column 'SLS_RGN_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: SLS_RGN_CD

        annotation SummarizationSetBy = Automatic

        
    column 'UPDT_TS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: UPDT_TS

        annotation SummarizationSetBy = Automatic

        
    column 'UPDT_USR_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: UPDT_USR_ID

        annotation SummarizationSetBy = Automatic

        



    partition 'SLS_ARA' = m
        mode: import
        source = 
            let Source = Oracle.Database(Server = "10.78.194.25:1521 / OPDBSRW", [HierarchicalNavigation = true]), #"Naviguated to Schema" = Source{[Schema = "DBSRW_SYS",Kind = "Schema"]}[Data], #"Filtered Rows" = Table.SelectRows(#"Naviguated to Schema", each true) in #"Filtered Rows"
        



    annotation PBI_ResultType = Table
