table 'SLS_DSTRCT'


    column 'SLS_ARA_CD'
        dataType: string
        summarizeBy: none

        dataCategory: Uncategorized
        annotation SummarizationSetBy = Automatic

        
    column 'id'
        dataType: string
        summarizeBy: none

        dataCategory: Uncategorized
        annotation SummarizationSetBy = Automatic

        
    column 'CRTE_TS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: CRTE_TS

        annotation SummarizationSetBy = Automatic

        
    column 'CRTE_USR_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: CRTE_USR_ID

        annotation SummarizationSetBy = Automatic

        
    column 'DSTRCT_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: DSTRCT_CD

        annotation SummarizationSetBy = Automatic

        
    column 'DSTRCT_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: DSTRCT_NM

        annotation SummarizationSetBy = Automatic

        
    column 'SLS_DSTRCT_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: SLS_DSTRCT_CD

        annotation SummarizationSetBy = Automatic

        
    column 'UPDT_TS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: UPDT_TS

        annotation SummarizationSetBy = Automatic

        
    column 'UPDT_USR_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: UPDT_USR_ID

        annotation SummarizationSetBy = Automatic

        



    partition 'SLS_DSTRCT' = m
        mode: import
        source = 
            let Source = Oracle.Database(Server = ":1521 / ", [HierarchicalNavigation = true]), #"Naviguated to Schema" = Source{[Schema = "",Kind = "Schema"]}[Data], #"Filtered Rows" = Table.SelectRows(#"Naviguated to Schema", each true) in #"Filtered Rows"
        



    annotation PBI_ResultType = Table
