table 'SVC_VHCL'


    column 'VIN_ID'
        dataType: string
        summarizeBy: none

        dataCategory: Uncategorized
        annotation SummarizationSetBy = Automatic

        
    column 'id'
        dataType: string
        summarizeBy: none

        dataCategory: Uncategorized
        annotation SummarizationSetBy = Automatic

        
    column 'AFLT_CMPNY_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: AFLT_CMPNY_CD

        annotation SummarizationSetBy = Automatic

        
    column 'CRTE_TS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: CRTE_TS

        annotation SummarizationSetBy = Automatic

        
    column 'CRTE_USR_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: CRTE_USR_ID

        annotation SummarizationSetBy = Automatic

        
    column 'EMSNS_CRFCTN_TX'
        dataType: string
        summarizeBy: none
        sourceColumn: EMSNS_CRFCTN_TX

        annotation SummarizationSetBy = Automatic

        
    column 'ENGN_NUBMER'
        dataType: string
        summarizeBy: none
        sourceColumn: ENGN_NUBMER

        annotation SummarizationSetBy = Automatic

        
    column 'ENGN_PRFX_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: ENGN_PRFX_NB

        annotation SummarizationSetBy = Automatic

        
    column 'ENGN_SRS_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: ENGN_SRS_NB

        annotation SummarizationSetBy = Automatic

        
    column 'FRGN_DSTBTN_VHCL_IN'
        dataType: boolean
        summarizeBy: none
        sourceColumn: FRGN_DSTBTN_VHCL_IN

        annotation SummarizationSetBy = Automatic

        
    column 'IN_SVC_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: IN_SVC_DT

        annotation SummarizationSetBy = Automatic

        
    column 'IN_SVC_MLG_QT'
        dataType: double
        summarizeBy: sum
        sourceColumn: IN_SVC_MLG_QT

        annotation SummarizationSetBy = Automatic

        
    column 'LCNS_PLAT_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: LCNS_PLAT_NB

        annotation SummarizationSetBy = Automatic

        
    column 'LST_KNOWN_MLG_QT'
        dataType: double
        summarizeBy: sum
        sourceColumn: LST_KNOWN_MLG_QT

        annotation SummarizationSetBy = Automatic

        
    column 'LST_KNOW_MLG_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: LST_KNOW_MLG_DT

        annotation SummarizationSetBy = Automatic

        
    column 'MNFCR_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: MNFCR_DT

        annotation SummarizationSetBy = Automatic

        
    column 'OPTN_GRP_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: OPTN_GRP_CD

        annotation SummarizationSetBy = Automatic

        
    column 'PDI_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: PDI_DT

        annotation SummarizationSetBy = Automatic

        
    column 'PLNT_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: PLNT_NM

        annotation SummarizationSetBy = Automatic

        
    column 'PRDCTN_MNTH_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: PRDCTN_MNTH_NB

        annotation SummarizationSetBy = Automatic

        
    column 'RTL_SLS_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: RTL_SLS_DT

        annotation SummarizationSetBy = Automatic

        
    column 'SLD_BY_DLR_CTY_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: SLD_BY_DLR_CTY_NM

        annotation SummarizationSetBy = Automatic

        
    column 'SLD_BY_DLR_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: SLD_BY_DLR_NB

        annotation SummarizationSetBy = Automatic

        
    column 'SLD_BY_DLR_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: SLD_BY_DLR_NM

        annotation SummarizationSetBy = Automatic

        
    column 'SLD_BY_DLR_ST_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: SLD_BY_DLR_ST_CD

        annotation SummarizationSetBy = Automatic

        
    column 'SL_TYP_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: SL_TYP_CD

        annotation SummarizationSetBy = Automatic

        
    column 'STK_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: STK_NB

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_VHCL_CRTE_TS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: SVC_VHCL_CRTE_TS

        annotation SummarizationSetBy = Automatic

        
    column 'SVC_VHCL_UPDT_TS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: SVC_VHCL_UPDT_TS

        annotation SummarizationSetBy = Automatic

        
    column 'TRM_LVL_TX'
        dataType: string
        summarizeBy: none
        sourceColumn: TRM_LVL_TX

        annotation SummarizationSetBy = Automatic

        
    column 'TRNMSN_TX'
        dataType: string
        summarizeBy: none
        sourceColumn: TRNMSN_TX

        annotation SummarizationSetBy = Automatic

        
    column 'UPDT_TS'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: UPDT_TS

        annotation SummarizationSetBy = Automatic

        
    column 'UPDT_USR_ID'
        dataType: string
        summarizeBy: none
        sourceColumn: UPDT_USR_ID

        annotation SummarizationSetBy = Automatic

        
    column 'VHCL_BDY_CLR_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: VHCL_BDY_CLR_CD

        annotation SummarizationSetBy = Automatic

        
    column 'VHCL_BDY_CLR_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: VHCL_BDY_CLR_NM

        annotation SummarizationSetBy = Automatic

        
    column 'VHCL_CLAS_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: VHCL_CLAS_CD

        annotation SummarizationSetBy = Automatic

        
    column 'VHCL_LN_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: VHCL_LN_CD

        annotation SummarizationSetBy = Automatic

        
    column 'VHCL_LN_DS'
        dataType: string
        summarizeBy: none
        sourceColumn: VHCL_LN_DS

        annotation SummarizationSetBy = Automatic

        
    column 'VHCL_MDL_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: VHCL_MDL_CD

        annotation SummarizationSetBy = Automatic

        
    column 'VHCL_MDL_DS'
        dataType: string
        summarizeBy: none
        sourceColumn: VHCL_MDL_DS

        annotation SummarizationSetBy = Automatic

        
    column 'VHCL_MDL_YR_NB'
        dataType: double
        summarizeBy: sum
        sourceColumn: VHCL_MDL_YR_NB

        annotation SummarizationSetBy = Automatic

        
    column 'VHCL_MK_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: VHCL_MK_CD

        annotation SummarizationSetBy = Automatic

        
    column 'VHCL_MK_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: VHCL_MK_NM

        annotation SummarizationSetBy = Automatic

        
    column 'VHCL_TRM_CD'
        dataType: string
        summarizeBy: none
        sourceColumn: VHCL_TRM_CD

        annotation SummarizationSetBy = Automatic

        
    column 'VHCL_TRM_NM'
        dataType: string
        summarizeBy: none
        sourceColumn: VHCL_TRM_NM

        annotation SummarizationSetBy = Automatic

        
    column 'WRNTY_EXPRTN_DT'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: WRNTY_EXPRTN_DT

        annotation SummarizationSetBy = Automatic

        
    column 'WRNTY_EXPRTN_MLG_QT'
        dataType: double
        summarizeBy: sum
        sourceColumn: WRNTY_EXPRTN_MLG_QT

        annotation SummarizationSetBy = Automatic

        



    partition 'SVC_VHCL' = m
        mode: import
        source = 
            let Source = Oracle.Database(Server = ":1521 / ", [HierarchicalNavigation = true]), #"Naviguated to Schema" = Source{[Schema = "",Kind = "Schema"]}[Data], #"Filtered Rows" = Table.SelectRows(#"Naviguated to Schema", each true) in #"Filtered Rows"
        



    annotation PBI_ResultType = Table
